=== randokuruza70/manual/manual/ewd/dtd/compact.dtd
<!-- <?xml version="1.0" encoding="UTF-8"?> -->
<!-- XML DTD for TOYOTA EWD -->
<!--
	EWD DTD for Compact XML

	Copyright (c) 2000-2012 SHINTEC HOZUMI Co.,LTD.
	All Rights Reserved. 

	ver 1.00	2011/06/20
	ver 2.0		2011/12/06 change attribute ver value
	ver 2.1		2012/07/10 no change in this file
-->

<!ENTITY % CompactItem "(ps | gp | part )">
<!ENTITY % psType "(conn | jb | rb | gp | w2w )">
<!ENTITY % Code "CDATA">
<!ENTITY % pinNo "CDATA">
<!ENTITY % figID "CDATA">
<!ENTITY % gpType "(conn | jb | rb | w2w )">
<!ENTITY % partElement "(path+, conn*, commref*, line* )">
<!ENTITY % partType "(conn | jb | rb | gp | w2w | gnd | ant | omit | sh | tw | cs | bat | annex)">
<!ENTITY % split "( h )">
<!ENTITY % dir "(h | v)">
<!ENTITY % comment "CDATA">
<!ENTITY % d "CDATA">
<!ENTITY % conn "(path+ , commref* )">
<!ENTITY % lineID "CDATA">
<!ENTITY % commref "(lineref? | partref )">
<!ELEMENT compact-defs (%CompactItem;)*>
<!ATTLIST compact-defs
	ver CDATA #IMPLIED
	pubno CDATA #REQUIRED
>
<!ELEMENT ps EMPTY>
<!ATTLIST ps
	type %psType; #REQUIRED
	code %Code; #REQUIRED
	pinNo %pinNo; #IMPLIED
	figID %figID; #REQUIRED
>
<!ELEMENT gp EMPTY>
<!ATTLIST gp
	type %gpType; #REQUIRED
	code %Code; #REQUIRED
	pinNo %pinNo; #IMPLIED
	figID %figID; #REQUIRED
>
<!ELEMENT part %partElement;>
<!ATTLIST part
	type %partType; #REQUIRED
	code %Code; #REQUIRED
	pinNo %pinNo; #IMPLIED
	figID %figID; #REQUIRED
	split %split; #IMPLIED
	dir %dir; #IMPLIED
	comment %comment; #IMPLIED
>
<!ELEMENT path EMPTY>
<!ATTLIST path
	d %d; #REQUIRED
>
<!ELEMENT conn %conn;>
<!ATTLIST conn
	lineID %lineID; #REQUIRED
>
<!ELEMENT commref %commref;>
<!ATTLIST commref
	figID %figID; #REQUIRED
>
<!ELEMENT lineref EMPTY>
<!ATTLIST lineref
	lineID %lineID; #REQUIRED
>
<!ELEMENT partref EMPTY>
<!ATTLIST partref
	figID %lineID; #IMPLIED
	dir %dir; #REQUIRED
>
<!ELEMENT line EMPTY>
<!ATTLIST line
	lineID %lineID; #REQUIRED
>

=== randokuruza70/manual/manual/ewd/contents/system/compact/RWD-F.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE compact-defs SYSTEM "../../../dtd/compact.dtd">
<compact-defs pubno="EM25T2E" ver="2.1.2.9">
    <part code="2" figID="1" type="rb">
        <path d="M 276.20, 27.71 L 326.34, 27.71 L 326.34, 103.77 L 276.20, 103.77 L 276.20, 27.71 "/>
    </part>
    <part code="2" figID="2" type="rb">
        <path d="M 106.23, 27.71 L 156.75, 27.71 L 156.75, 103.77 L 106.23, 103.77 L 106.23, 27.71 "/>
    </part>
    <part code="I105" figID="3" type="conn">
        <path d="M 101.42, 154.19 L 127.48, 154.19 L 127.48, 189.32 L 101.42, 189.32 L 101.42, 154.19 "/>
    </part>
    <part code="I107" figID="4" type="conn">
        <path d="M 65.34, 239.18 L 84.99, 239.18 L 84.99, 274.31 L 65.34, 274.31 L 65.34, 239.18 "/>
    </part>
    <part code="2" figID="5" type="rb">
        <path d="M 254.96, 239.75 L 388.81, 239.75 L 388.81, 350.23 L 254.96, 350.23 L 254.96, 239.75 "/>
    </part>
    <part code="L51,L55,L58" figID="6" type="conn">
        <path d="M 141.83, 408.02 L 181.19, 408.02 L 181.19, 479.41 L 141.83, 479.41 L 141.83, 408.02 "/>
    </part>
    <part code="L7" figID="7" split="h" type="conn">
        <path d="M 135.98, 518.20 L 280.45, 518.20 L 280.45, 564.69 L 135.98, 564.69 L 135.98, 518.20 "/>
        <conn lineID="10">
            <path d="M 257.35, 512.22 L 265.08, 512.22 L 265.08, 527.83 L 257.35, 527.83 L 257.35, 512.22 "/>
        </conn>
        <conn lineID="6">
            <path d="M 147.04, 554.70 L 154.54, 554.70 L 154.54, 570.96 L 147.04, 570.96 L 147.04, 554.70 "/>
        </conn>
        <conn lineID="7">
            <path d="M 147.04, 512.27 L 154.47, 512.27 L 154.47, 527.83 L 147.04, 527.83 L 147.04, 512.27 "/>
        </conn>
    </part>
    <part code="c1,c2" figID="8" type="conn">
        <path d="M 722.38, 264.67 L 739.38, 264.67 L 739.38, 316.80 L 722.38, 316.80 L 722.38, 264.67 "/>
    </part>
    <part code="d1,f1" figID="9" type="conn">
        <path d="M 807.36, 264.67 L 824.36, 264.67 L 824.36, 316.80 L 807.36, 316.80 L 807.36, 264.67 "/>
    </part>
    <part code="I94" figID="10" type="conn">
        <path d="M 373.94, 435.78 L 390.93, 435.78 L 390.93, 468.90 L 373.94, 468.90 L 373.94, 435.78 "/>
    </part>
    <part code="IL5" figID="14" type="w2w">
        <path d="M 140.58, 348.23 L 178.79, 348.23 L 178.79, 367.79 L 140.58, 367.79 L 140.58, 348.23 "/>
    </part>
    <part code="IL1" figID="15" type="w2w">
        <path d="M 140.59, 339.73 L 177.79, 339.73 L 177.79, 352.23 L 140.59, 352.23 L 140.59, 339.73 "/>
    </part>
    <part code="LI1" figID="16" type="w2w">
        <path d="M 248.37, 443.14 L 271.95, 443.14 L 271.95, 462.71 L 248.37, 462.71 L 248.37, 443.14 "/>
    </part>
    <part code="IS3" figID="17" type="w2w">
        <path d="M 367.35, 560.69 L 390.93, 560.69 L 390.93, 580.26 L 367.35, 580.26 L 367.35, 560.69 "/>
    </part>
    <part code="TS1" figID="18" type="w2w">
        <path d="M 591.00, 526.70 L 611.90, 526.70 L 611.90, 546.26 L 591.00, 546.26 L 591.00, 526.70 "/>
    </part>
    <part code="bT1" figID="19" type="w2w">
        <path d="M 591.42, 441.71 L 611.90, 441.71 L 611.90, 461.27 L 591.42, 461.27 L 591.42, 441.71 "/>
    </part>
    <part code="db1" figID="20" type="w2w">
        <path d="M 591.42, 382.22 L 611.90, 382.22 L 611.90, 401.78 L 591.42, 401.78 L 591.42, 382.22 "/>
    </part>
    <part code="aS2" figID="21" type="w2w">
        <path d="M 650.91, 441.71 L 671.39, 441.71 L 671.39, 461.27 L 650.91, 461.27 L 650.91, 441.71 "/>
    </part>
    <part code="ca3" figID="22" type="w2w">
        <path d="M 650.91, 382.22 L 671.39, 382.22 L 671.39, 401.78 L 650.91, 401.78 L 650.91, 382.22 "/>
    </part>
    <part code="TS1" figID="23" type="w2w">
        <path d="M 718.50, 519.63 L 739.38, 519.63 L 739.38, 539.20 L 718.50, 539.20 L 718.50, 519.63 "/>
    </part>
    <part code="aS2" figID="24" type="w2w">
        <path d="M 718.50, 441.71 L 739.38, 441.71 L 739.38, 461.27 L 718.50, 461.27 L 718.50, 441.71 "/>
    </part>
    <part code="ca4" figID="25" type="w2w">
        <path d="M 718.90, 382.22 L 739.38, 382.22 L 739.38, 401.78 L 718.90, 401.78 L 718.90, 382.22 "/>
    </part>
    <part code="bT1" figID="26" type="w2w">
        <path d="M 803.41, 484.20 L 824.36, 484.20 L 824.36, 503.77 L 803.41, 503.77 L 803.41, 484.20 "/>
    </part>
    <part code="bf1" figID="27" type="w2w">
        <path d="M 803.88, 375.16 L 824.36, 375.16 L 824.36, 394.72 L 803.88, 394.72 L 803.88, 375.16 "/>
    </part>
    <part code="LA" figID="28" type="gp">
        <path d="M 142.35, 679.67 L 163.60, 679.67 L 163.60, 710.00 L 142.35, 710.00 L 142.35, 679.67 "/>
    </part>
    <part code="TA" figID="29" type="gp">
        <path d="M 720.25, 679.67 L 741.50, 679.67 L 741.50, 710.00 L 720.25, 710.00 L 720.25, 679.67 "/>
    </part>
</compact-defs>

=== randokuruza70/manual/manual/ewd/contents/system/compact/FFL-F.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE compact-defs SYSTEM "../../../dtd/compact.dtd">
<compact-defs pubno="EM25T2E" ver="2.1.2.9">
    <part code="L24" figID="1" type="conn">
        <path d="M 59.49, 391.59 L 399.43, 391.59 L 399.43, 529.83 L 59.49, 529.83 L 59.49, 391.59 "/>
    </part>
    <part code="L53" figID="2" type="conn">
        <path d="M 283.02, 614.18 L 305.95, 614.18 L 305.95, 647.37 L 283.02, 647.37 L 283.02, 614.18 "/>
    </part>
    <part code="L25" figID="3" type="conn">
        <path d="M 824.36, 162.69 L 917.85, 162.69 L 917.85, 316.80 L 824.36, 316.80 L 824.36, 162.69 "/>
    </part>
    <part code="J1" figID="4" type="conn">
        <path d="M 594.79, 299.73 L 611.90, 299.73 L 611.90, 332.92 L 594.79, 332.92 L 594.79, 299.73 "/>
    </part>
    <part code="J2" figID="5" type="conn">
        <path d="M 671.27, 299.73 L 688.38, 299.73 L 688.38, 332.92 L 671.27, 332.92 L 671.27, 299.73 "/>
    </part>
    <part code="4" figID="6" type="rb">
        <path d="M 38.24, 27.71 L 84.66, 27.71 L 84.66, 103.77 L 38.24, 103.77 L 38.24, 27.71 "/>
    </part>
    <part code="2" figID="7" type="rb">
        <path d="M 182.72, 61.28 L 224.35, 61.28 L 224.35, 171.76 L 182.72, 171.76 L 182.72, 61.28 "/>
    </part>
    <part code="2" figID="8" type="rb">
        <path d="M 344.19, 27.71 L 395.65, 27.71 L 395.65, 103.77 L 344.19, 103.77 L 344.19, 27.71 "/>
    </part>
    <part code="2" figID="9" type="rb">
        <path d="M 322.95, 180.26 L 374.34, 180.26 L 374.34, 265.24 L 322.95, 265.24 L 322.95, 180.26 "/>
    </part>
    <part code="2" figID="10" type="rb">
        <path d="M 42.49, 222.75 L 99.88, 222.75 L 99.88, 307.73 L 42.49, 307.73 L 42.49, 222.75 "/>
    </part>
    <part code="I106" figID="11" type="conn">
        <path d="M 184.32, 213.68 L 203.97, 213.68 L 203.97, 248.81 L 184.32, 248.81 L 184.32, 213.68 "/>
    </part>
    <part code="IL6" figID="17" type="w2w">
        <path d="M 38.61, 348.23 L 76.80, 348.23 L 76.80, 367.79 L 38.61, 367.79 L 38.61, 348.23 "/>
    </part>
    <part code="IL2" figID="18" type="w2w">
        <path d="M 38.59, 339.73 L 75.80, 339.73 L 75.80, 352.23 L 38.59, 352.23 L 38.59, 339.73 "/>
    </part>
    <part code="AI1" figID="19" type="w2w">
        <path d="M 39.01, 127.26 L 59.49, 127.26 L 59.49, 146.83 L 39.01, 146.83 L 39.01, 127.26 "/>
    </part>
    <part code="IL5" figID="20" type="w2w">
        <path d="M 315.89, 348.23 L 357.26, 348.23 L 357.26, 367.79 L 315.89, 367.79 L 315.89, 348.23 "/>
    </part>
    <part code="IL1" figID="21" type="w2w">
        <path d="M 315.89, 339.73 L 356.26, 339.73 L 356.26, 352.23 L 315.89, 352.23 L 315.89, 339.73 "/>
    </part>
    <part code="IL5" figID="22" type="w2w">
        <path d="M 392.38, 246.24 L 433.74, 246.24 L 433.74, 258.74 L 392.38, 258.74 L 392.38, 246.24 "/>
    </part>
    <part code="IL1" figID="23" type="w2w">
        <path d="M 392.38, 230.68 L 432.74, 230.68 L 432.74, 250.24 L 392.38, 250.24 L 392.38, 230.68 "/>
    </part>
    <part code="KI2" figID="24" type="w2w">
        <path d="M 591.02, 475.71 L 611.90, 475.71 L 611.90, 495.27 L 591.02, 495.27 L 591.02, 475.71 "/>
    </part>
    <part code="JK2" figID="25" type="w2w">
        <path d="M 591.02, 399.22 L 611.90, 399.22 L 611.90, 418.78 L 591.02, 418.78 L 591.02, 399.22 "/>
    </part>
    <part code="JK2" figID="26" type="w2w">
        <path d="M 591.00, 247.68 L 611.90, 247.68 L 611.90, 267.24 L 591.00, 267.24 L 591.00, 247.68 "/>
    </part>
    <part code="KI2" figID="27" type="w2w">
        <path d="M 591.00, 188.19 L 611.90, 188.19 L 611.90, 207.75 L 591.00, 207.75 L 591.00, 188.19 "/>
    </part>
    <part code="KI2" figID="28" type="w2w">
        <path d="M 667.54, 475.71 L 688.38, 475.71 L 688.38, 495.27 L 667.54, 495.27 L 667.54, 475.71 "/>
    </part>
    <part code="JK2" figID="29" type="w2w">
        <path d="M 667.54, 399.22 L 688.38, 399.22 L 688.38, 418.78 L 667.54, 418.78 L 667.54, 399.22 "/>
    </part>
    <part code="JK2" figID="30" type="w2w">
        <path d="M 667.49, 247.68 L 688.38, 247.68 L 688.38, 267.24 L 667.49, 267.24 L 667.49, 247.68 "/>
    </part>
    <part code="KI2" figID="31" type="w2w">
        <path d="M 667.49, 188.19 L 688.38, 188.19 L 688.38, 207.75 L 667.49, 207.75 L 667.49, 188.19 "/>
    </part>
    <part code="CA4" figID="32" type="w2w">
        <path d="M 741.29, 536.63 L 764.87, 536.63 L 764.87, 556.19 L 741.29, 556.19 L 741.29, 536.63 "/>
    </part>
    <part code="AC1" figID="33" type="w2w">
        <path d="M 795.38, 543.69 L 815.86, 543.69 L 815.86, 563.26 L 795.38, 563.26 L 795.38, 543.69 "/>
    </part>
    <part code="AI3" figID="34" type="w2w">
        <path d="M 792.28, 484.20 L 829.19, 484.20 L 829.19, 496.70 L 792.28, 496.70 L 792.28, 484.20 "/>
    </part>
    <part code="AI3" figID="35" type="w2w">
        <path d="M 791.88, 475.71 L 829.19, 475.71 L 829.19, 488.20 L 791.88, 488.20 L 791.88, 475.71 "/>
    </part>
    <part code="AI3" figID="36" type="w2w">
        <path d="M 791.81, 467.21 L 825.85, 467.21 L 825.85, 479.71 L 791.81, 479.71 L 791.81, 467.21 "/>
    </part>
    <part code="AI3" figID="37" type="w2w">
        <path d="M 791.71, 451.64 L 825.85, 451.64 L 825.85, 471.21 L 791.71, 471.21 L 791.71, 451.64 "/>
    </part>
    <part code="AC5" figID="38" type="w2w">
        <path d="M 862.97, 552.19 L 893.83, 552.19 L 893.83, 571.76 L 862.97, 571.76 L 862.97, 552.19 "/>
    </part>
    <part code="IC2" figID="39" type="w2w">
        <path d="M 862.97, 543.69 L 893.83, 543.69 L 893.83, 556.19 L 862.97, 556.19 L 862.97, 543.69 "/>
    </part>
    <part code="IL6" figID="40" type="w2w">
        <path d="M 860.27, 356.73 L 901.16, 356.73 L 901.16, 369.22 L 860.27, 369.22 L 860.27, 356.73 "/>
    </part>
    <part code="IL2" figID="41" type="w2w">
        <path d="M 862.80, 341.16 L 900.16, 341.16 L 900.16, 360.73 L 862.80, 360.73 L 862.80, 341.16 "/>
    </part>
    <part code="AI3" figID="42" type="w2w">
        <path d="M 902.36, 451.64 L 926.35, 451.64 L 926.35, 471.21 L 902.36, 471.21 L 902.36, 451.64 "/>
    </part>
    <part code="LB" figID="43" type="gp">
        <path d="M 244.33, 679.67 L 265.58, 679.67 L 265.58, 710.00 L 244.33, 710.00 L 244.33, 679.67 "/>
    </part>
    <part code="LA" figID="44" type="gp">
        <path d="M 286.83, 679.67 L 308.07, 679.67 L 308.07, 710.00 L 286.83, 710.00 L 286.83, 679.67 "/>
    </part>
    <part code="IE" figID="45" type="gp">
        <path d="M 592.78, 679.67 L 614.02, 679.67 L 614.02, 710.00 L 592.78, 710.00 L 592.78, 679.67 "/>
    </part>
    <part code="IG" figID="46" type="gp">
        <path d="M 669.26, 679.67 L 690.51, 679.67 L 690.51, 710.00 L 669.26, 710.00 L 669.26, 679.67 "/>
    </part>
    <part code="CE" figID="47" type="gp">
        <path d="M 745.75, 679.67 L 767.00, 679.67 L 767.00, 710.00 L 745.75, 710.00 L 745.75, 679.67 "/>
    </part>
    <part code="CC" figID="48" type="gp">
        <path d="M 796.74, 679.67 L 817.99, 679.67 L 817.99, 710.00 L 796.74, 710.00 L 796.74, 679.67 "/>
    </part>
    <part code="CA" figID="49" type="gp">
        <path d="M 864.73, 679.67 L 885.98, 679.67 L 885.98, 710.00 L 864.73, 710.00 L 864.73, 679.67 "/>
    </part>
</compact-defs>

=== randokuruza70/manual/manual/ewd/contents/system/compact/RFL-F.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE compact-defs SYSTEM "../../../dtd/compact.dtd">
<compact-defs pubno="EM25T2E" ver="2.1.2.9">
    <part code="L25" figID="1" type="conn">
        <path d="M 875.35, 162.69 L 943.34, 162.69 L 943.34, 316.80 L 875.35, 316.80 L 875.35, 162.69 "/>
    </part>
    <part code="4" figID="2" type="rb">
        <path d="M 140.23, 27.71 L 186.64, 27.71 L 186.64, 103.77 L 140.23, 103.77 L 140.23, 27.71 "/>
    </part>
    <part code="2" figID="3" type="rb">
        <path d="M 284.70, 61.28 L 326.33, 61.28 L 326.33, 171.76 L 284.70, 171.76 L 284.70, 61.28 "/>
    </part>
    <part code="2" figID="4" type="rb">
        <path d="M 144.48, 231.25 L 201.87, 231.25 L 201.87, 316.23 L 144.48, 316.23 L 144.48, 231.25 "/>
    </part>
    <part code="T5" figID="5" type="conn">
        <path d="M 764.87, 477.14 L 824.36, 477.14 L 824.36, 546.26 L 764.87, 546.26 L 764.87, 477.14 "/>
    </part>
    <part code="2" figID="6" type="rb">
        <path d="M 637.39, 137.76 L 694.78, 137.76 L 694.78, 222.75 L 637.39, 222.75 L 637.39, 137.76 "/>
    </part>
    <part code="2" figID="7" type="rb">
        <path d="M 658.64, 27.71 L 710.77, 27.71 L 710.77, 103.77 L 658.64, 103.77 L 658.64, 27.71 "/>
    </part>
    <part code="L53" figID="8" type="conn">
        <path d="M 283.02, 614.18 L 305.95, 614.18 L 305.95, 647.37 L 283.02, 647.37 L 283.02, 614.18 "/>
    </part>
    <part code="L24" figID="9" type="conn">
        <path d="M 67.99, 400.65 L 399.43, 400.65 L 399.43, 520.76 L 67.99, 520.76 L 67.99, 400.65 "/>
    </part>
    <part code="T18" figID="10" split="h" type="conn">
        <path d="M 688.38, 492.70 L 722.38, 492.70 L 722.38, 530.70 L 688.38, 530.70 L 688.38, 492.70 "/>
        <conn lineID="21">
            <path d="M 699.38, 520.71 L 706.95, 520.71 L 706.95, 536.89 L 699.38, 536.89 L 699.38, 520.71 "/>
        </conn>
        <conn lineID="22">
            <path d="M 699.85, 486.70 L 706.87, 486.70 L 706.87, 502.34 L 699.85, 502.34 L 699.85, 486.70 "/>
        </conn>
    </part>
    <part code="IL2" figID="16" type="w2w">
        <path d="M 140.57, 348.23 L 161.47, 348.23 L 161.47, 367.79 L 140.57, 367.79 L 140.57, 348.23 "/>
    </part>
    <part code="AI1" figID="17" type="w2w">
        <path d="M 140.99, 127.26 L 161.47, 127.26 L 161.47, 146.83 L 140.99, 146.83 L 140.99, 127.26 "/>
    </part>
    <part code="LI1" figID="18" type="w2w">
        <path d="M 630.34, 273.17 L 654.39, 273.17 L 654.39, 292.74 L 630.34, 292.74 L 630.34, 273.17 "/>
    </part>
    <part code="ST3" figID="19" type="w2w">
        <path d="M 693.04, 407.72 L 713.88, 407.72 L 713.88, 427.28 L 693.04, 427.28 L 693.04, 407.72 "/>
    </part>
    <part code="TS2" figID="20" type="w2w">
        <path d="M 786.52, 341.16 L 807.37, 341.16 L 807.37, 360.73 L 786.52, 360.73 L 786.52, 341.16 "/>
    </part>
    <part code="IS3" figID="21" type="w2w">
        <path d="M 786.48, 288.74 L 807.37, 288.74 L 807.37, 308.30 L 786.48, 308.30 L 786.48, 288.74 "/>
    </part>
    <part code="LI1" figID="22" type="w2w">
        <path d="M 783.31, 186.75 L 807.37, 186.75 L 807.37, 206.32 L 783.31, 206.32 L 783.31, 186.75 "/>
    </part>
    <part code="AC1" figID="23" type="w2w">
        <path d="M 905.87, 535.20 L 926.35, 535.20 L 926.35, 554.76 L 905.87, 554.76 L 905.87, 535.20 "/>
    </part>
    <part code="AI3" figID="24" type="w2w">
        <path d="M 902.19, 468.64 L 926.35, 468.64 L 926.35, 488.20 L 902.19, 488.20 L 902.19, 468.64 "/>
    </part>
    <part code="IL2" figID="25" type="w2w">
        <path d="M 905.30, 341.16 L 926.35, 341.16 L 926.35, 360.73 L 905.30, 360.73 L 905.30, 341.16 "/>
    </part>
    <part code="IC2" figID="26" type="w2w">
        <path d="M 990.45, 535.20 L 1011.33, 535.20 L 1011.33, 554.76 L 990.45, 554.76 L 990.45, 535.20 "/>
    </part>
    <part code="LB" figID="27" type="gp">
        <path d="M 244.33, 679.67 L 265.58, 679.67 L 265.58, 710.00 L 244.33, 710.00 L 244.33, 679.67 "/>
    </part>
    <part code="LA" figID="28" type="gp">
        <path d="M 286.83, 679.67 L 308.07, 679.67 L 308.07, 710.00 L 286.83, 710.00 L 286.83, 679.67 "/>
    </part>
    <part code="TB" figID="29" type="gp">
        <path d="M 643.77, 679.67 L 665.01, 679.67 L 665.01, 710.00 L 643.77, 710.00 L 643.77, 679.67 "/>
    </part>
    <part code="TC" figID="30" type="gp">
        <path d="M 694.76, 679.67 L 716.01, 679.67 L 716.01, 710.00 L 694.76, 710.00 L 694.76, 679.67 "/>
    </part>
    <part code="TA" figID="31" type="gp">
        <path d="M 788.24, 679.67 L 809.49, 679.67 L 809.49, 710.00 L 788.24, 710.00 L 788.24, 679.67 "/>
    </part>
    <part code="CC" figID="32" type="gp">
        <path d="M 907.22, 679.67 L 928.47, 679.67 L 928.47, 710.00 L 907.22, 710.00 L 907.22, 679.67 "/>
    </part>
    <part code="CA" figID="33" type="gp">
        <path d="M 992.21, 679.67 L 1013.46, 679.67 L 1013.46, 710.00 L 992.21, 710.00 L 992.21, 679.67 "/>
    </part>
</compact-defs>

=== randokuruza70/manual/manual/ewd/contents/system/compact/SS-1HZ-B.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE compact-defs SYSTEM "../../../dtd/compact.dtd">
<compact-defs pubno="EM25T2E" ver="2.1.2.9">
    <part code="2" figID="1" type="rb">
        <path d="M 658.64, 27.71 L 700.16, 27.71 L 700.16, 103.77 L 658.64, 103.77 L 658.64, 27.71 "/>
    </part>
    <part code="I59,I70" figID="2" type="conn">
        <path d="M 660.24, 187.05 L 685.93, 187.05 L 685.93, 258.44 L 660.24, 258.44 L 660.24, 187.05 "/>
    </part>
    <part code="4" figID="3" type="rb">
        <path d="M 344.19, 27.71 L 385.38, 27.71 L 385.38, 103.77 L 344.19, 103.77 L 344.19, 27.71 "/>
    </part>
    <part code="1" figID="4" type="rb">
        <path d="M 348.44, 180.26 L 408.48, 180.26 L 408.48, 282.24 L 348.44, 282.24 L 348.44, 180.26 "/>
    </part>
    <part code="D10,E3" figID="5" type="conn">
        <path d="M 144.48, 222.18 L 178.47, 222.18 L 178.47, 299.80 L 144.48, 299.80 L 144.48, 222.18 "/>
    </part>
    <part code="E2,F2" figID="6" type="conn">
        <path d="M 50.99, 392.15 L 84.99, 392.15 L 84.99, 469.77 L 50.99, 469.77 L 50.99, 392.15 "/>
    </part>
    <part code="A36,D8,E1,E4,F1" figID="7" type="conn">
        <path d="M 127.48, 392.15 L 203.97, 392.15 L 203.97, 469.77 L 127.48, 469.77 L 127.48, 392.15 "/>
    </part>
    <part code="C89,D5" figID="8" split="h" type="conn">
        <path d="M 246.46, 399.22 L 322.95, 399.22 L 322.95, 437.21 L 246.46, 437.21 L 246.46, 399.22 "/>
        <conn lineID="7,8">
            <path d="M 255.41, 392.15 L 267.99, 392.15 L 267.99, 408.85 L 255.41, 408.85 L 255.41, 392.15 "/>
        </conn>
        <conn lineID="9">
            <path d="M 297.90, 392.15 L 310.48, 392.15 L 310.48, 408.92 L 297.90, 408.92 L 297.90, 392.15 "/>
        </conn>
    </part>
    <part code="A22" figID="9" type="conn">
        <path d="M 373.82, 528.13 L 396.98, 528.13 L 396.98, 581.39 L 373.82, 581.39 L 373.82, 528.13 "/>
    </part>
    <part code="A30" figID="10" type="conn">
        <path d="M 569.40, 434.65 L 603.40, 434.65 L 603.40, 479.71 L 569.40, 479.71 L 569.40, 434.65 "/>
    </part>
    <part code="AC1" figID="15" type="w2w">
        <path d="M 290.87, 339.73 L 314.45, 339.73 L 314.45, 359.29 L 290.87, 359.29 L 290.87, 339.73 "/>
    </part>
    <part code="AI3" figID="16" type="w2w">
        <path d="M 659.05, 307.17 L 679.89, 307.17 L 679.89, 326.73 L 659.05, 326.73 L 659.05, 307.17 "/>
    </part>
    <part code="FC" figID="17" type="gp">
        <path d="M 14.87, 679.67 L 36.12, 679.67 L 36.12, 710.00 L 14.87, 710.00 L 14.87, 679.67 "/>
    </part>
    <part code="FB" figID="18" type="gp">
        <path d="M 57.37, 679.67 L 78.61, 679.67 L 78.61, 710.00 L 57.37, 710.00 L 57.37, 679.67 "/>
    </part>
    <part code="AC" figID="19" type="gp">
        <path d="M 125.35, 679.67 L 146.60, 679.67 L 146.60, 710.00 L 125.35, 710.00 L 125.35, 679.67 "/>
    </part>
    <part code="FA" figID="20" type="gp">
        <path d="M 176.35, 679.67 L 197.59, 679.67 L 197.59, 710.00 L 176.35, 710.00 L 176.35, 679.67 "/>
    </part>
    <part code="AA" figID="21" type="gp">
        <path d="M 371.81, 679.67 L 393.06, 679.67 L 393.06, 710.00 L 371.81, 710.00 L 371.81, 679.67 "/>
    </part>
    <part code=" " figID="14" type="annex">
        <path d="M 297.45, 433.21 L 314.45, 433.21 L 314.45, 457.04 L 297.45, 457.04 L 297.45, 433.21 "/>
    </part>
</compact-defs>
