=== randokuruza70/manual/manual/ewd/dtd/ewdsearch.dtd
<!-- <?xml version="1.0" encoding="UTF-8"?> -->
<!-- XML DTD for TOYOTA EWD -->
<!--
	EWD DTD for Second Search XML

	Copyright (c) 2000-2012 SHINTEC HOZUMI Co.,LTD.
	All Rights Reserved. 

	ver 2.0		2011/12/06	new file
	ver 2.1		2012/07/10	add <name> tag.
												add entity value of CountryCode
-->

<!ENTITY % CountryCode "(en | ja | de | fr | es | it | nl | pt | da | sv | fi | no | is | cs | 
                         hu | pl | sl | sq | tr | el | ru | uk | la | he | zh | th | vi)">
<!ENTITY % ItemType "(conn | w2w | jb | jbc | rb  | relay | jc | gp | sp | fl | fuse)">
	<!--
 conn: connector
 w2w: Wire and Wire
 jb: Junction Block
 jbc: Junction Block Connector
 rb: Relay Block
 relay: Relay
 jc: Junction Connector
 gp: Ground Point
 sp: Splice Point
 fl: Fusible Link
 fuse: Fusible Link
	-->
<!ENTITY % Code "NMTOKENS">
<!ELEMENT EWDSearch (ttl)+>
<!ATTLIST EWDSearch
	ver CDATA #IMPLIED
	pubno CDATA #REQUIRED
	xml:lang %CountryCode; #REQUIRED
>
<!ELEMENT ttl (part)*>
<!ATTLIST ttl
	id  %Code; #REQUIRED
>
<!ELEMENT part (text?, name*)>
<!ATTLIST part
	type %ItemType; #REQUIRED
	code CDATA #REQUIRED
	subcode %Code; #IMPLIED
>
<!ELEMENT text (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name
	type CDATA #IMPLIED
>

=== randokuruza70/manual/manual/ewd/search/system/SYS030.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE EWDSearch SYSTEM "../../dtd/ewdsearch.dtd">
<EWDSearch ver="2.1.2.9" pubno="EM25T2E" xml:lang="en">
  <ttl id="SYS030">
    <part type="conn" code="L25,L26">
      <text>IND B ES</text>
      <name>Combination Meter Assembly</name>
      <name type="inner">Meter Micro Computer</name>
      <name type="inner">Sub Tank</name>
    </part>
    <part type="conn" code="I45">
      <name>Diode (Sub Tank Relay)</name>
    </part>
    <part type="conn" code="L8">
      <name>Fuel Control Switch Assembly</name>
    </part>
    <part type="conn" code="W2">
      <name>Fuel Tank Solenoid Main Valve Assembly</name>
    </part>
    <part type="conn" code="W1">
      <name>Fuel Tank Solenoid Return Valve Assembly</name>
    </part>
    <part type="conn" code="A22">
      <name>No. 1 Junction Connector</name>
    </part>
    <part type="conn" code="A23">
      <name>No. 2 Junction Connector</name>
    </part>
    <part type="conn" code="L32,L36">
      <name>No. 24 Junction Connector , No. 28 Junction Connector</name>
    </part>
    <part type="conn" code="I58,I70">
      <name>No. 9 Junction Connector , No. 19 Junction Connector</name>
    </part>
    <part type="conn" code="I58,I72">
      <name>No. 9 Junction Connector , No. 21 Junction Connector</name>
    </part>
    <part type="fuse" code="FUSE5">
      <text>DOME NO.1</text>
    </part>
    <part type="fuse" code="FUSE14">
      <text>IGN</text>
    </part>
    <part type="fuse" code="FUSE16">
      <text>MET</text>
    </part>
  </ttl>
</EWDSearch>

=== randokuruza70/manual/manual/ewd/search/routing/WR029.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE EWDSearch SYSTEM "../../dtd/ewdsearch.dtd">
<EWDSearch ver="2.1.2.9" pubno="EM25T2E" xml:lang="en">
  <ttl id="WR029">
    <part type="conn" code="C114">
      <name>Air Fuel Ratio Sensor (Bank 1 Sensor 1)</name>
    </part>
    <part type="conn" code="C128">
      <name>Differential Pressure Sensor</name>
    </part>
    <part type="conn" code="C120">
      <name>DPF Temperature Sensor (No. 3 Exhaust Gas Temperature Sensor)</name>
    </part>
    <part type="conn" code="C112">
      <name>Injector Assembly No. 8</name>
    </part>
    <part type="conn" code="C123">
      <name>Injector Driver (EDU) (No. 1)</name>
    </part>
    <part type="conn" code="C122">
      <name>Injector Driver (EDU) (No. 1)</name>
    </part>
    <part type="conn" code="C124">
      <name>Injector Driver (EDU) (No. 1)</name>
    </part>
    <part type="conn" code="C121">
      <name>Injector Driver (EDU) (No. 1)</name>
    </part>
    <part type="conn" code="C125">
      <name>Injector Driver (EDU) (No. 2)</name>
    </part>
    <part type="conn" code="C126">
      <name>Injector Driver (EDU) (No. 2)</name>
    </part>
    <part type="conn" code="C127">
      <name>Injector Driver (EDU) (No. 2)</name>
    </part>
    <part type="conn" code="C118">
      <name>No. 1 Exhaust Gas Temperature Sensor</name>
    </part>
    <part type="conn" code="C111">
      <name>No. 1 Vacuum Switching Valve Assembly (for EGR Cooler Bypass Valve)</name>
    </part>
    <part type="conn" code="C119">
      <name>No. 2 Exhaust Gas Temperature Sensor</name>
    </part>
  </ttl>
</EWDSearch>

=== randokuruza70/manual/manual/ewd/search/routing/WR042.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE EWDSearch SYSTEM "../../dtd/ewdsearch.dtd">
<EWDSearch ver="2.1.2.9" pubno="EM25T2E" xml:lang="en">
  <ttl id="WR042">
    <part type="conn" code="T11">
      <name>Back Buzzer Assembly</name>
    </part>
    <part type="conn" code="S25">
      <name>Curtain Shield Airbag Assembly LH</name>
    </part>
    <part type="conn" code="S22">
      <name>Curtain Shield Airbag Assembly RH</name>
    </part>
    <part type="conn" code="V2">
      <name>Differential Lock Shift Actuator</name>
    </part>
    <part type="conn" code="S26">
      <name>Door Side Airbag Sensor LH</name>
    </part>
    <part type="conn" code="S23">
      <name>Door Side Airbag Sensor RH</name>
    </part>
    <part type="conn" code="S6">
      <name>Front Door Courtesy Light Switch Assembly LH</name>
    </part>
    <part type="conn" code="S29">
      <name>Front Door Courtesy Light Switch Assembly LH</name>
    </part>
    <part type="conn" code="S4">
      <name>Front Door Courtesy Light Switch Assembly RH</name>
    </part>
    <part type="conn" code="S20">
      <name>Front Door Courtesy Light Switch Assembly RH</name>
    </part>
    <part type="conn" code="S28">
      <name>Front Seat Inner Belt Assembly LH</name>
    </part>
    <part type="conn" code="S19">
      <name>Front Seat Inner Belt Assembly RH</name>
    </part>
    <part type="conn" code="S12">
      <name>Front Seat Inner Belt Assembly RH</name>
    </part>
    <part type="conn" code="S27">
      <name>Front Seat Outer Belt Assembly LH</name>
    </part>
    <part type="conn" code="S18">
      <name>Front Seat Outer Belt Assembly RH</name>
    </part>
    <part type="conn" code="T3">
      <name>Fuel Pump</name>
    </part>
    <part type="conn" code="X2">
      <name>Fuel Pump (Sub)</name>
    </part>
    <part type="conn" code="T4">
      <name>Fuel Sender Gage Assembly (Rear)</name>
    </part>
    <part type="conn" code="X1">
      <name>Fuel Sender Gage Assembly (Rear)</name>
    </part>
    <part type="conn" code="T19">
      <name>Fuel Sender Gage Assembly (Rear)</name>
    </part>
    <part type="conn" code="W2">
      <name>Fuel Tank Solenoid Main Valve Assembly</name>
    </part>
    <part type="conn" code="W1">
      <name>Fuel Tank Solenoid Return Valve Assembly</name>
    </part>
    <part type="conn" code="T15">
      <name>License Plate Light Assembly LH</name>
    </part>
    <part type="conn" code="T16">
      <name>License Plate Light Assembly LH</name>
    </part>
    <part type="conn" code="T13">
      <name>License Plate Light Assembly RH</name>
    </part>
    <part type="conn" code="T12">
      <name>License Plate Light Assembly RH</name>
    </part>
    <part type="conn" code="S8">
      <name>No. 3 Room Light Assembly</name>
    </part>
    <part type="conn" code="S7">
      <name>No. 3 Room Light Assembly</name>
    </part>
    <part type="conn" code="S3">
      <name>Parking Brake Switch Assembly</name>
    </part>
    <part type="conn" code="S15">
      <name>Parking Brake Switch Assembly</name>
    </part>
    <part type="conn" code="T17">
      <name>Rear Combination Light Assembly LH</name>
    </part>
    <part type="conn" code="T14">
      <name>Rear Combination Light Assembly RH</name>
    </part>
    <part type="conn" code="V1">
      <name>Rear Differential Lock Position Switch</name>
    </part>
    <part type="conn" code="T18">
      <name>Rear Fog Light Socket &amp; Wire</name>
    </part>
    <part type="conn" code="V3">
      <name>Rear Speed Sensor (Skid Control Sensor Wire)</name>
    </part>
    <part type="conn" code="T10">
      <name>Trailer Socket</name>
    </part>
  </ttl>
</EWDSearch>
