=== randokuruza70/manual/manual/ewd/dtd/ewdsearch.dtd
<!-- <?xml version="1.0" encoding="UTF-8"?> -->
<!-- XML DTD for TOYOTA EWD -->
<!--
	EWD DTD for Second Search XML

	Copyright (c) 2000-2012 SHINTEC HOZUMI Co.,LTD.
	All Rights Reserved. 

	ver 2.0		2011/12/06	new file
	ver 2.1		2012/07/10	add <name> tag.
												add entity value of CountryCode
-->

<!ENTITY % CountryCode "(en | ja | de | fr | es | it | nl | pt | da | sv | fi | no | is | cs | 
                         hu | pl | sl | sq | tr | el | ru | uk | la | he | zh | th | vi)">
<!ENTITY % ItemType "(conn | w2w | jb | jbc | rb  | relay | jc | gp | sp | fl | fuse)">
	<!--
 conn: connector
 w2w: Wire and Wire
 jb: Junction Block
 jbc: Junction Block Connector
 rb: Relay Block
 relay: Relay
 jc: Junction Connector
 gp: Ground Point
 sp: Splice Point
 fl: Fusible Link
 fuse: Fusible Link
	-->
<!ENTITY % Code "NMTOKENS">
<!ELEMENT EWDSearch (ttl)+>
<!ATTLIST EWDSearch
	ver CDATA #IMPLIED
	pubno CDATA #REQUIRED
	xml:lang %CountryCode; #REQUIRED
>
<!ELEMENT ttl (part)*>
<!ATTLIST ttl
	id  %Code; #REQUIRED
>
<!ELEMENT part (text?, name*)>
<!ATTLIST part
	type %ItemType; #REQUIRED
	code CDATA #REQUIRED
	subcode %Code; #IMPLIED
>
<!ELEMENT text (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name
	type CDATA #IMPLIED
>

=== randokuruza70/manual/manual/ewd/search/system/SYS081.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE EWDSearch SYSTEM "../../dtd/ewdsearch.dtd">
<EWDSearch ver="2.1.2.9" pubno="EM25T2E" xml:lang="en">
  <ttl id="SYS081">
    <part type="conn" code="A6,I2">
      <name>A/C Pressure Switch (Cooler Refrigerant Liquid Pipe B)</name>
    </part>
    <part type="conn" code="I7">
      <text>E M1 M2 HI</text>
      <name>Blower Resistor</name>
    </part>
    <part type="conn" code="I88">
      <text>MGC LOCK SG GND TE B/V PSW B IGN ACT AC1</text>
      <name>Cooler Stabilizer Amplifier Assembly</name>
    </part>
    <part type="conn" code="C2">
      <text>NE NE-</text>
      <name>Crank Position Sensor</name>
    </part>
    <part type="conn" code="C42">
      <text>NE+ NE- GND</text>
      <name>Crank Position Sensor</name>
    </part>
    <part type="conn" code="C69,C116">
      <name>Diesel Engine Coolant Temperature Sensor</name>
    </part>
    <part type="conn" code="C1">
      <name>E.F.I. Engine Coolant Temperature Sensor</name>
    </part>
    <part type="conn" code="A29,C39,I84">
      <text>ECM ACT AC1 NE+ NE- TACH ETHW THW E2</text>
    </part>
    <part type="conn" code="I87">
      <text>M</text>
      <name>Front Blower Motor (Heater Blower Case)</name>
    </part>
    <part type="conn" code="I15">
      <text>VR1 VR2 E LO M1 M2 HI A/C</text>
      <name>Heater Blower Switch Assembly</name>
    </part>
    <part type="conn" code="C23">
      <text>SSR+ SSR- MG+</text>
      <name>Magnet Clutch Assembly</name>
    </part>
    <part type="conn" code="I16">
      <name>No. 1 Cooler Thermistor</name>
    </part>
    <part type="conn" code="I59,I67">
      <name>No. 10 Junction Connector , No. 16 Junction Connector</name>
    </part>
    <part type="conn" code="I59,I70">
      <name>No. 10 Junction Connector , No. 19 Junction Connector</name>
    </part>
    <part type="conn" code="I67,I107">
      <name>No. 12 Junction Connector , No. 16 Junction Connector</name>
    </part>
    <part type="conn" code="I108,I109">
      <name>No. 13 Junction Connector</name>
    </part>
    <part type="conn" code="I97">
      <name>No. 32 Junction Connector</name>
    </part>
    <part type="conn" code="C38">
      <name>No. 4 Junction Connector</name>
    </part>
    <part type="conn" code="I94">
      <name>No. 7 Junction Connector</name>
    </part>
    <part type="conn" code="I105">
      <name>No. 8 Junction Connector</name>
    </part>
    <part type="conn" code="C102,C103">
      <name>Short Connector</name>
    </part>
    <part type="fuse" code="FUSE4">
      <text>A/C</text>
    </part>
    <part type="fuse" code="FUSE23">
      <text>GAUGE</text>
    </part>
    <part type="fuse" code="FUSE39">
      <text>HTR</text>
    </part>
  </ttl>
</EWDSearch>

=== randokuruza70/manual/manual/ewd/search/system/SYS054.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE EWDSearch SYSTEM "../../dtd/ewdsearch.dtd">
<EWDSearch ver="2.1.2.9" pubno="EM25T2E" xml:lang="en">
  <ttl id="SYS054">
    <part type="conn" code="A5">
      <name>High Pitched Horn Assembly</name>
    </part>
    <part type="conn" code="A4">
      <name>Low Pitched Horn Assembly</name>
    </part>
    <part type="conn" code="z1">
      <name>Spiral Cable Sub-Assembly , Horn Button Wire Sub-Assembly</name>
      <name type="inner">Horn Switch</name>
    </part>
    <part type="conn" code="L27,z1">
      <text>HO</text>
      <name>Spiral Cable Sub-Assembly , Horn Button Wire Sub-Assembly</name>
    </part>
    <part type="fuse" code="FUSE47">
      <text>HORN</text>
    </part>
  </ttl>
</EWDSearch>

=== randokuruza70/manual/manual/ewd/search/routing/WR016.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE EWDSearch SYSTEM "../../dtd/ewdsearch.dtd">
<EWDSearch ver="2.1.2.9" pubno="EM25T2E" xml:lang="en">
  <ttl id="WR016">
    <part type="conn" code="b3">
      <name>Back Door Courtesy Light Switch Assembly</name>
    </part>
    <part type="conn" code="b1">
      <name>Back Door Lock Assembly</name>
    </part>
    <part type="conn" code="Y3">
      <name>Center Stop Light Assembly</name>
    </part>
    <part type="conn" code="V2">
      <name>Differential Lock Shift Actuator</name>
    </part>
    <part type="conn" code="U1">
      <name>Front Door Courtesy Light Switch Assembly LH</name>
    </part>
    <part type="conn" code="X2">
      <name>Fuel Pump (Sub)</name>
    </part>
    <part type="conn" code="X1">
      <name>Fuel Sender Gage Assembly (Rear)</name>
    </part>
    <part type="conn" code="W2">
      <name>Fuel Tank Solenoid Main Valve Assembly</name>
    </part>
    <part type="conn" code="W1">
      <name>Fuel Tank Solenoid Return Valve Assembly</name>
    </part>
    <part type="conn" code="b4">
      <name>License Plate Light Assembly</name>
    </part>
    <part type="conn" code="e1">
      <name>License Plate Light Assembly</name>
    </part>
    <part type="conn" code="Y5">
      <name>No. 1 Room Light Assembly</name>
    </part>
    <part type="conn" code="Y4">
      <name>No. 2 Room Light Assembly</name>
    </part>
    <part type="conn" code="Y2">
      <name>No. 3 Room Light Assembly</name>
    </part>
    <part type="conn" code="Y1">
      <name>No. 3 Room Light Assembly</name>
    </part>
    <part type="conn" code="i1">
      <name>Outer Rear View Mirror Assembly LH</name>
    </part>
    <part type="conn" code="j1">
      <name>Outer Rear View Mirror Assembly RH</name>
    </part>
    <part type="conn" code="V1">
      <name>Rear Differential Lock Position Switch</name>
    </part>
    <part type="conn" code="V3">
      <name>Rear Speed Sensor (Skid Control Sensor Wire)</name>
    </part>
    <part type="conn" code="f1">
      <name>Rear Window Defogger (Back Door Glass LH)</name>
    </part>
    <part type="conn" code="d1">
      <name>Rear Window Defogger (Back Door Glass LH)</name>
    </part>
    <part type="conn" code="c1">
      <name>Rear Window Defogger (Back Door Glass RH)</name>
    </part>
    <part type="conn" code="c2">
      <name>Rear Window Defogger (Back Door Glass RH)</name>
    </part>
    <part type="conn" code="a1">
      <name>Rear Wiper Motor Assembly</name>
    </part>
    <part type="conn" code="U5">
      <name>Tire Pressure Warning ECU and Receiver</name>
    </part>
  </ttl>
</EWDSearch>

=== randokuruza70/manual/manual/ewd/search/routing/WR053.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE EWDSearch SYSTEM "../../dtd/ewdsearch.dtd">
<EWDSearch ver="2.1.2.9" pubno="EM25T2E" xml:lang="en">
  <ttl id="WR053">
    <part type="w2w" code="Pi1">
      <name>Front Door Wire LH and Switch Wire LH</name>
    </part>
    <part type="w2w" code="Oj2">
      <name>Front Door Wire RH and Switch Wire RH</name>
    </part>
    <part type="w2w" code="Oj1">
      <name>Front Door Wire RH and Switch Wire RH</name>
    </part>
    <part type="w2w" code="aS2">
      <name>No. 1 Back Door Wire and Floor Wire</name>
    </part>
    <part type="w2w" code="aS1">
      <name>No. 1 Back Door Wire and Floor Wire</name>
    </part>
    <part type="w2w" code="aS3">
      <name>No. 1 Back Door Wire and Floor Wire</name>
    </part>
    <part type="w2w" code="ca4">
      <name>No. 1 Rear Window Wire and No. 1 Back Door Wire</name>
    </part>
    <part type="w2w" code="ca3">
      <name>No. 1 Rear Window Wire and No. 1 Back Door Wire</name>
    </part>
    <part type="w2w" code="YS4">
      <name>No. 1 Roof Wire and Floor Wire</name>
    </part>
    <part type="w2w" code="bT3">
      <name>No. 2 Back Door Wire and No. 2 Floor Wire</name>
    </part>
    <part type="w2w" code="bT1">
      <name>No. 2 Back Door Wire and No. 2 Floor Wire</name>
    </part>
    <part type="w2w" code="bT2">
      <name>No. 2 Back Door Wire and No. 2 Floor Wire</name>
    </part>
    <part type="w2w" code="bf1">
      <name>No. 2 Back Door Wire and No. 4 Back Door Wire</name>
    </part>
    <part type="w2w" code="TS1">
      <name>No. 2 Floor Wire and Floor Wire</name>
    </part>
    <part type="w2w" code="TS2">
      <name>No. 2 Floor Wire and Floor Wire</name>
    </part>
    <part type="w2w" code="TS3">
      <name>No. 2 Floor Wire and Floor Wire</name>
    </part>
    <part type="w2w" code="TS4">
      <name>No. 2 Floor Wire and Floor Wire</name>
    </part>
    <part type="w2w" code="TV2">
      <name>No. 2 Floor Wire and Frame Wire</name>
    </part>
    <part type="w2w" code="TX1">
      <name>No. 2 Floor Wire and No. 3 Frame Wire</name>
    </part>
    <part type="w2w" code="WC2">
      <name>No. 2 Frame Wire and Engine Wire</name>
    </part>
    <part type="w2w" code="db1">
      <name>No. 2 Rear Window Wire and No. 2 Back Door Wire</name>
    </part>
    <part type="w2w" code="eb2">
      <name>No. 3 Back Door Wire and No. 2 Back Door Wire</name>
    </part>
    <part type="w2w" code="XT1">
      <name>No. 3 Frame Wire and No. 2 Floor Wire</name>
    </part>
  </ttl>
</EWDSearch>

=== randokuruza70/manual/manual/ewd/search/system/SYS048.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE EWDSearch SYSTEM "../../dtd/ewdsearch.dtd">
<EWDSearch ver="2.1.2.9" pubno="EM25T2E" xml:lang="en">
  <ttl id="SYS048">
    <part type="conn" code="I46">
      <name>Diode (Wiper Relay)</name>
    </part>
    <part type="conn" code="A22">
      <name>No. 1 Junction Connector</name>
    </part>
    <part type="conn" code="I59">
      <name>No. 10 Junction Connector</name>
    </part>
    <part type="conn" code="I63,I65">
      <name>No. 13 Junction Connector</name>
    </part>
    <part type="conn" code="A23">
      <name>No. 2 Junction Connector</name>
    </part>
    <part type="conn" code="L33">
      <name>No. 25 Junction Connector</name>
    </part>
    <part type="conn" code="L39">
      <name>No. 31 Junction Connector</name>
    </part>
    <part type="conn" code="I57">
      <name>No. 8 Junction Connector</name>
    </part>
    <part type="conn" code="I35">
      <text>M</text>
      <name>Windshield Washer Motor and Pump Assembly</name>
    </part>
    <part type="conn" code="A12">
      <text>B +S E M +2 +1</text>
      <name>Windshield Wiper Motor Assembly</name>
    </part>
    <part type="conn" code="L22,L23">
      <text>+B +2 +1 MIST OFF HI EW WF LO</text>
      <name>Windshield Wiper Switch Assembly</name>
      <name type="inner">Off</name>
      <name type="inner">Front Washer Switch</name>
      <name type="inner">Front Wiper Switch</name>
      <name type="inner">On</name>
    </part>
    <part type="conn" code="I26">
      <name>Wiper Lock Switch (Limit Switch Assembly)</name>
    </part>
    <part type="fuse" code="FUSE20">
      <text>ECU IG</text>
    </part>
    <part type="fuse" code="FUSE29">
      <text>WIP</text>
    </part>
  </ttl>
</EWDSearch>

=== randokuruza70/manual/manual/ewd/search/routing/WR025.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE EWDSearch SYSTEM "../../dtd/ewdsearch.dtd">
<EWDSearch ver="2.1.2.9" pubno="EM25T2E" xml:lang="en">
  <ttl id="WR025">
    <part type="conn" code="C95">
      <name>Back-Up Light Switch Assembly</name>
    </part>
    <part type="conn" code="C98">
      <name>Center Differential Lock Indicator Switch (No. 1 Transfer Indicator Switch)</name>
    </part>
    <part type="conn" code="C91">
      <name>Electric Vacuum Regulating Valve Assembly (EGR)</name>
    </part>
    <part type="conn" code="C86">
      <name>Engine Coolant Temperature Sensor</name>
    </part>
    <part type="conn" code="C88">
      <name>Engine Oil Pressure Switch Assembly</name>
    </part>
    <part type="conn" code="C97">
      <name>Fuel Sender Gage Assembly (Front)</name>
    </part>
    <part type="conn" code="C90">
      <name>Glow Plug Assembly</name>
    </part>
    <part type="conn" code="C84">
      <name>Injection or Supply Pump Assembly</name>
    </part>
    <part type="conn" code="C83">
      <name>Injection or Supply Pump Assembly</name>
    </part>
    <part type="conn" code="C87">
      <name>Oil Pressure Sender Gage Assembly</name>
    </part>
    <part type="conn" code="C96">
      <name>Speedometer Sensor</name>
    </part>
    <part type="conn" code="C89">
      <name>Starter Assembly</name>
    </part>
    <part type="conn" code="C99">
      <name>Transfer L4 Position Switch (No. 1 Transfer Indicator Switch)</name>
    </part>
    <part type="conn" code="C93">
      <name>Vacuum Sensor</name>
    </part>
    <part type="conn" code="C94">
      <name>Vacuum Switching Valve Assembly (BACS)</name>
    </part>
    <part type="conn" code="C92">
      <name>Vacuum Switching Valve Assembly (EGR Cut)</name>
    </part>
    <part type="conn" code="C85">
      <name>Water Temperature Sender Gage Assembly</name>
    </part>
  </ttl>
</EWDSearch>

=== randokuruza70/manual/manual/ewd/search/routing/WR010.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE EWDSearch SYSTEM "../../dtd/ewdsearch.dtd">
<EWDSearch ver="2.1.2.9" pubno="EM25T2E" xml:lang="en">
  <ttl id="WR010">
    <part type="conn" code="I2">
      <name>A/C Pressure Switch (Cooler Refrigerant Liquid Pipe B)</name>
    </part>
    <part type="conn" code="D8">
      <name>Battery (Main)</name>
    </part>
    <part type="conn" code="k2">
      <name>Battery (Main)</name>
    </part>
    <part type="conn" code="D9">
      <name>Battery (Main)</name>
    </part>
    <part type="conn" code="I84">
      <text>ECM</text>
    </part>
    <part type="conn" code="J2">
      <name>Fog Light Assembly LH</name>
    </part>
    <part type="conn" code="J1">
      <name>Fog Light Assembly RH</name>
    </part>
    <part type="conn" code="I52">
      <name>Front Airbag Sensor RH</name>
    </part>
    <part type="conn" code="r3">
      <name>Fuel Temperature Sensor</name>
    </part>
    <part type="conn" code="I76">
      <name>Fuse Block Assembly</name>
    </part>
    <part type="conn" code="I36">
      <name>Headlight Assembly RH</name>
    </part>
    <part type="conn" code="I91">
      <name>Headlight Assembly RH</name>
    </part>
    <part type="conn" code="I38">
      <name>Headlight Assembly RH</name>
    </part>
    <part type="conn" code="I44">
      <name>Headlight Assembly RH</name>
    </part>
    <part type="conn" code="m3">
      <name>No. 1 Magnet Switch Assembly</name>
    </part>
    <part type="conn" code="k1">
      <name>No. 1 Magnet Switch Assembly</name>
    </part>
    <part type="conn" code="m4">
      <name>No. 1 Magnet Switch Assembly</name>
    </part>
    <part type="conn" code="I25">
      <name>Side Turn Signal Light Assembly RH</name>
    </part>
    <part type="conn" code="D7">
      <name>Starter Assembly</name>
    </part>
    <part type="conn" code="D6">
      <name>Starter Assembly</name>
    </part>
    <part type="conn" code="r2">
      <name>Suction Control Valve</name>
    </part>
    <part type="conn" code="I48">
      <name>Thermistor Assembly</name>
    </part>
    <part type="conn" code="I32">
      <name>Vacuum Warning Switch Assembly</name>
    </part>
    <part type="conn" code="s1">
      <name>Winch Assembly</name>
    </part>
    <part type="conn" code="s2">
      <name>Winch Motor with Magnet Switch Assembly</name>
    </part>
    <part type="conn" code="t1">
      <name>Winch Motor with Magnet Switch Assembly</name>
    </part>
    <part type="conn" code="m2">
      <name>Winch Motor with Magnet Switch Assembly</name>
    </part>
    <part type="conn" code="m1">
      <name>Winch Motor with Magnet Switch Assembly</name>
    </part>
    <part type="conn" code="I86">
      <name>Windshield Wiper Motor Assembly</name>
    </part>
  </ttl>
</EWDSearch>

=== randokuruza70/manual/manual/ewd/search/routing/WR007.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE EWDSearch SYSTEM "../../dtd/ewdsearch.dtd">
<EWDSearch ver="2.1.2.9" pubno="EM25T2E" xml:lang="en">
  <ttl id="WR007">
    <part type="conn" code="A10">
      <name>Antenna with Holder Assembly</name>
    </part>
    <part type="conn" code="A36">
      <name>Battery (Main)</name>
    </part>
    <part type="conn" code="A35">
      <name>Battery (Main)</name>
    </part>
    <part type="conn" code="A42">
      <name>Brake Actuator Assembly</name>
    </part>
    <part type="conn" code="A15">
      <name>Brake Fluid Level Warning Switch (Brake Master Cylinder Reservoir Sub-Assembly)</name>
    </part>
    <part type="conn" code="A25">
      <name>Brake Vacuum Check Valve Assembly</name>
    </part>
    <part type="conn" code="A27">
      <name>Brake Vacuum Check Valve Assembly</name>
    </part>
    <part type="conn" code="A28">
      <name>Brake Vacuum Check Valve Assembly</name>
    </part>
    <part type="conn" code="A26">
      <name>Brake Vacuum Check Valve Assembly</name>
    </part>
    <part type="conn" code="A13">
      <name>Front Airbag Sensor LH</name>
    </part>
    <part type="conn" code="B2">
      <name>Front Differential Lock Position Switch</name>
    </part>
    <part type="conn" code="A21">
      <name>Front Speed Sensor LH (Skid Control Sensor Wire LH)</name>
    </part>
    <part type="conn" code="B3">
      <name>Front Speed Sensor RH (Skid Control Sensor Wire RH)</name>
    </part>
    <part type="conn" code="A8">
      <name>Fuel Filter Vacuum Sensor</name>
    </part>
    <part type="conn" code="A9">
      <name>Fuel Sediment Switch</name>
    </part>
    <part type="conn" code="A38">
      <name>Headlight Assembly LH</name>
    </part>
    <part type="conn" code="A1">
      <name>Headlight Assembly LH</name>
    </part>
    <part type="conn" code="A3">
      <name>Headlight Assembly LH</name>
    </part>
    <part type="conn" code="A14">
      <name>Headlight Assembly LH</name>
    </part>
    <part type="conn" code="A5">
      <name>High Pitched Horn Assembly</name>
    </part>
    <part type="conn" code="A4">
      <name>Low Pitched Horn Assembly</name>
    </part>
    <part type="conn" code="A22">
      <name>No. 1 Junction Connector</name>
    </part>
    <part type="conn" code="B1">
      <name>No. 2 Differential Lock Shift Actuator</name>
    </part>
    <part type="conn" code="A23">
      <name>No. 2 Junction Connector</name>
    </part>
    <part type="conn" code="A43">
      <name>No. 34 Junction Connector</name>
    </part>
    <part type="conn" code="A11">
      <name>Side Turn Signal Light Assembly LH</name>
    </part>
    <part type="conn" code="A2">
      <name>Windshield Washer Motor and Pump Assembly</name>
    </part>
  </ttl>
</EWDSearch>
