=== randokuruza70/manual/manual/ewd/dtd/ewdtree.dtd
<!-- <?xml version="1.0" encoding="UTF-8"?> -->
<!-- XML DTD for TOYOTA EWD -->
<!--
	EWD DTD for EWD Tree XML

	Copyright (c) 2000-2012 SHINTEC HOZUMI Co.,LTD.
	All Rights Reserved. 

	ver 2.0		2012/03/21
	ver 2.1		2012/07/10	add entity value of CountryCode
-->

<!ENTITY % CountryCode "(en | ja | de | fr | es | it | nl | pt | da | sv | fi | no | is | cs | 
                         hu | pl | sl | sq | tr | el | ru | uk | la | he | zh | th | vi)">
<!ENTITY % Book "( name, note*, book* )">
<!ELEMENT EwdTree (book* | root* | text* | note*)>
<!ATTLIST EwdTree
	ver CDATA #IMPLIED
	pubno CDATA #REQUIRED
	xml:lang %CountryCode; #REQUIRED
>
<!ELEMENT root (name)>
<!ATTLIST root
	id CDATA #REQUIRED
>
<!ELEMENT book (%Book;)>
<!ATTLIST book
	id CDATA #REQUIRED
	file CDATA #IMPLIED
>
<!ELEMENT text (name)>
<!ATTLIST text
	ewd CDATA #IMPLIED
	code CDATA #IMPLIED
	type CDATA #IMPLIED
	figID CDATA #IMPLIED
>
<!ELEMENT note (%Book;, text*)>
<!ATTLIST note
	id CDATA #IMPLIED
	icon CDATA #IMPLIED
	file CDATA #IMPLIED
	ewd CDATA #IMPLIED
	code CDATA #IMPLIED
	type CDATA #IMPLIED
>
<!ELEMENT name (#PCDATA)>

=== randokuruza70/manual/manual/ewd/contents/tree/201608/models/GRJ71L-KJMRK/tree-WIRE030.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE EwdTree SYSTEM "../../../../../dtd/ewdtree.dtd">
<EwdTree ver="2.1.2.9" pubno="EM25T2E" xml:lang="en">
  <note ewd="WIRE030" code="O6" type="conn">
    <name>Door Control Relay Assembly</name>
  </note>
  <note ewd="WIRE030" code="O15" type="conn">
    <name>Door Control Relay Assembly</name>
  </note>
  <note ewd="WIRE030" code="O14" type="conn">
    <name>Door Control Switch</name>
  </note>
  <note ewd="WIRE030" code="O3" type="conn">
    <name>Front Door Lock Actuator Assembly RH</name>
  </note>
  <note ewd="WIRE030" code="O4" type="conn">
    <name>Front Door Lock Actuator Assembly RH</name>
  </note>
  <note ewd="WIRE030" code="O5" type="conn">
    <name>Front Door Lock Actuator Assembly RH</name>
  </note>
  <note ewd="WIRE030" code="O7" type="conn">
    <name>Front Door Lock Actuator Assembly RH</name>
  </note>
  <note ewd="WIRE030" code="O2" type="conn">
    <name>Front Power Window Regulator Motor Assembly RH</name>
  </note>
  <note ewd="WIRE030" code="O10" type="conn">
    <name>Front Power Window Regulator Switch Assembly RH</name>
  </note>
  <note ewd="WIRE030" code="O11" type="conn">
    <name>Front Power Window Regulator Switch Assembly RH</name>
  </note>
  <note ewd="WIRE030" code="O8" type="conn">
    <name>Power Window Regulator Master Switch Assembly</name>
  </note>
  <note ewd="WIRE030" code="O9" type="conn">
    <name>Power Window Regulator Master Switch Assembly</name>
  </note>
  <note ewd="WIRE030" code="Oj1" type="w2w">
    <name>Front Door Wire RH and Switch Wire RH</name>
  </note>
  <note ewd="WIRE030" code="Oj2" type="w2w">
    <name>Front Door Wire RH and Switch Wire RH</name>
  </note>
</EwdTree>

=== randokuruza70/manual/manual/ewd/contents/tree/201608/models/VDJ76R-RKMNYQ/tree-routing.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE EwdTree SYSTEM "../../../../../dtd/ewdtree.dtd">
<EwdTree ver="2.1.2.9" pubno="EM25T2E" xml:lang="en">
  <book id="L-EG">
    <name>Engine Compartment</name>
    <note id="WR027" icon="P" file="T">
      <name>Position of Parts (RHD 1VD-FTV)</name>
    </note>
    <note id="WR063" icon="P" file="T">
      <name>Wire and Wire (RHD 1VD-FTV)</name>
    </note>
    <note id="WR064" icon="P" file="T">
      <name>Ground Points (RHD 1VD-FTV)</name>
    </note>
    <book id="RELAY_RL001" file="T">
      <name>Relay Location</name>
    </book>
  </book>
  <book id="L-INPA">
    <name>Instrument Panel</name>
    <note id="WR031" icon="P" file="T">
      <name>Position of Parts (RHD)</name>
    </note>
    <note id="WR065" icon="P" file="T">
      <name>Wire and Wire (RHD)</name>
    </note>
    <note id="WR066" icon="P" file="T">
      <name>Ground Points (RHD)</name>
    </note>
    <book id="RELAY_RL002" file="T">
      <name>Relay Location(LHD)</name>
    </book>
    <book id="RELAY_RL003" file="T">
      <name>Relay Location(RHD)</name>
    </book>
  </book>
  <book id="L-BODY">
    <name>Body</name>
    <note id="WR035" icon="P" file="T">
      <name>Position of Parts (RHD 4-Door Except Pick-Up)</name>
    </note>
    <note id="WR037" icon="P" file="T">
      <name>Position of Parts (RHD 2-Door Except Pick-Up)</name>
    </note>
    <note id="WR039" icon="P" file="T">
      <name>Position of Parts (RHD 4-Door Pick-Up)</name>
    </note>
    <note id="WR041" icon="P" file="T">
      <name>Position of Parts (RHD 2-Door Pick-Up)</name>
    </note>
    <note id="WR067" icon="P" file="T">
      <name>Wire and Wire (RHD 4-Door Except Pick-Up)</name>
    </note>
    <note id="WR068" icon="P" file="T">
      <name>Ground Points (RHD 4-Door Except Pick-Up)</name>
    </note>
    <note id="WR069" icon="P" file="T">
      <name>Wire and Wire (RHD 2-Door Except Pick-Up)</name>
    </note>
    <note id="WR070" icon="P" file="T">
      <name>Ground Points (RHD 2-Door Except Pick-Up)</name>
    </note>
    <note id="WR071" icon="P" file="T">
      <name>Wire and Wire (RHD 4-Door Pick-Up)</name>
    </note>
    <note id="WR072" icon="P" file="T">
      <name>Ground Points (RHD 4-Door Pick-Up)</name>
    </note>
    <note id="WR073" icon="P" file="T">
      <name>Wire and Wire (RHD 2-Door Pick-Up)</name>
    </note>
    <note id="WR074" icon="P" file="T">
      <name>Ground Points (RHD 2-Door Pick-Up)</name>
    </note>
    <book id="RELAY_RL004" file="T">
      <name>Relay Location(4-Door Except Pick-Up)</name>
    </book>
    <book id="RELAY_RL005" file="T">
      <name>Relay Location(2-Door Except Pick-Up)</name>
    </book>
    <book id="RELAY_RL006" file="T">
      <name>Relay Location(4-Door Pick-Up)</name>
    </book>
    <book id="RELAY_RL007" file="T">
      <name>Relay Location(2-Door Pick-Up)</name>
    </book>
  </book>
  <book id="L-ANTE">
    <name>Antenna</name>
    <note id="WR075" file="T">
      <name>Antenna (4-Door Except Pick-Up)</name>
    </note>
    <note id="WR076" file="T">
      <name>Antenna (2-Door Except Pick-Up)</name>
    </note>
    <note id="WR077" file="T">
      <name>Antenna (4-Door Pick-Up)</name>
    </note>
    <note id="WR078" file="T">
      <name>Antenna (2-Door Pick-Up)</name>
    </note>
  </book>
</EwdTree>

=== randokuruza70/manual/manual/ewd/contents/tree/201701/tree-routing.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE EwdTree SYSTEM "../../../dtd/ewdtree.dtd">
<EwdTree ver="2.1.2.9" pubno="EM25T2E" xml:lang="en">
  <book id="L-EG">
    <name>Engine Compartment</name>
    <note id="WR001" icon="P" file="T">
      <name>Position of Parts (LHD 1GR-FE)</name>
    </note>
    <note id="WR004" icon="P" file="T">
      <name>Position of Parts (LHD 1HZ)</name>
    </note>
    <note id="WR007" icon="P" file="T">
      <name>Position of Parts (LHD 1VD-FTV)</name>
    </note>
    <note id="WR021" icon="P" file="T">
      <name>Position of Parts (RHD 1GR-FE)</name>
    </note>
    <note id="WR024" icon="P" file="T">
      <name>Position of Parts (RHD 1HZ)</name>
    </note>
    <note id="WR027" icon="P" file="T">
      <name>Position of Parts (RHD 1VD-FTV)</name>
    </note>
    <note id="WR043" icon="P" file="T">
      <name>Wire and Wire (LHD 1GR-FE)</name>
    </note>
    <note id="WR044" icon="P" file="T">
      <name>Ground Points (LHD 1GR-FE)</name>
    </note>
    <note id="WR045" icon="P" file="T">
      <name>Wire and Wire (LHD 1HZ)</name>
    </note>
    <note id="WR046" icon="P" file="T">
      <name>Ground Points (LHD 1HZ)</name>
    </note>
    <note id="WR047" icon="P" file="T">
      <name>Wire and Wire (LHD 1VD-FTV)</name>
    </note>
    <note id="WR048" icon="P" file="T">
      <name>Ground Points (LHD 1VD-FTV)</name>
    </note>
    <note id="WR059" icon="P" file="T">
      <name>Wire and Wire (RHD 1GR-FE)</name>
    </note>
    <note id="WR060" icon="P" file="T">
      <name>Ground Points (RHD 1GR-FE)</name>
    </note>
    <note id="WR061" icon="P" file="T">
      <name>Wire and Wire (RHD 1HZ)</name>
    </note>
    <note id="WR062" icon="P" file="T">
      <name>Ground Points (RHD 1HZ)</name>
    </note>
    <note id="WR063" icon="P" file="T">
      <name>Wire and Wire (RHD 1VD-FTV)</name>
    </note>
    <note id="WR064" icon="P" file="T">
      <name>Ground Points (RHD 1VD-FTV)</name>
    </note>
    <book id="RELAY_RL001" file="T">
      <name>Relay Location</name>
    </book>
  </book>
  <book id="L-INPA">
    <name>Instrument Panel</name>
    <note id="WR011" icon="P" file="T">
      <name>Position of Parts (LHD)</name>
    </note>
    <note id="WR031" icon="P" file="T">
      <name>Position of Parts (RHD)</name>
    </note>
    <note id="WR049" icon="P" file="T">
      <name>Wire and Wire (LHD)</name>
    </note>
    <note id="WR050" icon="P" file="T">
      <name>Ground Points (LHD)</name>
    </note>
    <note id="WR065" icon="P" file="T">
      <name>Wire and Wire (RHD)</name>
    </note>
    <note id="WR066" icon="P" file="T">
      <name>Ground Points (RHD)</name>
    </note>
    <book id="RELAY_RL002" file="T">
      <name>Relay Location(LHD)</name>
    </book>
    <book id="RELAY_RL003" file="T">
      <name>Relay Location(RHD)</name>
    </book>
  </book>
  <book id="L-BODY">
    <name>Body</name>
    <note id="WR013" icon="P" file="T">
      <name>Position of Parts (LHD 4-Door Except Pick-Up)</name>
    </note>
    <note id="WR015" icon="P" file="T">
      <name>Position of Parts (LHD 2-Door Except Pick-Up)</name>
    </note>
    <note id="WR017" icon="P" file="T">
      <name>Position of Parts (LHD 4-Door Pick-Up)</name>
    </note>
    <note id="WR019" icon="P" file="T">
      <name>Position of Parts (LHD 2-Door Pick-Up)</name>
    </note>
    <note id="WR035" icon="P" file="T">
      <name>Position of Parts (RHD 4-Door Except Pick-Up)</name>
    </note>
    <note id="WR037" icon="P" file="T">
      <name>Position of Parts (RHD 2-Door Except Pick-Up)</name>
    </note>
    <note id="WR039" icon="P" file="T">
      <name>Position of Parts (RHD 4-Door Pick-Up)</name>
    </note>
    <note id="WR041" icon="P" file="T">
      <name>Position of Parts (RHD 2-Door Pick-Up)</name>
    </note>
    <note id="WR051" icon="P" file="T">
      <name>Wire and Wire (LHD 4-Door Except Pick-Up)</name>
    </note>
    <note id="WR052" icon="P" file="T">
      <name>Ground Points (LHD 4-Door Except Pick-Up)</name>
    </note>
    <note id="WR053" icon="P" file="T">
      <name>Wire and Wire (LHD 2-Door Except Pick-Up)</name>
    </note>
    <note id="WR054" icon="P" file="T">
      <name>Ground Points (LHD 2-Door Except Pick-Up)</name>
    </note>
    <note id="WR055" icon="P" file="T">
      <name>Wire and Wire (LHD 4-Door Pick-Up)</name>
    </note>
    <note id="WR056" icon="P" file="T">
      <name>Ground Points (LHD 4-Door Pick-Up)</name>
    </note>
    <note id="WR057" icon="P" file="T">
      <name>Wire and Wire (LHD 2-Door Pick-Up)</name>
    </note>
    <note id="WR058" icon="P" file="T">
      <name>Ground Points (LHD 2-Door Pick-Up)</name>
    </note>
    <note id="WR067" icon="P" file="T">
      <name>Wire and Wire (RHD 4-Door Except Pick-Up)</name>
    </note>
    <note id="WR068" icon="P" file="T">
      <name>Ground Points (RHD 4-Door Except Pick-Up)</name>
    </note>
    <note id="WR069" icon="P" file="T">
      <name>Wire and Wire (RHD 2-Door Except Pick-Up)</name>
    </note>
    <note id="WR070" icon="P" file="T">
      <name>Ground Points (RHD 2-Door Except Pick-Up)</name>
    </note>
    <note id="WR071" icon="P" file="T">
      <name>Wire and Wire (RHD 4-Door Pick-Up)</name>
    </note>
    <note id="WR072" icon="P" file="T">
      <name>Ground Points (RHD 4-Door Pick-Up)</name>
    </note>
    <note id="WR073" icon="P" file="T">
      <name>Wire and Wire (RHD 2-Door Pick-Up)</name>
    </note>
    <note id="WR074" icon="P" file="T">
      <name>Ground Points (RHD 2-Door Pick-Up)</name>
    </note>
    <book id="RELAY_RL004" file="T">
      <name>Relay Location(4-Door Except Pick-Up)</name>
    </book>
    <book id="RELAY_RL005" file="T">
      <name>Relay Location(2-Door Except Pick-Up)</name>
    </book>
    <book id="RELAY_RL006" file="T">
      <name>Relay Location(4-Door Pick-Up)</name>
    </book>
    <book id="RELAY_RL007" file="T">
      <name>Relay Location(2-Door Pick-Up)</name>
    </book>
  </book>
  <book id="L-ANTE">
    <name>Antenna</name>
    <note id="WR075" file="T">
      <name>Antenna (4-Door Except Pick-Up)</name>
    </note>
    <note id="WR076" file="T">
      <name>Antenna (2-Door Except Pick-Up)</name>
    </note>
    <note id="WR077" file="T">
      <name>Antenna (4-Door Pick-Up)</name>
    </note>
    <note id="WR078" file="T">
      <name>Antenna (2-Door Pick-Up)</name>
    </note>
  </book>
</EwdTree>

=== randokuruza70/manual/manual/ewd/contents/tree/201608/tree-WR017.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE EwdTree SYSTEM "../../../dtd/ewdtree.dtd">
<EwdTree ver="2.1.2.9" pubno="EM25T2E" xml:lang="en">
  <text ewd="WR017" code="P7" type="conn">
    <name>Door Control Relay Assembly</name>
  </text>
  <text ewd="WR017" code="S4" type="conn">
    <name>Front Door Courtesy Light Switch Assembly RH</name>
  </text>
  <text ewd="WR017" code="P5" type="conn">
    <name>Front Door Lock Actuator Assembly LH</name>
  </text>
  <text ewd="WR017" code="P8" type="conn">
    <name>Front Door Lock Actuator Assembly LH</name>
  </text>
  <text ewd="WR017" code="O3" type="conn">
    <name>Front Door Lock Actuator Assembly RH</name>
  </text>
  <text ewd="WR017" code="P2" type="conn">
    <name>Front Power Window Regulator Motor Assembly LH</name>
  </text>
  <text ewd="WR017" code="O2" type="conn">
    <name>Front Power Window Regulator Motor Assembly RH</name>
  </text>
  <text ewd="WR017" code="O10" type="conn">
    <name>Front Power Window Regulator Switch Assembly RH</name>
  </text>
  <text ewd="WR017" code="S2" type="conn">
    <name>Front Seat Inner Belt Assembly LH</name>
  </text>
  <text ewd="WR017" code="S3" type="conn">
    <name>Parking Brake Switch Assembly</name>
  </text>
  <text ewd="WR017" code="S15" type="conn">
    <name>Parking Brake Switch Assembly</name>
  </text>
  <text ewd="WR017" code="P9" type="conn">
    <name>Power Window Regulator Master Switch Assembly</name>
  </text>
  <text ewd="WR017" code="S13" type="conn">
    <name>Rear Door Courtesy Light Switch Assembly RH</name>
  </text>
  <text ewd="WR017" code="S16" type="conn">
    <name>Rear Door Courtesy Light Switch Assembly RH</name>
  </text>
  <text ewd="WR017" code="Q2" type="conn">
    <name>Rear Door Lock Actuator Assembly LH</name>
  </text>
  <text ewd="WR017" code="R2" type="conn">
    <name>Rear Door Lock Actuator Assembly RH</name>
  </text>
  <text ewd="WR017" code="S5" type="conn">
    <name>Rear Heater Blower Resistor</name>
  </text>
  <text ewd="WR017" code="S10" type="conn">
    <name>Rear Heater Blower Switch</name>
  </text>
  <text ewd="WR017" code="Q3" type="conn">
    <name>Rear Power Window Regulator Motor Assembly LH</name>
  </text>
  <text ewd="WR017" code="R3" type="conn">
    <name>Rear Power Window Regulator Motor Assembly RH</name>
  </text>
  <text ewd="WR017" code="Q1" type="conn">
    <name>Rear Power Window Regulator Switch Assembly LH</name>
  </text>
  <text ewd="WR017" code="R1" type="conn">
    <name>Rear Power Window Regulator Switch Assembly RH</name>
  </text>
  <text ewd="WR018" code="T11" type="conn">
    <name>Back Buzzer Assembly</name>
  </text>
  <text ewd="WR018" code="V2" type="conn">
    <name>Differential Lock Shift Actuator</name>
  </text>
  <text ewd="WR018" code="U1" type="conn">
    <name>Front Door Courtesy Light Switch Assembly LH</name>
  </text>
  <text ewd="WR018" code="T8" type="conn">
    <name>Fuel Pump (Sub)</name>
  </text>
  <text ewd="WR018" code="T9" type="conn">
    <name>Fuel Sender Gage Assembly (Rear)</name>
  </text>
  <text ewd="WR018" code="T19" type="conn">
    <name>Fuel Sender Gage Assembly (Rear)</name>
  </text>
  <text ewd="WR018" code="T15" type="conn">
    <name>License Plate Light Assembly LH</name>
  </text>
  <text ewd="WR018" code="T16" type="conn">
    <name>License Plate Light Assembly LH</name>
  </text>
  <text ewd="WR018" code="T12" type="conn">
    <name>License Plate Light Assembly RH</name>
  </text>
  <text ewd="WR018" code="T13" type="conn">
    <name>License Plate Light Assembly RH</name>
  </text>
  <text ewd="WR018" code="Y5" type="conn">
    <name>No. 1 Room Light Assembly</name>
  </text>
  <text ewd="WR018" code="i1" type="conn">
    <name>Outer Rear View Mirror Assembly LH</name>
  </text>
  <text ewd="WR018" code="j1" type="conn">
    <name>Outer Rear View Mirror Assembly RH</name>
  </text>
  <text ewd="WR018" code="T17" type="conn">
    <name>Rear Combination Light Assembly LH</name>
  </text>
  <text ewd="WR018" code="T14" type="conn">
    <name>Rear Combination Light Assembly RH</name>
  </text>
  <text ewd="WR018" code="V1" type="conn">
    <name>Rear Differential Lock Position Switch</name>
  </text>
  <text ewd="WR018" code="U2" type="conn">
    <name>Rear Door Courtesy Light Switch Assembly LH</name>
  </text>
  <text ewd="WR018" code="T18" type="conn">
    <name>Rear Fog Light Socket &amp; Wire</name>
  </text>
  <text ewd="WR018" code="V3" type="conn">
    <name>Rear Speed Sensor (Skid Control Sensor Wire)</name>
  </text>
  <text ewd="WR018" code="Y7" type="conn">
    <name>Tire Pressure Warning ECU and Receiver</name>
  </text>
  <text ewd="WR018" code="T10" type="conn">
    <name>Trailer Socket</name>
  </text>
</EwdTree>

=== randokuruza70/manual/manual/ewd/contents/tree/201701/tree-SYS061.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE EwdTree SYSTEM "../../../dtd/ewdtree.dtd">
<EwdTree ver="2.1.2.9" pubno="EM25T2E" xml:lang="en">
  <text ewd="SYS061" code="L25" type="conn" figID="1">
    <name>Combination Meter Assembly</name>
  </text>
  <text ewd="SYS061" code="L24" type="conn" figID="9">
    <name>Headlight Dimmer Switch Assembly</name>
  </text>
  <text ewd="SYS061" code="L53" type="conn" figID="8">
    <name>No. 31 Junction Connector</name>
  </text>
  <text ewd="SYS061" code="T5" type="conn" figID="5">
    <name>Rear Combination Light Assembly LH</name>
  </text>
  <text ewd="SYS061" code="T18" type="conn" figID="10">
    <name>Rear Fog Light Socket &amp; Wire</name>
  </text>
  <text ewd="SYS061" code="FUSE18" type="fuse" figID="45">
    <name>10A TAIL</name>
  </text>
  <text ewd="SYS061" code="FUSE25" type="fuse" figID="46">
    <name>15A RR FOG</name>
  </text>
  <text ewd="SYS061" code="FUSE57" type="fuse" figID="44">
    <name>50A MAIN1</name>
  </text>
  <text ewd="SYS061" code="CA" type="gp" figID="33">
    <name />
  </text>
  <text ewd="SYS061" code="CC" type="gp" figID="32">
    <name />
  </text>
  <text ewd="SYS061" code="LA" type="gp" figID="28">
    <name />
  </text>
  <text ewd="SYS061" code="LB" type="gp" figID="27">
    <name />
  </text>
  <text ewd="SYS061" code="TA" type="gp" figID="31">
    <name />
  </text>
  <text ewd="SYS061" code="TB" type="gp" figID="29">
    <name />
  </text>
  <text ewd="SYS061" code="TC" type="gp" figID="30">
    <name />
  </text>
  <text ewd="SYS061" code="2" type="rb" figID="4,6">
    <name />
  </text>
  <text ewd="SYS061" code="FUSE18" type="rb" figID="3">
    <name>10A TAIL</name>
  </text>
  <text ewd="SYS061" code="FUSE25" type="rb" figID="7">
    <name>15A RR FOG</name>
  </text>
  <text ewd="SYS061" code="FUSE57" type="rb" figID="2">
    <name>50A MAIN1</name>
  </text>
  <text ewd="SYS061" code="SP19" type="sp" figID="41,43">
    <name />
  </text>
  <text ewd="SYS061" code="SP45" type="sp" figID="36">
    <name />
  </text>
  <text ewd="SYS061" code="SP58" type="sp" figID="40">
    <name />
  </text>
  <text ewd="SYS061" code="SP60" type="sp" figID="42">
    <name />
  </text>
  <text ewd="SYS061" code="SP71" type="sp" figID="34">
    <name />
  </text>
  <text ewd="SYS061" code="SP82" type="sp" figID="35">
    <name />
  </text>
  <text ewd="SYS061" code="SP106" type="sp" figID="37,38">
    <name />
  </text>
  <text ewd="SYS061" code="SP113" type="sp" figID="39">
    <name />
  </text>
  <text ewd="SYS061" code="IC2" type="w2w" figID="26">
    <name>Cowl Wire and Engine Wire</name>
  </text>
  <text ewd="SYS061" code="IS3" type="w2w" figID="21">
    <name>Cowl Wire and Floor Wire</name>
  </text>
  <text ewd="SYS061" code="IL2" type="w2w" figID="16,25">
    <name>Cowl Wire and Instrument Panel Wire</name>
  </text>
  <text ewd="SYS061" code="AI1" type="w2w" figID="17">
    <name>Engine Room Main Wire and Cowl Wire</name>
  </text>
  <text ewd="SYS061" code="AI3" type="w2w" figID="24">
    <name>Engine Room Main Wire and Cowl Wire</name>
  </text>
  <text ewd="SYS061" code="AC1" type="w2w" figID="23">
    <name>Engine Room Main Wire and Engine Wire</name>
  </text>
  <text ewd="SYS061" code="ST3" type="w2w" figID="19">
    <name>Floor Wire and No. 2 Floor Wire</name>
  </text>
  <text ewd="SYS061" code="LI1" type="w2w" figID="18,22">
    <name>Instrument Panel Wire and Cowl Wire</name>
  </text>
  <text ewd="SYS061" code="TS2" type="w2w" figID="20">
    <name>No. 2 Floor Wire and Floor Wire</name>
  </text>
</EwdTree>

=== randokuruza70/manual/manual/ewd/contents/tree/201408/models/HZJ71L-RJMRS/tree-SYS066.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE EwdTree SYSTEM "../../../../../dtd/ewdtree.dtd">
<EwdTree ver="2.1.2.9" pubno="EM25T2E" xml:lang="en">
  <text ewd="SYS066" code="I61,I72" type="conn" figID="2">
    <name>No. 11 Junction Connector , No. 21 Junction Connector</name>
  </text>
  <text ewd="SYS066" code="L32,L37" type="conn" figID="3">
    <name>No. 24 Junction Connector , No. 29 Junction Connector</name>
  </text>
  <text ewd="SYS066" code="L34" type="conn" figID="5">
    <name>No. 26 Junction Connector</name>
  </text>
  <text ewd="SYS066" code="L35" type="conn" figID="4">
    <name>No. 27 Junction Connector</name>
  </text>
  <text ewd="SYS066" code="L39" type="conn" figID="8">
    <name>No. 31 Junction Connector</name>
  </text>
  <text ewd="SYS066" code="L16" type="conn" figID="9">
    <name>Outer Mirror Switch Assembly</name>
  </text>
  <text ewd="SYS066" code="i1" type="conn" figID="6">
    <name>Outer Rear View Mirror Assembly LH</name>
  </text>
  <text ewd="SYS066" code="j1" type="conn" figID="7">
    <name>Outer Rear View Mirror Assembly RH</name>
  </text>
  <text ewd="SYS066" code="FUSE1" type="fuse" figID="26">
    <name>7.5A ACC</name>
  </text>
  <text ewd="SYS066" code="LA" type="gp" figID="25">
    <name />
  </text>
  <text ewd="SYS066" code="LB" type="gp" figID="24">
    <name />
  </text>
  <text ewd="SYS066" code="FUSE1" type="rb" figID="1">
    <name>7.5A ACC</name>
  </text>
  <text ewd="SYS066" code="IL1" type="w2w" figID="11">
    <name>Cowl Wire and Instrument Panel Wire</name>
  </text>
  <text ewd="SYS066" code="PL1" type="w2w" figID="13,15,17">
    <name>Front Door Wire LH and Instrument Panel Wire</name>
  </text>
  <text ewd="SYS066" code="Pi1" type="w2w" figID="12,14,16">
    <name>Front Door Wire LH and Switch Wire LH</name>
  </text>
  <text ewd="SYS066" code="OL1" type="w2w" figID="19,21,23">
    <name>Front Door Wire RH and Instrument Panel Wire</name>
  </text>
  <text ewd="SYS066" code="Oj1" type="w2w" figID="18,20,22">
    <name>Front Door Wire RH and Switch Wire RH</name>
  </text>
</EwdTree>

=== randokuruza70/manual/manual/ewd/contents/tree/201701/tree-WR060.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE EwdTree SYSTEM "../../../dtd/ewdtree.dtd">
<EwdTree ver="2.1.2.9" pubno="EM25T2E" xml:lang="en">
  <text ewd="WR060" code="AA" type="gp">
    <name>Ground Point</name>
  </text>
  <text ewd="WR060" code="AC" type="gp">
    <name>Ground Point</name>
  </text>
  <text ewd="WR060" code="AD" type="gp">
    <name>Ground Point</name>
  </text>
  <text ewd="WR060" code="CA" type="gp">
    <name>Ground Point</name>
  </text>
  <text ewd="WR060" code="CB" type="gp">
    <name>Ground Point</name>
  </text>
  <text ewd="WR060" code="DA" type="gp">
    <name>Ground Point</name>
  </text>
  <text ewd="WR060" code="HA" type="gp">
    <name>Ground Point</name>
  </text>
  <text ewd="WR060" code="HB" type="gp">
    <name>Ground Point</name>
  </text>
  <text ewd="WR060" code="IE" type="gp">
    <name>Ground Point</name>
  </text>
  <text ewd="WR060" code="tA" type="gp">
    <name>Ground Point</name>
  </text>
</EwdTree>

=== randokuruza70/manual/manual/ewd/contents/tree/201608/tree-WIRE002.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE EwdTree SYSTEM "../../../dtd/ewdtree.dtd">
<EwdTree ver="2.1.2.9" pubno="EM25T2E" xml:lang="en">
  <note ewd="WIRE002" code="B2" type="conn">
    <name>Front Differential Lock Position Switch</name>
  </note>
  <note ewd="WIRE002" code="B3" type="conn">
    <name>Front Speed Sensor RH (Skid Control Sensor Wire RH)</name>
  </note>
  <note ewd="WIRE002" code="B4" type="conn">
    <name>Front Speed Sensor RH (Skid Control Sensor Wire RH)</name>
  </note>
  <note ewd="WIRE002" code="B1" type="conn">
    <name>No. 2 Differential Lock Shift Actuator</name>
  </note>
  <note ewd="WIRE002" code="B5" type="conn">
    <name>No. 2 Differential Lock Shift Actuator</name>
  </note>
  <note ewd="WIRE002" code="BI2" type="w2w">
    <name>No. 2 Engine Room Wire and Cowl Wire</name>
  </note>
</EwdTree>
