=== randokuruza70/manual/manual/ewd/dtd/ewdtext.dtd
<!-- <?xml version="1.0" encoding="UTF-8"?> -->
<!-- XML DTD for TOYOTA EWD -->
<!--
	EWD DTD for SVG translation text XML

	Copyright (c) 2000-2012 SHINTEC HOZUMI Co.,LTD.
	All Rights Reserved. 

	ver 2.0		2011/12/06
	ver 2.1		2012/07/10	add entity value of CountryCode
-->

<!ENTITY % CountryCode "(en | ja | de | fr | es | it | nl | pt | da | sv | fi | no | is | cs | 
                         hu | pl | sl | sq | tr | el | ru | uk | la | he | zh | th | vi)">
<!ENTITY % Number "NMTOKEN">
<!ELEMENT texts (text)+>
<!ATTLIST texts
	ver CDATA #IMPLIED
	pubno CDATA #REQUIRED
	lang %CountryCode; #REQUIRED
	style CDATA #REQUIRED
>
<!ELEMENT text (#PCDATA)>
<!ATTLIST text
	textID %Number; #REQUIRED
>

=== randokuruza70/manual/manual/ewd/contents/system/text/en/HBLC-B.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE texts SYSTEM "../../../../dtd/ewdtext.dtd">
<texts lang="en" pubno="EM25T2E" style="font-size:6px;font-family:'Arial'" ver="2.1.2.9">
	<text textID="1">DIM Relay</text>
	<text textID="2">H-LP Relay</text>
	<text textID="3">Head</text>
	<text textID="4">Headlight Assembly LH</text>
	<text textID="5">Headlight Assembly RH</text>
	<text textID="6">Headlight Beam Level Control Actuator</text>
	<text textID="7">Headlight Dimmer Switch Assembly</text>
	<text textID="8">Headlight Leveling Switch</text>
	<text textID="9">Light Control Switch</text>
	<text textID="10">No. 22 Junction Connector</text>
	<text textID="11">No. 26 Junction Connector</text>
	<text textID="12">No. 31 Junction Connector</text>
	<text textID="13">Tail</text>
</texts>
