=== randokuruza70/manual/manual/ewd/dtd/ewdtext.dtd
<!-- <?xml version="1.0" encoding="UTF-8"?> -->
<!-- XML DTD for TOYOTA EWD -->
<!--
	EWD DTD for SVG translation text XML

	Copyright (c) 2000-2012 SHINTEC HOZUMI Co.,LTD.
	All Rights Reserved. 

	ver 2.0		2011/12/06
	ver 2.1		2012/07/10	add entity value of CountryCode
-->

<!ENTITY % CountryCode "(en | ja | de | fr | es | it | nl | pt | da | sv | fi | no | is | cs | 
                         hu | pl | sl | sq | tr | el | ru | uk | la | he | zh | th | vi)">
<!ENTITY % Number "NMTOKEN">
<!ELEMENT texts (text)+>
<!ATTLIST texts
	ver CDATA #IMPLIED
	pubno CDATA #REQUIRED
	lang %CountryCode; #REQUIRED
	style CDATA #REQUIRED
>
<!ELEMENT text (#PCDATA)>
<!ATTLIST text
	textID %Number; #REQUIRED
>

=== randokuruza70/manual/manual/ewd/contents/system/text/en/HL-F.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE texts SYSTEM "../../../../dtd/ewdtext.dtd">
<texts lang="en" pubno="EM25T2E" style="font-size:6px;font-family:'Arial'" ver="2.1.2.9">
	<text textID="1">* 6 :1GR-FE, RHD 1HZ 24V Battery Type</text>
	<text textID="2">* 7 :1VD-FTV, RHD 1HZ 12V Battery Type</text>
	<text textID="3">* 8 :1GR-FE, 1VD-FTV, 1HZ 12V Battery Type</text>
	<text textID="4">* 9 :1HZ 24V Battery Type</text>
	<text textID="5">*10 :1HZ 12V Battery Type</text>
	<text textID="6">Combination Meter Assembly</text>
	<text textID="7">DIM Relay</text>
	<text textID="8">Dimmer Switch</text>
	<text textID="9">Flash</text>
	<text textID="10">H-LP Relay</text>
	<text textID="11">Head</text>
	<text textID="12">Headlight Assembly LH</text>
	<text textID="13">Headlight Assembly RH</text>
	<text textID="14">Headlight Dimmer Switch Assembly</text>
	<text textID="15">High</text>
	<text textID="16">High Beam</text>
	<text textID="17">Light Control Switch</text>
	<text textID="18">Low</text>
	<text textID="19">No. 1 Junction Connector</text>
	<text textID="20">No. 12 Junction Connector</text>
	<text textID="21">No. 12 Junction Connector , No. 20 Junction Connector</text>
	<text textID="22">No. 20 Junction Connector</text>
	<text textID="23">No. 24 Junction Connector</text>
	<text textID="24">No. 24 Junction Connector , No. 26 Junction Connector</text>
	<text textID="25">No. 26 Junction Connector</text>
	<text textID="26">No. 31 Junction Connector</text>
	<text textID="27">Tail</text>
</texts>

=== randokuruza70/manual/manual/ewd/contents/system/text/en/TL-B.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE texts SYSTEM "../../../../dtd/ewdtext.dtd">
<texts lang="en" pubno="EM25T2E" style="font-size:6px;font-family:'Arial'" ver="2.1.2.9">
	<text textID="1">* 1 :Pick-Up Body Type</text>
	<text textID="2">* 2 :Except Pick-Up Body Type</text>
	<text textID="3">* 3 :Algeria, Australia</text>
	<text textID="4">* 4 :Except *3</text>
	<text textID="5">* 7 :1GR-FE, RHD 1HZ 24V Battery Type</text>
	<text textID="6">* 8 :1VD-FTV, RHD 1HZ 12V Battery Type</text>
	<text textID="7">*10 :RHD 1HZ 24V Battery Type</text>
	<text textID="8">*11 :RHD 1HZ 12V Battery Type</text>
	<text textID="9">*14 :Back Door w/ Fuel Tank</text>
	<text textID="10">*15 :Back Door w/o Fuel Tank</text>
	<text textID="11">Clearance</text>
	<text textID="12">Head</text>
	<text textID="13">Headlight Assembly LH</text>
	<text textID="14">Headlight Assembly RH</text>
	<text textID="15">Headlight Dimmer Switch Assembly</text>
	<text textID="16">License Plate Light Assembly</text>
	<text textID="17">License Plate Light Assembly LH</text>
	<text textID="18">License Plate Light Assembly RH</text>
	<text textID="19">Light Control Switch</text>
	<text textID="20">No. 1 Junction Connector</text>
	<text textID="21">No. 6 Junction Connector</text>
	<text textID="22">No. 9 Junction Connector</text>
	<text textID="23">No. 31 Junction Connector</text>
	<text textID="24">Rear Combination Light Assembly LH</text>
	<text textID="25">Rear Combination Light Assembly RH</text>
	<text textID="26">TAIL Relay</text>
	<text textID="27">Tail</text>
</texts>

=== randokuruza70/manual/manual/ewd/contents/system/text/en/EIS-B.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE texts SYSTEM "../../../../dtd/ewdtext.dtd">
<texts lang="en" pubno="EM25T2E" style="font-size:6px;font-family:'Arial'" ver="2.1.2.9">
	<text textID="1">* 3 :2-Door Pick-Up Body Type</text>
	<text textID="2">* 4 :4-Door Pick-Up Body Type, Except Pick-Up Body Type</text>
	<text textID="3">Combination Meter Assembly</text>
	<text textID="4">Front Door Courtesy Light Switch Assembly LH</text>
	<text textID="5">Front Door Courtesy Light Switch Assembly RH</text>
	<text textID="6">No. 6 Junction Connector</text>
	<text textID="7">No. 8 Junction Connector</text>
	<text textID="8">No. 11 Junction Connector</text>
	<text textID="9">No. 11 Junction Connector , No. 21 Junction Connector</text>
	<text textID="10">No. 13 Junction Connector</text>
	<text textID="11">No. 16 Junction Connector</text>
	<text textID="12">No. 18 Junction Connector</text>
	<text textID="13">No. 21 Junction Connector</text>
	<text textID="14">No. 24 Junction Connector</text>
	<text textID="15">No. 24 Junction Connector , No. 26 Junction Connector</text>
	<text textID="16">No. 24 Junction Connector , No. 28 Junction Connector</text>
	<text textID="17">No. 26 Junction Connector</text>
	<text textID="18">No. 27 Junction Connector</text>
	<text textID="19">No. 27 Junction Connector , No. 28 Junction Connector</text>
	<text textID="20">No. 28 Junction Connector</text>
	<text textID="21">No. 31 Junction Connector</text>
	<text textID="22">Security</text>
	<text textID="23">Transponder Key Amplifier</text>
	<text textID="24">Transponder Key ECU Assembly</text>
	<text textID="25">Un-Lock Warning Switch Assembly</text>
</texts>

=== randokuruza70/manual/manual/ewd/contents/system/text/en/AC-1GR-F.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE texts SYSTEM "../../../../dtd/ewdtext.dtd">
<texts lang="en" pubno="EM25T2E" style="font-size:6px;font-family:'Arial'" ver="2.1.2.9">
	<text textID="1">* 5 :w/ Air Conditioner</text>
	<text textID="2">* 6 :Australia</text>
	<text textID="3">* 7 :Except Australia</text>
	<text textID="4">* 8 :Shielded</text>
	<text textID="5">A/C COMP Relay</text>
	<text textID="6">A/C Pressure Switch (Cooler Refrigerant Liquid Pipe B)</text>
	<text textID="7">Blower Resistor</text>
	<text textID="8">Cooler Stabilizer Amplifier Assembly</text>
	<text textID="9">Crank Position Sensor</text>
	<text textID="10">Diesel Engine Coolant Temperature Sensor</text>
	<text textID="11">E.F.I. Engine Coolant Temperature Sensor</text>
	<text textID="12">Front Blower Motor (Heater Blower Case)</text>
	<text textID="13">HTR Relay</text>
	<text textID="14">Heater Blower Switch Assembly</text>
	<text textID="15">Magnet Clutch Assembly</text>
	<text textID="16">No. 1 Cooler Thermistor</text>
	<text textID="17">No. 4 Junction Connector</text>
	<text textID="18">No. 7 Junction Connector</text>
	<text textID="19">No. 8 Junction Connector</text>
	<text textID="20">No. 10 Junction Connector</text>
	<text textID="21">No. 10 Junction Connector , No. 16 Junction Connector</text>
	<text textID="22">No. 10 Junction Connector , No. 19 Junction Connector</text>
	<text textID="23">No. 12 Junction Connector</text>
	<text textID="24">No. 12 Junction Connector , No. 16 Junction Connector</text>
	<text textID="25">No. 13 Junction Connector</text>
	<text textID="26">No. 16 Junction Connector</text>
	<text textID="27">No. 19 Junction Connector</text>
	<text textID="28">No. 32 Junction Connector</text>
	<text textID="29">Short Connector</text>
</texts>

=== randokuruza70/manual/manual/ewd/contents/system/text/en/C-B.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE texts SYSTEM "../../../../dtd/ewdtext.dtd">
<texts lang="en" pubno="EM25T2E" style="font-size:6px;font-family:'Arial'" ver="2.1.2.9">
	<text textID="1">* 2 :12V Battery Type</text>
	<text textID="2">* 3 :24V Battery Type</text>
	<text textID="3">* 4 :1HZ 12V Battery Type, 1VD-FTV</text>
	<text textID="4">* 5 :1HZ 24V Battery Type</text>
	<text textID="5">* 6 :Multi Clock Type</text>
	<text textID="6">* 7 :w/ ABS</text>
	<text textID="7">*21 :w/o ABS</text>
	<text textID="8">*22 :LHD 1GR-FE w/o ABS</text>
	<text textID="9">*23 :1HZ w/o ABS</text>
	<text textID="10">Brake Actuator Assembly</text>
	<text textID="11">Clock Assembly</text>
	<text textID="12">Combination Meter Assembly</text>
	<text textID="13">Meter Micro Computer</text>
	<text textID="14">No. 8 Junction Connector</text>
	<text textID="15">No. 9 Junction Connector</text>
	<text textID="16">No. 9 Junction Connector , No. 21 Junction Connector</text>
	<text textID="17">No. 11 Junction Connector</text>
	<text textID="18">No. 11 Junction Connector , No. 21 Junction Connector</text>
	<text textID="19">No. 12 Junction Connector</text>
	<text textID="20">No. 13 Junction Connector</text>
	<text textID="21">No. 18 Junction Connector</text>
	<text textID="22">No. 21 Junction Connector</text>
	<text textID="23">No. 24 Junction Connector</text>
	<text textID="24">No. 24 Junction Connector , No. 28 Junction Connector</text>
	<text textID="25">No. 24 Junction Connector , No. 29 Junction Connector</text>
	<text textID="26">No. 25 Junction Connector</text>
	<text textID="27">No. 25 Junction Connector , No. 28 Junction Connector</text>
	<text textID="28">No. 25 Junction Connector , No. 29 Junction Connector</text>
	<text textID="29">No. 28 Junction Connector</text>
	<text textID="30">No. 29 Junction Connector</text>
	<text textID="31">Speedometer Sensor</text>
	<text textID="32">Thermistor Assembly</text>
</texts>

=== randokuruza70/manual/manual/ewd/contents/system/text/en/DLC-LHD-B.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE texts SYSTEM "../../../../dtd/ewdtext.dtd">
<texts lang="en" pubno="EM25T2E" style="font-size:6px;font-family:'Arial'" ver="2.1.2.9">
	<text textID="1">* 1 :4-Door</text>
	<text textID="2">* 2 :2-Door</text>
	<text textID="3">* 3 :w/ Power Window</text>
	<text textID="4">* 4 :w/o Power Window</text>
	<text textID="5">* 5 :4-Door Pick-Up Body Type</text>
	<text textID="6">* 6 :4-Door Except Pick-Up Body Type</text>
	<text textID="7">* 7 :2-Door Except Pick-Up Body Type</text>
	<text textID="8">* 8 :Except Pick-Up Body Type</text>
	<text textID="9">* 9 :Except 2-Door Pick-Up Body Type</text>
	<text textID="10">Back Door Lock Assembly</text>
	<text textID="11">Door Control Relay Assembly</text>
	<text textID="12">Door Control Switch</text>
	<text textID="13">Door Control Switch Assembly</text>
	<text textID="14">Door Lock Control Switch</text>
	<text textID="15">Front Door Lock Actuator Assembly LH</text>
	<text textID="16">Front Door Lock Actuator Assembly RH</text>
	<text textID="17">Key Lock</text>
	<text textID="18">Key Unlock</text>
	<text textID="19">Lock</text>
	<text textID="20">No. 31 Junction Connector</text>
	<text textID="21">Power Window Regulator Master Switch Assembly</text>
	<text textID="22">Rear Door Lock Actuator Assembly LH</text>
	<text textID="23">Rear Door Lock Actuator Assembly RH</text>
	<text textID="24">Unlock</text>
</texts>

=== randokuruza70/manual/manual/ewd/contents/system/text/en/FFL-B.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE texts SYSTEM "../../../../dtd/ewdtext.dtd">
<texts lang="en" pubno="EM25T2E" style="font-size:6px;font-family:'Arial'" ver="2.1.2.9">
	<text textID="1">Combination Meter Assembly</text>
	<text textID="2">FR FOG Relay</text>
	<text textID="3">Fog Light Assembly LH</text>
	<text textID="4">Fog Light Assembly RH</text>
	<text textID="5">Fog Light Switch</text>
	<text textID="6">Front</text>
	<text textID="7">Front Fog</text>
	<text textID="8">Head</text>
	<text textID="9">Headlight Dimmer Switch Assembly</text>
	<text textID="10">Light Control Switch</text>
	<text textID="11">No. 9 Junction Connector</text>
	<text textID="12">No. 31 Junction Connector</text>
	<text textID="13">Rear</text>
	<text textID="14">TAIL Relay</text>
	<text textID="15">Tail</text>
</texts>

=== randokuruza70/manual/manual/ewd/contents/system/text/en/LR-F.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE texts SYSTEM "../../../../dtd/ewdtext.dtd">
<texts lang="en" pubno="EM25T2E" style="font-size:6px;font-family:'Arial'" ver="2.1.2.9">
	<text textID="1">* 5 :1GR-FE, 1VD-FTV, 1HZ 12V Battery Type</text>
	<text textID="2">* 6 :1HZ 24V Battery Type</text>
	<text textID="3">* 7 :1HZ 12V Battery Type</text>
	<text textID="4">* 8 :2-Door Pick-Up Body Type</text>
	<text textID="5">* 9 :4-Door Pick-Up Body Type</text>
	<text textID="6">*10 :Except Pick-Up Body Type</text>
	<text textID="7">*11 :w/ VSC</text>
	<text textID="8">*12 :w/o VSC</text>
	<text textID="9">*13 :Before Jan. 2017 Production</text>
	<text textID="10">*14 :From Jan. 2017 Production</text>
	<text textID="11">Buzzer</text>
	<text textID="12">Combination Meter Assembly</text>
	<text textID="13">Front Door Courtesy Light Switch Assembly LH</text>
	<text textID="14">Front Door Courtesy Light Switch Assembly RH</text>
	<text textID="15">Head</text>
	<text textID="16">Headlight Dimmer Switch Assembly</text>
	<text textID="17">Light Control Switch</text>
	<text textID="18">No. 9 Junction Connector</text>
	<text textID="19">No. 9 Junction Connector , No. 36 Junction Connector , No. 21 Junction Connector</text>
	<text textID="20">No. 11 Junction Connector</text>
	<text textID="21">No. 11 Junction Connector , No. 21 Junction Connector</text>
	<text textID="22">No. 16 Junction Connector</text>
	<text textID="23">No. 21 Junction Connector</text>
	<text textID="24">No. 27 Junction Connector</text>
	<text textID="25">No. 27 Junction Connector , No. 28 Junction Connector</text>
	<text textID="26">No. 28 Junction Connector</text>
	<text textID="27">No. 30 Junction Connector</text>
	<text textID="28">No. 31 Junction Connector</text>
	<text textID="29">No. 33 Junction Connector</text>
	<text textID="30">No. 36 Junction Connector</text>
	<text textID="31">TAIL Relay</text>
	<text textID="32">Tail</text>
</texts>
