=== randokuruza70/manual/manual/ewd/dtd/ewdtree.dtd
<!-- <?xml version="1.0" encoding="UTF-8"?> -->
<!-- XML DTD for TOYOTA EWD -->
<!--
	EWD DTD for EWD Tree XML

	Copyright (c) 2000-2012 SHINTEC HOZUMI Co.,LTD.
	All Rights Reserved. 

	ver 2.0		2012/03/21
	ver 2.1		2012/07/10	add entity value of CountryCode
-->

<!ENTITY % CountryCode "(en | ja | de | fr | es | it | nl | pt | da | sv | fi | no | is | cs | 
                         hu | pl | sl | sq | tr | el | ru | uk | la | he | zh | th | vi)">
<!ENTITY % Book "( name, note*, book* )">
<!ELEMENT EwdTree (book* | root* | text* | note*)>
<!ATTLIST EwdTree
	ver CDATA #IMPLIED
	pubno CDATA #REQUIRED
	xml:lang %CountryCode; #REQUIRED
>
<!ELEMENT root (name)>
<!ATTLIST root
	id CDATA #REQUIRED
>
<!ELEMENT book (%Book;)>
<!ATTLIST book
	id CDATA #REQUIRED
	file CDATA #IMPLIED
>
<!ELEMENT text (name)>
<!ATTLIST text
	ewd CDATA #IMPLIED
	code CDATA #IMPLIED
	type CDATA #IMPLIED
	figID CDATA #IMPLIED
>
<!ELEMENT note (%Book;, text*)>
<!ATTLIST note
	id CDATA #IMPLIED
	icon CDATA #IMPLIED
	file CDATA #IMPLIED
	ewd CDATA #IMPLIED
	code CDATA #IMPLIED
	type CDATA #IMPLIED
>
<!ELEMENT name (#PCDATA)>

=== randokuruza70/manual/manual/ewd/contents/tree/201608/tree-SYS059.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE EwdTree SYSTEM "../../../dtd/ewdtree.dtd">
<EwdTree ver="2.1.2.9" pubno="EM25T2E" xml:lang="en">
  <text ewd="SYS059" code="O2,P2" type="conn" figID="1,2">
    <name>Front Power Window Regulator Motor Assembly RH , Front Power Window Regulator Motor Assembly LH</name>
  </text>
  <text ewd="SYS059" code="O10,O11,P11,P12" type="conn" figID="10">
    <name>Front Power Window Regulator Switch Assembly RH , Front Power Window Regulator Switch Assembly LH</name>
  </text>
  <text ewd="SYS059" code="I96" type="conn" figID="9">
    <name>No. 20 Junction Connector</name>
  </text>
  <text ewd="SYS059" code="I93" type="conn" figID="6">
    <name>No. 5 Junction Connector</name>
  </text>
  <text ewd="SYS059" code="O8,O9,P9,P10" type="conn" figID="8">
    <name>Power Window Regulator Master Switch Assembly</name>
  </text>
  <text ewd="SYS059" code="Q3" type="conn" figID="4">
    <name>Rear Power Window Regulator Motor Assembly LH</name>
  </text>
  <text ewd="SYS059" code="R3" type="conn" figID="3">
    <name>Rear Power Window Regulator Motor Assembly RH</name>
  </text>
  <text ewd="SYS059" code="Q1" type="conn" figID="11">
    <name>Rear Power Window Regulator Switch Assembly LH</name>
  </text>
  <text ewd="SYS059" code="R1" type="conn" figID="7">
    <name>Rear Power Window Regulator Switch Assembly RH</name>
  </text>
  <text ewd="SYS059" code="FUSE32" type="fuse" figID="61">
    <name>30A POWER</name>
  </text>
  <text ewd="SYS059" code="IA" type="gp" figID="50">
    <name />
  </text>
  <text ewd="SYS059" code="IC" type="gp" figID="51">
    <name />
  </text>
  <text ewd="SYS059" code="FUSE32" type="rb" figID="5">
    <name>30A POWER</name>
  </text>
  <text ewd="SYS059" code="SP61" type="sp" figID="55,56,57">
    <name />
  </text>
  <text ewd="SYS059" code="SP66" type="sp" figID="59">
    <name />
  </text>
  <text ewd="SYS059" code="SP88" type="sp" figID="60">
    <name />
  </text>
  <text ewd="SYS059" code="SP93" type="sp" figID="58">
    <name />
  </text>
  <text ewd="SYS059" code="SP142" type="sp" figID="54">
    <name />
  </text>
  <text ewd="SYS059" code="SP143" type="sp" figID="53">
    <name />
  </text>
  <text ewd="SYS059" code="SP144" type="sp" figID="52">
    <name />
  </text>
  <text ewd="SYS059" code="IS2" type="w2w" figID="33,37">
    <name>Cowl Wire and Floor Wire</name>
  </text>
  <text ewd="SYS059" code="IS3" type="w2w" figID="16">
    <name>Cowl Wire and Floor Wire</name>
  </text>
  <text ewd="SYS059" code="PI2" type="w2w" figID="13,40,44">
    <name>Front Door Wire LH and Cowl Wire</name>
  </text>
  <text ewd="SYS059" code="PI3" type="w2w" figID="24,29,31,35,39,43,47,49">
    <name>Front Door Wire LH and Cowl Wire</name>
  </text>
  <text ewd="SYS059" code="OI4" type="w2w" figID="14,41,45">
    <name>Front Door Wire RH and Cowl Wire</name>
  </text>
  <text ewd="SYS059" code="OI5" type="w2w" figID="23,28,30,34,38,42,46,48">
    <name>Front Door Wire RH and Cowl Wire</name>
  </text>
  <text ewd="SYS059" code="RS1" type="w2w" figID="15,32,36">
    <name>No. 1 Rear Door Wire and Floor Wire</name>
  </text>
  <text ewd="SYS059" code="QU1" type="w2w" figID="17,20,25">
    <name>No. 2 Rear Door Wire and No. 3 Floor Wire</name>
  </text>
  <text ewd="SYS059" code="UI4" type="w2w" figID="19,22,27">
    <name>No. 3 Floor Wire and Cowl Wire</name>
  </text>
  <text ewd="SYS059" code="UI5" type="w2w" figID="18,21,26">
    <name>No. 3 Floor Wire and Cowl Wire</name>
  </text>
</EwdTree>

=== randokuruza70/manual/manual/ewd/contents/tree/201408/tree-WIRE001.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE EwdTree SYSTEM "../../../dtd/ewdtree.dtd">
<EwdTree ver="2.1.2.9" pubno="EM25T2E" xml:lang="en">
  <note ewd="WIRE001" code="A6" type="conn">
    <name>A/C Pressure Switch (Cooler Refrigerant Liquid Pipe B)</name>
  </note>
  <note ewd="WIRE001" code="A10" type="conn">
    <name>Antenna with Holder Assembly</name>
  </note>
  <note ewd="WIRE001" code="A35" type="conn">
    <name>Battery (Main)</name>
  </note>
  <note ewd="WIRE001" code="A36" type="conn">
    <name>Battery (Main)</name>
  </note>
  <note ewd="WIRE001" code="A37" type="conn">
    <name>Battery (Sub)</name>
  </note>
  <note ewd="WIRE001" code="A20" type="conn">
    <name>Brake Actuator Assembly</name>
  </note>
  <note ewd="WIRE001" code="A42" type="conn">
    <name>Brake Actuator Assembly</name>
  </note>
  <note ewd="WIRE001" code="A15" type="conn">
    <name>Brake Fluid Level Warning Switch (Brake Master Cylinder Reservoir Sub-Assembly)</name>
  </note>
  <note ewd="WIRE001" code="A25" type="conn">
    <name>Brake Vacuum Check Valve Assembly</name>
  </note>
  <note ewd="WIRE001" code="A26" type="conn">
    <name>Brake Vacuum Check Valve Assembly</name>
  </note>
  <note ewd="WIRE001" code="A27" type="conn">
    <name>Brake Vacuum Check Valve Assembly</name>
  </note>
  <note ewd="WIRE001" code="A28" type="conn">
    <name>Brake Vacuum Check Valve Assembly</name>
  </note>
  <note ewd="WIRE001" code="A29" type="conn">
    <name>ECM</name>
  </note>
  <note ewd="WIRE001" code="A13" type="conn">
    <name>Front Airbag Sensor LH</name>
  </note>
  <note ewd="WIRE001" code="A21" type="conn">
    <name>Front Speed Sensor LH (Skid Control Sensor Wire LH)</name>
  </note>
  <note ewd="WIRE001" code="A8" type="conn">
    <name>Fuel Filter Vacuum Sensor</name>
  </note>
  <note ewd="WIRE001" code="A16" type="conn">
    <name>Fuel Heater</name>
  </note>
  <note ewd="WIRE001" code="A17" type="conn">
    <name>Fuel Pump Resistor Assembly</name>
  </note>
  <note ewd="WIRE001" code="A40" type="conn">
    <name>Fuel Pump Resistor Assembly</name>
  </note>
  <note ewd="WIRE001" code="A9" type="conn">
    <name>Fuel Sediment Switch</name>
  </note>
  <note ewd="WIRE001" code="A1" type="conn">
    <name>Headlight Assembly LH</name>
  </note>
  <note ewd="WIRE001" code="A3" type="conn">
    <name>Headlight Assembly LH</name>
  </note>
  <note ewd="WIRE001" code="A7" type="conn">
    <name>Headlight Assembly LH</name>
  </note>
  <note ewd="WIRE001" code="A14" type="conn">
    <name>Headlight Assembly LH</name>
  </note>
  <note ewd="WIRE001" code="A38" type="conn">
    <name>Headlight Assembly LH</name>
  </note>
  <note ewd="WIRE001" code="A5" type="conn">
    <name>High Pitched Horn Assembly</name>
  </note>
  <note ewd="WIRE001" code="A4" type="conn">
    <name>Low Pitched Horn Assembly</name>
  </note>
  <note ewd="WIRE001" code="A22" type="conn">
    <name>No. 1 Junction Connector</name>
  </note>
  <note ewd="WIRE001" code="A18" type="conn">
    <name>No. 1 Vacuum Switching Valve (A/C Idle-Up)</name>
  </note>
  <note ewd="WIRE001" code="A41" type="conn">
    <name>No. 1 Vacuum Switching Valve (A/C Idle-Up)</name>
  </note>
  <note ewd="WIRE001" code="A23" type="conn">
    <name>No. 2 Junction Connector</name>
  </note>
  <note ewd="WIRE001" code="A24" type="conn">
    <name>No. 3 CAN Junction Connector</name>
  </note>
  <note ewd="WIRE001" code="A43" type="conn">
    <name>No. 34 Junction Connector</name>
  </note>
  <note ewd="WIRE001" code="A11" type="conn">
    <name>Side Turn Signal Light Assembly LH</name>
  </note>
  <note ewd="WIRE001" code="A2" type="conn">
    <name>Windshield Washer Motor and Pump Assembly</name>
  </note>
  <note ewd="WIRE001" code="A12" type="conn">
    <name>Windshield Wiper Motor Assembly</name>
  </note>
  <note ewd="WIRE001" code="A39" type="conn">
    <name>Windshield Wiper Motor Assembly</name>
  </note>
  <note ewd="WIRE001" code="4A" type="jbc">
    <name>Engine Room Main Wire and Fuse Block Assembly</name>
  </note>
  <note ewd="WIRE001" code="4B" type="jbc">
    <name>Engine Room Main Wire and Fuse Block Assembly</name>
  </note>
  <note ewd="WIRE001" code="3B" type="jbc">
    <name>Engine Room Main Wire and Fusible Link Block Assembly</name>
  </note>
  <note ewd="WIRE001" code="3C" type="jbc">
    <name>Engine Room Main Wire and Fusible Link Block Assembly</name>
  </note>
  <note ewd="WIRE001" code="3D" type="jbc">
    <name>Engine Room Main Wire and Fusible Link Block Assembly</name>
  </note>
  <note ewd="WIRE001" code="3E" type="jbc">
    <name>Engine Room Main Wire and Fusible Link Block Assembly</name>
  </note>
  <note ewd="WIRE001" code="3F" type="jbc">
    <name>Engine Room Main Wire and Fusible Link Block Assembly</name>
  </note>
  <note ewd="WIRE001" code="3G" type="jbc">
    <name>Engine Room Main Wire and Fusible Link Block Assembly</name>
  </note>
  <note ewd="WIRE001" code="3H" type="jbc">
    <name>Engine Room Main Wire and Fusible Link Block Assembly</name>
  </note>
  <note ewd="WIRE001" code="3I" type="jbc">
    <name>Engine Room Main Wire and Fusible Link Block Assembly</name>
  </note>
  <note ewd="WIRE001" code="3A" type="jbc">
    <name>Engine Room Main Wire and Fusible Link Block Assembly [1HZ]</name>
  </note>
  <note ewd="WIRE001" code="AC1" type="w2w">
    <name>Engine Room Main Wire and Engine Wire</name>
  </note>
  <note ewd="WIRE001" code="AC2" type="w2w">
    <name>Engine Room Main Wire and Engine Wire</name>
  </note>
  <note ewd="WIRE001" code="AC3" type="w2w">
    <name>Engine Room Main Wire and Engine Wire</name>
  </note>
  <note ewd="WIRE001" code="AC5" type="w2w">
    <name>Engine Room Main Wire and Engine Wire</name>
  </note>
  <note ewd="WIRE001" code="AC7" type="w2w">
    <name>Engine Room Main Wire and Engine Wire</name>
  </note>
  <note ewd="WIRE001" code="AC8" type="w2w">
    <name>Engine Room Main Wire and Engine Wire</name>
  </note>
  <note ewd="WIRE001" code="AC9" type="w2w">
    <name>Engine Room Main Wire and Engine Wire</name>
  </note>
  <note ewd="WIRE001" code="AC10" type="w2w">
    <name>Engine Room Main Wire and Engine Wire</name>
  </note>
  <note ewd="WIRE001" code="AC11" type="w2w">
    <name>Engine Room Main Wire and Engine Wire</name>
  </note>
</EwdTree>

=== randokuruza70/manual/manual/ewd/contents/tree/201701/tree-RELAY_RL002.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE EwdTree SYSTEM "../../../dtd/ewdtree.dtd">
<EwdTree ver="2.1.2.9" pubno="EM25T2E" xml:lang="en">
  <note id="RL002" icon="P">
    <name>Relay Location(LHD)</name>
    <book id="RELAY_RL009">
      <name>Cowl Side R/B Assembly</name>
      <note id="RL002_RL009">
        <name>Cowl Side R/B Assembly</name>
      </note>
      <note id="RL002_RL009-Inn">
        <name>Inner Circuit</name>
      </note>
    </book>
    <book id="RELAY_RL012">
      <name>No. 1 CAN Junction Connector</name>
      <note id="RL002_RL012">
        <name>No. 1 CAN Junction Connector</name>
      </note>
      <note id="RL002_RL012-Inn">
        <name>Inner Circuit</name>
      </note>
    </book>
    <book id="RELAY_RL013">
      <name>No. 2 CAN Junction Connector</name>
      <note id="RL002_RL013">
        <name>No. 2 CAN Junction Connector</name>
      </note>
      <note id="RL002_RL013-Inn">
        <name>Inner Circuit</name>
      </note>
    </book>
    <book id="RELAY_RL015">
      <name>No. 6 CAN Junction Connector</name>
      <note id="RL002_RL015">
        <name>No. 6 CAN Junction Connector</name>
      </note>
      <note id="RL002_RL015-Inn">
        <name>Inner Circuit</name>
      </note>
    </book>
  </note>
</EwdTree>

=== randokuruza70/manual/manual/ewd/contents/tree/201408/models/HZJ76R-RKMRS/tree-system.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE EwdTree SYSTEM "../../../../../dtd/ewdtree.dtd">
<EwdTree ver="2.1.2.9" pubno="EM25T2E" xml:lang="en">
  <book id="S-EG">
    <name>Engine / Hybrid System</name>
    <note id="SYS018" icon="P" file="T">
      <name>Emission Control (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS026" icon="P" file="T">
      <name>Fuel Heater (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS030" icon="P" file="T">
      <name>Fuel Tank Changeover (Diesel) (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS032" icon="P" file="T">
      <name>Glow Plug (w/o Emission Control) (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS034" icon="P" file="T">
      <name>Ignition (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS038" icon="P" file="T">
      <name>Starting (1HZ) (Before Aug. 2016 Production)</name>
    </note>
  </book>
  <book id="S-DR">
    <name>Drivetrain</name>
    <note id="SYS013" icon="P" file="T">
      <name>4WD (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS015" icon="P" file="T">
      <name>Front/Rear Differential Lock (Before Aug. 2016 Production)</name>
    </note>
  </book>
  <book id="S-SS">
    <name>Suspension</name>
  </book>
  <book id="S-BK">
    <name>Brake</name>
    <note id="SYS005" icon="P" file="T">
      <name>ABS (Before Aug. 2016 Production)</name>
    </note>
  </book>
  <book id="S-AV">
    <name>Audio/Visual/Telematics</name>
    <note id="SYS001" icon="P" file="T">
      <name>Audio System (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS003" icon="P" file="T">
      <name>Auto Antenna (Before Aug. 2016 Production)</name>
    </note>
  </book>
  <book id="S-PS">
    <name>Power Source / Network</name>
    <note id="SYS120" icon="P" file="T">
      <name>Charging (1HZ) (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS124" icon="P" file="T">
      <name>DLC3 (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS126" icon="P" file="T">
      <name>Multiplex Communication System (CAN) (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS128" icon="P" file="T">
      <name>Power Source (Diesel) (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS130" icon="P" file="T">
      <name>Power Source (Gasoline) (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS134" icon="P" file="T">
      <name>Ground Point (RHD Before Aug. 2016 Production)</name>
    </note>
  </book>
  <book id="S-IN">
    <name>Vehicle Interior</name>
    <note id="SYS082" icon="P" file="T">
      <name>Air Conditioner (1HZ) (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS084" icon="P" file="T">
      <name>Cigarette Lighter (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS086" icon="P" file="T">
      <name>Clock (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS088" icon="P" file="T">
      <name>Combination Meter (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS094" icon="P" file="T">
      <name>Door Lock Control (RHD w/ Wireless Door Lock Control) (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS096" icon="P" file="T">
      <name>Door Lock Control (RHD w/o Wireless Door Lock Control) (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS098" icon="P" file="T">
      <name>Illumination (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS100" icon="P" file="T">
      <name>Immobiliser System (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS102" icon="P" file="T">
      <name>Interior Light (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS104" icon="P" file="T">
      <name>Key Reminder (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS106" icon="P" file="T">
      <name>Power Outlet (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS108" icon="P" file="T">
      <name>Rear Heater (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS110" icon="P" file="T">
      <name>Seat Belt Warning (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS112" icon="P" file="T">
      <name>SRS (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS116" icon="P" file="T">
      <name>Wireless Door Lock Control (RHD) (Before Aug. 2016 Production)</name>
    </note>
  </book>
  <book id="S-EX">
    <name>Vehicle Exterior</name>
    <note id="SYS040" icon="P" file="T">
      <name>Back-Up Light (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS042" icon="P" file="T">
      <name>Front Fog Light (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS046" icon="P" file="T">
      <name>Front Wiper and Washer (RHD 12V Battery Type) (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS048" icon="P" file="T">
      <name>Front Wiper and Washer (RHD 24V Battery Type) (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS050" icon="P" file="T">
      <name>Headlight (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS052" icon="P" file="T">
      <name>Headlight Beam Level Control (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS054" icon="P" file="T">
      <name>Horn (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS056" icon="P" file="T">
      <name>Light Reminder (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS058" icon="P" file="T">
      <name>Power Window (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS060" icon="P" file="T">
      <name>Rear Fog Light (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS062" icon="P" file="T">
      <name>Rear Window Defogger (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS064" icon="P" file="T">
      <name>Rear Wiper and Washer (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS066" icon="P" file="T">
      <name>Remote Control Mirror (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS068" icon="P" file="T">
      <name>Stop Light (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS070" icon="P" file="T">
      <name>Taillight (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS072" icon="P" file="T">
      <name>Trailer Socket (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS074" icon="P" file="T">
      <name>Turn Signal and Hazard Warning Light (12V Battery Type) (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS076" icon="P" file="T">
      <name>Turn Signal and Hazard Warning Light (24V Battery Type) (Before Aug. 2016 Production)</name>
    </note>
    <note id="SYS078" icon="P" file="T">
      <name>Winch (Before Aug. 2016 Production)</name>
    </note>
  </book>
</EwdTree>

=== randokuruza70/manual/manual/ewd/contents/tree/201701/models/HZJ76L-RKMRS/tree-SYS039.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE EwdTree SYSTEM "../../../../../dtd/ewdtree.dtd">
<EwdTree ver="2.1.2.9" pubno="EM25T2E" xml:lang="en">
  <text ewd="SYS039" code="A36,D8,E1,E4,F1" type="conn" figID="7">
    <name>Battery (Main)</name>
  </text>
  <text ewd="SYS039" code="D10,E3" type="conn" figID="5">
    <name>Battery (Sub)</name>
  </text>
  <text ewd="SYS039" code="E2,F2" type="conn" figID="6">
    <name>Battery (Sub)</name>
  </text>
  <text ewd="SYS039" code="A30" type="conn" figID="10">
    <name>Emission Control ECU</name>
  </text>
  <text ewd="SYS039" code="A22" type="conn" figID="9">
    <name>No. 1 Junction Connector</name>
  </text>
  <text ewd="SYS039" code="I59,I70" type="conn" figID="2">
    <name>No. 10 Junction Connector , No. 19 Junction Connector</name>
  </text>
  <text ewd="SYS039" code="C89,D5" type="conn" figID="8">
    <name>Starter Assembly</name>
  </text>
  <text ewd="SYS039" code="FUSE55" type="fuse" figID="24">
    <name>50A AM2</name>
  </text>
  <text ewd="SYS039" code="FUSE3" type="fuse" figID="25">
    <name>7.5A ST</name>
  </text>
  <text ewd="SYS039" code="AA" type="gp" figID="21">
    <name />
  </text>
  <text ewd="SYS039" code="AC" type="gp" figID="19">
    <name />
  </text>
  <text ewd="SYS039" code="FA" type="gp" figID="20">
    <name />
  </text>
  <text ewd="SYS039" code="FB" type="gp" figID="18">
    <name />
  </text>
  <text ewd="SYS039" code="FC" type="gp" figID="17">
    <name />
  </text>
  <text ewd="SYS039" code="1" type="rb" figID="4">
    <name />
  </text>
  <text ewd="SYS039" code="FUSE55" type="rb" figID="3">
    <name>50A AM2</name>
  </text>
  <text ewd="SYS039" code="FUSE3" type="rb" figID="1">
    <name>7.5A ST</name>
  </text>
  <text ewd="SYS039" code="SP3" type="sp" figID="23">
    <name />
  </text>
  <text ewd="SYS039" code="SP4" type="sp" figID="22">
    <name />
  </text>
  <text ewd="SYS039" code="AI3" type="w2w" figID="16">
    <name>Engine Room Main Wire and Cowl Wire</name>
  </text>
  <text ewd="SYS039" code="AC1" type="w2w" figID="15">
    <name>Engine Room Main Wire and Engine Wire</name>
  </text>
</EwdTree>

=== randokuruza70/manual/manual/ewd/contents/tree/201701/models/VDJ76R-RKMNYQ/tree-SYS004.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE EwdTree SYSTEM "../../../../../dtd/ewdtree.dtd">
<EwdTree ver="2.1.2.9" pubno="EM25T2E" xml:lang="en">
  <text ewd="SYS004" code="L45" type="conn" figID="9">
    <name>Antenna Switch Assembly</name>
  </text>
  <text ewd="SYS004" code="A10" type="conn" figID="10">
    <name>Antenna with Holder Assembly</name>
  </text>
  <text ewd="SYS004" code="I49" type="conn" figID="16">
    <name>Motor Antenna Control Relay</name>
  </text>
  <text ewd="SYS004" code="I61,I72" type="conn" figID="7">
    <name>No. 11 Junction Connector , No. 21 Junction Connector</name>
  </text>
  <text ewd="SYS004" code="I108,I109" type="conn" figID="2">
    <name>No. 13 Junction Connector</name>
  </text>
  <text ewd="SYS004" code="I95" type="conn" figID="6">
    <name>No. 18 Junction Connector</name>
  </text>
  <text ewd="SYS004" code="I72" type="conn" figID="15">
    <name>No. 21 Junction Connector</name>
  </text>
  <text ewd="SYS004" code="L34,L35" type="conn" figID="12">
    <name>No. 26 Junction Connector , No. 27 Junction Connector</name>
  </text>
  <text ewd="SYS004" code="I110" type="conn" figID="8">
    <name>No. 33 Junction Connector</name>
  </text>
  <text ewd="SYS004" code="I117" type="conn" figID="14">
    <name>No. 35 Junction Connector</name>
  </text>
  <text ewd="SYS004" code="I93" type="conn" figID="11">
    <name>No. 5 Junction Connector</name>
  </text>
  <text ewd="SYS004" code="I105" type="conn" figID="1">
    <name>No. 8 Junction Connector</name>
  </text>
  <text ewd="SYS004" code="L42" type="conn" figID="13">
    <name>Radio Receiver Assembly</name>
  </text>
  <text ewd="SYS004" code="FUSE6" type="fuse" figID="55">
    <name>10A ECU-B</name>
  </text>
  <text ewd="SYS004" code="FUSE20" type="fuse" figID="56">
    <name>15A ECU IG</name>
  </text>
  <text ewd="SYS004" code="FUSE1" type="fuse" figID="54">
    <name>7.5A ACC</name>
  </text>
  <text ewd="SYS004" code="IA" type="gp" figID="46">
    <name />
  </text>
  <text ewd="SYS004" code="IE" type="gp" figID="44">
    <name />
  </text>
  <text ewd="SYS004" code="IG" type="gp" figID="45">
    <name />
  </text>
  <text ewd="SYS004" code="LA" type="gp" figID="47">
    <name />
  </text>
  <text ewd="SYS004" code="FUSE6" type="rb" figID="4">
    <name>10A ECU-B</name>
  </text>
  <text ewd="SYS004" code="FUSE20" type="rb" figID="5">
    <name>15A ECU IG</name>
  </text>
  <text ewd="SYS004" code="FUSE1" type="rb" figID="3">
    <name>7.5A ACC</name>
  </text>
  <text ewd="SYS004" code="SP44" type="sp" figID="52">
    <name />
  </text>
  <text ewd="SYS004" code="SP54" type="sp" figID="49">
    <name />
  </text>
  <text ewd="SYS004" code="SP76" type="sp" figID="48">
    <name />
  </text>
  <text ewd="SYS004" code="SP81" type="sp" figID="53">
    <name />
  </text>
  <text ewd="SYS004" code="SP126" type="sp" figID="50">
    <name />
  </text>
  <text ewd="SYS004" code="SP127" type="sp" figID="51">
    <name />
  </text>
  <text ewd="SYS004" code="IL1" type="w2w" figID="36,41,43">
    <name>Cowl Wire and Instrument Panel Wire</name>
  </text>
  <text ewd="SYS004" code="IL5" type="w2w" figID="35,40,42">
    <name>Cowl Wire and Instrument Panel Wire</name>
  </text>
  <text ewd="SYS004" code="AI3" type="w2w" figID="20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,37,38,39">
    <name>Engine Room Main Wire and Cowl Wire</name>
  </text>
</EwdTree>
