=== randokuruza70/manual/manual/ewd/dtd/parts.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- #  DTD VERSION 1.7  UPDATE Dec. 04, 2014    -->
<!ELEMENT tmc-service-parts (pub)>
<!ELEMENT pub (term+)>
<!ATTLIST pub
	id ID #REQUIRED
	type (RM | NM | EM | BM) #REQUIRED
>
<!ELEMENT term (parts*)>
<!ATTLIST term
	term-id-from CDATA #REQUIRED
>
<!ELEMENT parts (name, location+)>
<!ATTLIST parts
	parts-id CDATA #REQUIRED
	p-type CDATA #REQUIRED
>
<!ELEMENT name (#PCDATA)>
<!ELEMENT location EMPTY>
<!ATTLIST location
	toc-type CDATA #REQUIRED
	section-id CDATA #REQUIRED
	ttl-id CDATA #REQUIRED
	ncf-para-category CDATA #IMPLIED
	para-id CDATA #IMPLIED
	sub-para-id CDATA #IMPLIED
	step-id CDATA #IMPLIED
	linkkey CDATA #IMPLIED
>

=== randokuruza70/manual/manual/ewd/control/parts.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE tmc-service-parts SYSTEM "../dtd/parts.dtd">
<tmc-service-parts>
  <pub id="EM25T0E" type="EM">
    <term term-id-from="001">
      <parts parts-id="11301K" p-type="1">
        <name> </name>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS022" linkkey="ewd_type=system;ewd=SYS022;type=c,c;code=C42,C68"/>
        <location toc-type="ttl" section-id="_IN" ttl-id="_SYS080" linkkey="ewd_type=system;ewd=SYS080;type=c;code=C42"/>
        <location toc-type="ttl" section-id="_IN" ttl-id="_SYS088" linkkey="ewd_type=system;ewd=SYS088;type=c;code=C42"/>
      </parts>
      <parts parts-id="11301M" p-type="1">
        <name> </name>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS020" linkkey="ewd_type=system;ewd=SYS020;type=c,c;code=C22,C24"/>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS028" linkkey="ewd_type=system;ewd=SYS028;type=c,c;code=C22,C24"/>
      </parts>
      <parts parts-id="11401G" p-type="1">
        <name> </name>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS020" linkkey="ewd_type=system;ewd=SYS020;type=c;code=C2"/>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS028" linkkey="ewd_type=system;ewd=SYS028;type=c;code=C2"/>
        <location toc-type="ttl" section-id="_IN" ttl-id="_SYS080" linkkey="ewd_type=system;ewd=SYS080;type=c;code=C2"/>
        <location toc-type="ttl" section-id="_IN" ttl-id="_SYS088" linkkey="ewd_type=system;ewd=SYS088;type=c;code=C2"/>
      </parts>
      <parts parts-id="15330B" p-type="1">
        <name> </name>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS020" linkkey="ewd_type=system;ewd=SYS020;type=c;code=C27"/>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS028" linkkey="ewd_type=system;ewd=SYS028;type=c;code=C27"/>
      </parts>
      <parts parts-id="15340" p-type="1">
        <name> </name>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS020" linkkey="ewd_type=system;ewd=SYS020;type=c;code=C26"/>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS028" linkkey="ewd_type=system;ewd=SYS028;type=c;code=C26"/>
      </parts>
      <parts parts-id="17650" p-type="1">
        <name> </name>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS018" linkkey="ewd_type=system;ewd=SYS018;type=c,c;code=C92,C94"/>
      </parts>
      <parts parts-id="19500" p-type="1">
        <name> </name>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS034" linkkey="ewd_type=system;ewd=SYS034;type=c,c,c,c,c,c;code=C5,C6,C7,C12,C13,C14"/>
      </parts>
      <parts parts-id="19850" p-type="1">
        <name> </name>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS018" linkkey="ewd_type=system;ewd=SYS018;type=c;code=C90"/>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS022" linkkey="ewd_type=system;ewd=SYS022;type=c,c;code=C45,C62"/>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS032" linkkey="ewd_type=system;ewd=SYS032;type=c;code=C90"/>
      </parts>
      <parts parts-id="22030" p-type="1">
        <name> </name>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS020" linkkey="ewd_type=system;ewd=SYS020;type=c;code=C4"/>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS028" linkkey="ewd_type=system;ewd=SYS028;type=c;code=C4"/>
      </parts>
      <parts parts-id="22100" p-type="1">
        <name> </name>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS018" linkkey="ewd_type=system;ewd=SYS018;type=c,c;code=C83,C84"/>
        <location toc-type="ttl" section-id="_IN" ttl-id="_SYS088" linkkey="ewd_type=system;ewd=SYS088;type=c;code=C83"/>
      </parts>
      <parts parts-id="22204" p-type="1">
        <name> </name>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS020" linkkey="ewd_type=system;ewd=SYS020;type=c;code=C3"/>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS022" linkkey="ewd_type=system;ewd=SYS022;type=c;code=C41"/>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS028" linkkey="ewd_type=system;ewd=SYS028;type=c;code=C3"/>
      </parts>
      <parts parts-id="23221" p-type="1">
        <name> </name>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS020" linkkey="ewd_type=system;ewd=SYS020;type=c,c,c,c;code=C31,T3,T8,X2"/>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS028" linkkey="ewd_type=system;ewd=SYS028;type=c,c,c,c;code=C31,T3,T8,X2"/>
      </parts>
      <parts parts-id="23250" p-type="1">
        <name> </name>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS020" linkkey="ewd_type=system;ewd=SYS020;type=c,c,c,c,c,c;code=C8,C9,C11,C16,C20,C25"/>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS028" linkkey="ewd_type=system;ewd=SYS028;type=c,c,c,c,c,c;code=C8,C9,C11,C16,C20,C25"/>
      </parts>
      <parts parts-id="23670" p-type="1">
        <name> </name>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS022" linkkey="ewd_type=system;ewd=SYS022;type=c,c,c,c,c,c,c,c;code=C48,C49,C51,C57,C63,C64,C67,C72"/>
      </parts>
      <parts parts-id="25620" p-type="1">
        <name> </name>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS022" linkkey="ewd_type=system;ewd=SYS022;type=c;code=C47"/>
      </parts>
      <parts parts-id="25630" p-type="1">
        <name> </name>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS022" linkkey="ewd_type=system;ewd=SYS022;type=c;code=C66"/>
      </parts>
      <parts parts-id="25850" p-type="1">
        <name> </name>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS018" linkkey="ewd_type=system;ewd=SYS018;type=c;code=C91"/>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS022" linkkey="ewd_type=system;ewd=SYS022;type=c;code=C91"/>
      </parts>
      <parts parts-id="25860" p-type="1">
        <name> </name>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS020" linkkey="ewd_type=system;ewd=SYS020;type=c,c;code=C15,C37"/>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS028" linkkey="ewd_type=system;ewd=SYS028;type=c,c;code=C15,C37"/>
      </parts>
      <parts parts-id="25860A" p-type="1">
        <name> </name>
        <location toc-type="ttl" section-id="_IN" ttl-id="_SYS082" linkkey="ewd_type=system;ewd=SYS082;type=c;code=A18"/>
      </parts>
      <parts parts-id="26100G" p-type="1">
        <name> </name>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS022" linkkey="ewd_type=system;ewd=SYS022;type=c,c,c,c;code=C50,C58,C61,C65"/>
      </parts>
      <parts parts-id="27020" p-type="1">
        <name> </name>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS022" linkkey="ewd_type=system;ewd=SYS022;type=c;code=C44"/>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS032" linkkey="ewd_type=system;ewd=SYS032;type=c;code=I34"/>
        <location toc-type="ttl" section-id="_PS" ttl-id="_SYS118" linkkey="ewd_type=system;ewd=SYS118;type=c,c;code=D1,D4"/>
        <location toc-type="ttl" section-id="_PS" ttl-id="_SYS120" linkkey="ewd_type=system;ewd=SYS120;type=c,c;code=I1,I34"/>
        <location toc-type="ttl" section-id="_PS" ttl-id="_SYS122" linkkey="ewd_type=system;ewd=SYS122;type=c,c;code=C43,C44"/>
      </parts>
      <parts parts-id="28100" p-type="1">
        <name> </name>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS036" linkkey="ewd_type=system;ewd=SYS036;type=c,c,c,c;code=D2,D3,D6,D7"/>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS038" linkkey="ewd_type=system;ewd=SYS038;type=c,c;code=C89,D5"/>
      </parts>
      <parts parts-id="28520" p-type="1">
        <name> </name>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS032" linkkey="ewd_type=system;ewd=SYS032;type=c;code=I42"/>
      </parts>
      <parts parts-id="28800" p-type="1">
        <name> </name>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS036" linkkey="ewd_type=system;ewd=SYS036;type=c,c,c;code=A36,D8,D9"/>
        <location toc-type="ttl" section-id="_EG" ttl-id="_SYS038" linkkey="ewd_type=system;ewd=SYS038;type=c,c,c,c,c,c,c,c,c;code=A36,D8,D10,E1,E2,E3,E4,F1,F2"/>
        <location toc-type="ttl" section-id="_EX" ttl-id="_SYS078" linkkey="ewd_type=system;ewd=SYS078;type=c,c,c,c,c,c,c;code=A36,D9,E1,E2,F1,F2,k2"/>
        <location toc-type="ttl" section-id="_PS" ttl-id="_SYS118" linkkey="ewd_type=system;ewd=SYS118;type=c,c,c;code=A35,A36,D9"/>
        <location toc-type="ttl" section-id="_PS" ttl-id="_SYS120" linkkey="ewd_type=system;ewd=SYS120;type=c,c,c,c,c,c,c,c,c;code=A35,A36,A37,E1,E2,E3,E4,F1,F2"/>
        <location toc-type="ttl" section-id="_PS" ttl-id="_SYS122" linkkey="ewd_type=system;ewd=SYS122;type=c,c,c;code=A35,A36,D9"/>
        <location toc-type="ttl" section-id="_PS" ttl-id="_SYS128" linkkey="ewd_type=system;ewd=SYS128;type=c,c,c,c,c,c,c,c,c,c;code=A35,A36,A37,D9,E1,E2,E3,E4,F1,F2"/>
        <location toc-type="ttl" section-id="_PS" ttl-id="_SYS130" linkkey="ewd_type=system;ewd=SYS130;type=c,c,c;code=A35,A36,D9"/>
      </parts>
      <parts parts-id="38110" p-type="1">
        <name> </name>
        <location toc-type="ttl" section-id="_EX" ttl-id="_SYS078" linkkey="ewd_type=system;ewd=SYS078;type=c;code=s1"/>
      </parts>
      <parts parts-id="38600A" p-type="1">
        <name> </name>
        <location toc-type="ttl" section-id="_EX" ttl-id="_SYS078" linkkey="ewd_type=system;ewd=SYS078;type=c,c,c,c;code=m1,m2,s2,t1"/>
      </parts>
      <parts parts-id="38630" p-type="1">
        <name> </name>
        <location toc-type="ttl" section-id="_EX" ttl-id="_SYS078" linkkey="ewd_type=system;ewd=SYS078;type=c,c,c;code=k1,m3,m4"/>
      </parts>
      <parts parts-id="41450" p-type="1">
        <name> </name>
        <location toc-type="ttl" section-id="_DR" ttl-id="_SYS015" linkkey="ewd_type=system;ewd=SYS015;type=c;code=V2"/>
      </parts>
