=== randokuruza70/manual/manual/brm/dtd/paragraph-contents.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- #  DTD VERSION 1.7  UPDATE Dec. 04, 2014    -->
<!ELEMENT tmc-service-paragraph (pub)>
<!ELEMENT pub (servcat)>
<!ATTLIST pub
	id CDATA #REQUIRED
>
<!ELEMENT servcat (name, section)>
<!ATTLIST servcat
	id CDATA #REQUIRED
>
<!ELEMENT section (name, ttl)>
<!ATTLIST section
	id CDATA #REQUIRED
>
<!ELEMENT ttl (name, para)>
<!ATTLIST ttl
	id CDATA #REQUIRED
>
<!ELEMENT para (((name, ncf-para?) | (dtccode, dtcname)*), subpara+)>
<!ATTLIST para
	category CDATA #REQUIRED
	id ID #REQUIRED
>
<!ELEMENT ncf-para (name)>
<!ATTLIST ncf-para
	ncf-para-category CDATA #REQUIRED
>
<!ELEMENT subpara (name?, s-1*, content2*, content3*, content4*, content5*, testgrp*)>
<!ATTLIST subpara
	id ID #REQUIRED
	category CDATA #REQUIRED
>
<!ELEMENT name (#PCDATA)>
<!ELEMENT dtcname (#PCDATA)>
<!ELEMENT dtccode (#PCDATA)>
<!ELEMENT action (actiontitle, content6?)?>
<!ATTLIST action
	actiontype (next | end | jump) #REQUIRED
	cellposition CDATA #IMPLIED
	childid CDATA #IMPLIED
>
<!ELEMENT actiontitle (#PCDATA)>
<!ELEMENT atten2 (title?, (figure | ptxt | list1 | table)+)>
<!ELEMENT atten3 (title?, (figure | ptxt | list1 | table)+)>
<!ELEMENT atten4 (title?, (figure | ptxt | list1 | table)+)>
<!ELEMENT callout (table)>
<!ELEMENT colspec EMPTY>
<!ATTLIST colspec
	align (left | right | center) #IMPLIED
	colname NMTOKEN #IMPLIED
	colnum NMTOKEN #IMPLIED
	colsep NMTOKEN #IMPLIED
	colwidth CDATA #IMPLIED
	rowsep NMTOKEN #IMPLIED
>
<!ELEMENT content1 ((ptxt | list1 | spec | figure | table | atten2 | atten3 | atten4 | torque | sst | gts-info)*, s2*)>
<!ELEMENT content2 (title?, (ptxt | figure | atten2 | atten3 | atten4)*)>
<!ELEMENT content3 (title?, (ptxt | list1 | spec | figure | table | atten2 | atten3 | atten4 | torque | sst | gts-info)*)>
<!ELEMENT content4 (title?, (table | atten2 | atten3 | atten4)*)>
<!ELEMENT content5 (title?, (ptxt | step1 | list1 | spec | figure | table | atten2 | atten3 | atten4 | torque | sst | topic | gts-info)*)>
<!ELEMENT content6 (title?, (spec | sst | torque | atten2 | atten3 | atten4 | figure | list1 | table | test1 | ptxt | gts-info)*)>
<!ELEMENT convertitem (c-value1*, c-value2*, c-value3*)>
<!ATTLIST convertitem
	point1 CDATA #REQUIRED
	point2 CDATA #IMPLIED
	style CDATA #REQUIRED
	unit CDATA #REQUIRED
>
<!ELEMENT c-value1 (#PCDATA)>
<!ATTLIST c-value1
	type CDATA #REQUIRED
	unit CDATA #REQUIRED
>
<!ELEMENT c-value2 (#PCDATA)>
<!ATTLIST c-value2
	type CDATA #REQUIRED
	unit CDATA #REQUIRED
>
<!ELEMENT c-value3 (#PCDATA)>
<!ATTLIST c-value3
	type CDATA #REQUIRED
	unit CDATA #REQUIRED
>
<!ELEMENT data-name (ptxt | list1 | mlink | torque | graphic | atten2 | atten3 | atten4)*>
<!ATTLIST data-name
	args1 CDATA #IMPLIED
	name CDATA #REQUIRED
	parts-id CDATA #IMPLIED
>
<!ELEMENT entry (data-name | (title?, (ptxt | list1 | atten2 | atten3 | atten4 | graphic | judge-value)*))>
<!ATTLIST entry
	align (left | right | center) #IMPLIED
	colname NMTOKEN #IMPLIED
	colsep NMTOKEN #IMPLIED
	morerows NMTOKEN #IMPLIED
	nameend NMTOKEN #IMPLIED
	namest NMTOKEN #IMPLIED
	rowsep NMTOKEN #IMPLIED
	valign (top | middle | bottom) #IMPLIED
>
<!ELEMENT figure (title?, graphic+, callout?, footnote?)>
<!ATTLIST figure
	translate CDATA #IMPLIED
	type CDATA #IMPLIED
>
<!ELEMENT footnote (ptxt)+>
<!ELEMENT graphic EMPTY>
<!ATTLIST graphic
	graphicname CDATA #REQUIRED
	height CDATA #REQUIRED
	width CDATA #REQUIRED
>
<!ELEMENT item (ptxt | figure | table | spec | atten2 | atten3 | atten4)+>
<!ATTLIST item
	label CDATA #IMPLIED
>
<!ELEMENT judge-value (ptxt)>
<!ATTLIST judge-value
	label CDATA #IMPLIED
>
<!ELEMENT list1 (title?, figure*, item, (item | list2)*)>
<!ATTLIST list1
	type (ordered | unordered | nonmark) #IMPLIED
>
<!ELEMENT list2 (title?, figure*, item, (item | list3)*)>
<!ATTLIST list2
	type (ordered | unordered | nonmark) #IMPLIED
>
<!ELEMENT list3 (title?, figure*, item+)>
<!ATTLIST list3
	type (ordered | unordered | nonmark) #IMPLIED
>
<!ELEMENT mlink (xref+)>
<!ELEMENT ptxt (#PCDATA | sub | sup | mlink)*>
<!ELEMENT result (action)>
<!ATTLIST result
	cellposition CDATA #IMPLIED
	label CDATA #IMPLIED
>
<!ELEMENT results (result+)>
<!ELEMENT row (entry+)>
<!ATTLIST row
	rowsep NMTOKEN #IMPLIED
>
<!ELEMENT s-1 (ptxt+, content1*)>
<!ATTLIST s-1
	id ID #REQUIRED
>
<!ELEMENT s2 ((ptxt | list1 | spec | figure | table | atten2 | atten3 | atten4 | torque | sst | gts-info)*, s3*)>
<!ATTLIST s2
	label CDATA #IMPLIED
>
<!ELEMENT s3 ((ptxt | list1 | spec | figure | table | atten2 | atten3 | atten4 | torque | sst | gts-info)*)>
<!ATTLIST s3
	label CDATA #IMPLIED
>
<!ELEMENT s-number (#PCDATA)>
<!ELEMENT spec (title, (table | (subtitle* | specitem)+)+)>
<!ATTLIST spec
	type (current | resistance | voltage | other) #REQUIRED
>
<!ELEMENT specitem (ptxt)+>
<!ELEMENT sst (sstitem+)>
<!ELEMENT sstitem (s-number+, s-subnumber*, ptxt?)+>
<!ELEMENT s-subnumber (#PCDATA)>
<!ELEMENT step1 ((ptxt | list1 | spec | figure | table | atten2 | atten3 | atten4 | torque | sst | gts-info)*, step2*)>
<!ATTLIST step1
	label CDATA #IMPLIED
>
<!ELEMENT step2 ((ptxt | list1 | spec | figure | table | atten2 | atten3 | atten4 | torque | sst | gts-info)*, step3*)>
<!ATTLIST step2
	label CDATA #IMPLIED
>
<!ELEMENT step3 ((ptxt | list1 | spec | figure | table | atten2 | atten3 | atten4 | torque | sst | gts-info)*)>
<!ATTLIST step3
	label CDATA #IMPLIED
>
<!ELEMENT sub (#PCDATA)>
<!ELEMENT subtitle (#PCDATA)>
<!ELEMENT sup (#PCDATA)>
<!ELEMENT table (title?, (ptxt)*, tgroup+, footnote?)>
<!ATTLIST table
	colsep NMTOKEN #IMPLIED
	frame (all | none) #IMPLIED
	pgwide NMTOKEN #IMPLIED
	rowsep NMTOKEN #IMPLIED
	type (dtc-table | dtc-explan-table | tool-table | symptom-table | caption-table | torque-specification-table | freeze-frame | data-list | data-list-table | active-test | active-test-table | utility | utility-table | customize | multi-list) #IMPLIED
>
<!ELEMENT tbody (row+)>
<!ATTLIST tbody
	valign (top | middle | bottom) #IMPLIED
>
<!ELEMENT test1 (ptxt, (ptxt | spec | atten2 | atten3 | atten4 | figure | list1 | table | gts-info)*, test2*)>
<!ATTLIST test1
	id ID #IMPLIED
	label CDATA #IMPLIED
>
<!ELEMENT test2 (ptxt, (ptxt | spec | atten2 | atten3 | atten4 | figure | list1 | table | gts-info)*)>
<!ATTLIST test2
	id ID #IMPLIED
	label CDATA #IMPLIED
>
<!ELEMENT testgrp (testtitle, content6*, results?)>
<!ATTLIST testgrp
	cellposition CDATA #IMPLIED
	id ID #REQUIRED
>
<!ELEMENT testtitle (#PCDATA)*>
<!ELEMENT tgroup (colspec*, thead?, tbody)>
<!ATTLIST tgroup
	align (left | right | center) #IMPLIED
	cols NMTOKEN #REQUIRED
	colsep NMTOKEN #IMPLIED
	rowsep NMTOKEN #IMPLIED
>
<!ELEMENT thead (colspec*, row+)>
<!ATTLIST thead
	valign (top | middle | bottom) #IMPLIED
>
<!ELEMENT title (#PCDATA)>
<!ATTLIST title
	date CDATA #IMPLIED
>
<!ELEMENT topic (title?, (ptxt | list1 | spec | figure | table | atten2 | atten3 | atten4 | torque | sst)*)>
<!ATTLIST topic
	id ID #IMPLIED
>
<!ELEMENT torque (subtitle?, convertitem, ptxt*)+>
<!ELEMENT xref EMPTY>
<!ATTLIST xref
	href CDATA #REQUIRED
	label CDATA #IMPLIED
	refid CDATA #IMPLIED
	term-id-from CDATA #REQUIRED
	term-id-to CDATA #IMPLIED
>
<!ELEMENT gts-info (title, ((table+, title?, table?, gts-exec?, app-communication) | (gts-exec, app-communication)))>
<!ATTLIST gts-info
	category CDATA #IMPLIED
>
<!ELEMENT gts-cust EMPTY>
<!ATTLIST gts-cust
	cust-id CDATA #REQUIRED
>
<!ELEMENT gts-did EMPTY>
<!ATTLIST gts-did
	did-id CDATA #REQUIRED
>
<!ELEMENT gts-ecu (gts-did?, gts-pid*, gts-util?)?>
<!ATTLIST gts-ecu
	ecu-id CDATA #REQUIRED
>
<!ELEMENT gts-exec ((gts-ecu* | gts-cust*), gts-2nd-ecu?)>
<!ATTLIST gts-exec
	function-id CDATA #REQUIRED
>
<!ELEMENT gts-pid EMPTY>
<!ATTLIST gts-pid
	pid-id CDATA #REQUIRED
>
<!ELEMENT gts-util EMPTY>
<!ATTLIST gts-util
	util-id CDATA #REQUIRED
>
<!ELEMENT gts-2nd-ecu (gts-2nd-pid*, gts-multi)?>
<!ATTLIST gts-2nd-ecu
	ecu-id CDATA #REQUIRED
>
<!ELEMENT gts-2nd-pid EMPTY>
<!ATTLIST gts-2nd-pid
	pid-id CDATA #REQUIRED
>
<!ELEMENT gts-multi EMPTY>
<!ATTLIST gts-multi
	multi-mode CDATA #REQUIRED
>
<!ELEMENT app-param (#PCDATA)*>
<!ATTLIST app-param
	name CDATA #REQUIRED
>
<!ELEMENT app-communication (app-param-unit | app-param)*>
<!ELEMENT app-param-unit (app-param+)>

=== randokuruza70/manual/manual/repair/contents/xml/RM1000000012NTY.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tmc-service-paragraph SYSTEM "../dtd/paragraph-contents.dtd">
<tmc-service-paragraph><pub id="RM25T0E"><servcat id="_53"><name>Suspension</name><section id="_062777"><name>TIRE PRESSURE MONITORING</name><ttl id="_0306275"><name>TIRE PRESSURE WARNING SYSTEM</name><para id="RM1000000012NTY" category="C"><dtccode>C2198/98</dtccode><dtcname>Initialization Switch (for Test Mode DTC)</dtcname><subpara id="RM1000000012NTY_02" category="03"><name>DESCRIPTION</name><content5><ptxt>During test mode, when the tire pressure warning reset switch is on, the tire pressure warning light comes on and when the tire pressure warning reset switch is off, the tire pressure warning light blinks at 0.125 second intervals.</ptxt><table type="dtc-explan-table" pgwide="1"><tgroup cols="4"><colspec colname="1" colwidth="1.06in"/><colspec colname="2" colwidth="1.42in"/><colspec colname="3" colwidth="2.12in"/><colspec colname="4" colwidth="2.48in"/><thead><row><entry align="center" valign="middle"><ptxt>DTC No.</ptxt></entry><entry align="center" valign="middle"><ptxt>Detection Item</ptxt></entry><entry align="center" valign="middle"><ptxt>DTC Detection Condition</ptxt></entry><entry align="center" valign="middle"><ptxt>Trouble Area</ptxt></entry></row></thead><tbody><row><entry align="left" valign="middle"><data-name name="dtc-code"><ptxt>C2198/98</ptxt></data-name></entry><entry align="left" valign="middle"><data-name name="detect-item"><ptxt>Initialization Switch (for Test Mode DTC)</ptxt></data-name></entry><entry align="left" valign="middle"><data-name name="dtc-detect-cond"><ptxt>Test mode procedure is performed.</ptxt></data-name></entry><entry align="left" valign="middle"><data-name name="trouble-area"><list1 type="unordered"><item><ptxt>Tire pressure warning reset switch</ptxt></item><item><ptxt>Wire harness or connector</ptxt></item><item><ptxt>Tire pressure warning ECU and receiver</ptxt></item></list1></data-name></entry></row></tbody></tgroup></table></content5></subpara><subpara id="RM1000000012NTY_03" category="03"><name>WIRING DIAGRAM</name><content5><figure type="1" translate="E"><graphic graphicname="C249283E44" width="7.168479331in" height="3.812598425in"/></figure></content5></subpara><subpara id="RM1000000012NTY_04" category="10"><name>CAUTION / NOTICE / HINT</name><content5><atten3><list1 type="unordered"><item><ptxt>When replacing the tire pressure warning ECU and receiver, read the transmitter IDs stored in the old ECU using the GTS and write them down before removal.</ptxt></item><item><ptxt>It is necessary to perform initialization <mlink><xref label="Seep00001" term-id-from="003" href="RM1000000012NUB"/></mlink> after registration <mlink><xref label="Seep00002" term-id-from="003" href="RM1000000012NUA"/></mlink> of the transmitter IDs into the tire pressure warning ECU and receiver if the ECU has been replaced.</ptxt></item></list1></atten3></content5></subpara><subpara id="RM1000000012NTY_01" category="01"><name>PROCEDURE</name><testgrp id="RM1000000012NTY_01_0001" cellposition="1-1"><testtitle>INSPECT TIRE PRESSURE WARNING RESET SWITCH</testtitle><content6><test1><ptxt>Turn the ignition switch off.</ptxt></test1><test1><ptxt>Remove the tire pressure warning reset switch.</ptxt><ptxt>Click here<mlink><xref label="Seep00001" term-id-from="003" href="RM1000000013GKP"/></mlink></ptxt></test1><test1><ptxt>Inspect the tire pressure warning reset switch.</ptxt><ptxt>Click here<mlink><xref label="Seep00002" term-id-from="003" href="RM1000000013GKN"/></mlink></ptxt></test1><spec type="other"><title>Result</title><table><tgroup cols="1"><colspec colname="col1" colwidth="4.13in"/><thead><row><entry align="center"><ptxt>Proceed to</ptxt></entry></row></thead><tbody><row><entry align="center"><judge-value label="1"><ptxt>OK</ptxt></judge-value></entry></row><row><entry align="center"><judge-value label="2"><ptxt>NG</ptxt></judge-value></entry></row></tbody></tgroup></table></spec></content6><results><result label="1" cellposition="1-1"><action actiontype="next" cellposition="2-1" childid="RM1000000012NTY_01_0002"/></result><result label="2" cellposition="1-3"><action actiontype="end" cellposition="2-3"><actiontitle>REPLACE TIRE PRESSURE WARNING RESET SWITCH</actiontitle><content6><ptxt>Click here<mlink><xref label="Seep00001" term-id-from="003" href="RM1000000013GKP"/></mlink></ptxt></content6></action></result></results></testgrp><testgrp id="RM1000000012NTY_01_0002" cellposition="2-1"><testtitle>CHECK HARNESS AND CONNECTOR (TIRE PRESSURE WARNING RESET SWITCH - TIRE PRESSURE WARNING ECU AND RECEIVER)</testtitle><content6><test1><ptxt>Disconnect the L56 tire pressure warning reset switch connector.</ptxt></test1><test1><ptxt>Disconnect the S30*1, Y7*2 or U5*3 tire pressure warning ECU and receiver connector.</ptxt><list1 type="nonmark"><item><ptxt>*1: for Single Cab</ptxt></item><item><ptxt>*2: for Double Cab</ptxt></item><item><ptxt>*3: except Single and Double Cabs</ptxt></item></list1></test1><test1><ptxt>Measure the resistance according to the value(s) in the table below.</ptxt><spec type="resistance"><title>Standard Resistance</title><table><tgroup cols="3"><colspec colname="col1" colwidth="1.65in"/><colspec colname="col2" colwidth="1.03in"/><colspec colname="col3" colwidth="1.45in"/><thead><row><entry valign="middle" align="center"><ptxt>Tester Connection</ptxt></entry><entry valign="middle" align="center"><ptxt>Condition</ptxt></entry><entry valign="middle" align="center"><ptxt>Specified Condition</ptxt></entry></row></thead><tbody><row><entry valign="middle" align="center"><ptxt>S30-7 (CLSW) - L56-1 (INT)*1</ptxt><ptxt>Y7-7 (CLSW) - L56-1 (INT)*2</ptxt><ptxt>U5-7 (CLSW) - L56-1 (INT)*3</ptxt></entry><entry valign="middle" align="center"><ptxt>Always</ptxt></entry><entry valign="middle" align="center"><ptxt>Below 1 Ω</ptxt></entry></row><row><entry valign="middle" align="center"><ptxt>S30-7 (CLSW) or L56-1 (INT) - Body ground*1</ptxt><ptxt>Y7-7 (CLSW) or L56-1 (INT) - Body ground*2</ptxt><ptxt>U5-7 (CLSW) or L56-1 (INT) - Body ground*3</ptxt></entry><entry valign="middle" align="center"><ptxt>Always</ptxt></entry><entry valign="middle" align="center"><ptxt>10 kΩ or higher</ptxt></entry></row><row><entry valign="middle" align="center"><ptxt>L56-2 (E) - Body ground</ptxt></entry><entry valign="middle" align="center"><ptxt>Always</ptxt></entry><entry valign="middle" align="center"><ptxt>Below 1 Ω</ptxt></entry></row></tbody></tgroup></table></spec><list1 type="nonmark"><item><ptxt>*1: for Single Cab</ptxt></item><item><ptxt>*2: for Double Cab</ptxt></item><item><ptxt>*3: except Single and Double Cabs</ptxt></item></list1><spec type="other"><title>Result</title><table><tgroup cols="1"><colspec colname="col1" colwidth="4.13in"/><thead><row><entry align="center" valign="middle"><ptxt>Proceed to</ptxt></entry></row></thead><tbody><row><entry align="center" valign="middle"><judge-value label="1"><ptxt>OK</ptxt></judge-value></entry></row><row><entry align="center" valign="middle"><judge-value label="2"><ptxt>NG</ptxt></judge-value></entry></row></tbody></tgroup></table></spec></test1></content6><results><result label="1" cellposition="2-1"><action actiontype="end" cellposition="3-1"><actiontitle>REPLACE TIRE PRESSURE WARNING ECU AND RECEIVER</actiontitle><content6><ptxt>for Single Cab: Click here<mlink><xref label="Seep00001" term-id-from="003" href="RM1000000013GKS"/></mlink></ptxt><ptxt>for Double Cab: Click here<mlink><xref label="Seep00002" term-id-from="003" href="RM1000000013GKS"/></mlink></ptxt><ptxt>for Short Body: Click here<mlink><xref label="Seep00003" term-id-from="003" href="RM1000000013GKK"/></mlink></ptxt><ptxt>for Long Body: Click here<mlink><xref label="Seep00004" term-id-from="003" href="RM1000000013GKW"/></mlink></ptxt><ptxt>for Semi-long Body: Click here<mlink><xref label="Seep00005" term-id-from="003" href="RM1000000013GKZ"/></mlink></ptxt></content6></action></result><result label="2" cellposition="2-2"><action actiontype="end" cellposition="3-2"><actiontitle>REPAIR OR REPLACE HARNESS OR CONNECTOR</actiontitle><content6/></action></result></results></testgrp></subpara></para></ttl></section></servcat></pub></tmc-service-paragraph>

=== randokuruza70/manual/manual/repair/contents/xml/RM100000000FWAL.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tmc-service-paragraph SYSTEM "../dtd/paragraph-contents.dtd">
<tmc-service-paragraph><pub id="RM25T0E"><servcat id="_58"><name>Vehicle Interior</name><section id="_029925"><name>THEFT DETERRENT / KEYLESS ENTRY</name><ttl id="_0138323"><name>IMMOBILISER SYSTEM</name><para id="RM100000000FWAL" category="C"><dtccode>B279C</dtccode><dtcname>Theft Deterrent System Presence Detection</dtcname><subpara id="RM100000000FWAL_03" category="03"><name>DESCRIPTION</name><content5><ptxt>If an ECM that is incompatible with the immobiliser system is installed, the ECM stores this DTC.</ptxt><table type="dtc-explan-table" pgwide="1"><tgroup cols="5"><colspec colname="1" colwidth="1.42in"/><colspec colname="2" colwidth="1.42in"/><colspec colname="3" colwidth="1.42in"/><colspec colname="4" colwidth="1.42in"/><colspec colname="5" colwidth="1.40in"/><thead><row><entry align="center" valign="middle"><ptxt>DTC No.</ptxt></entry><entry align="center" valign="middle"><ptxt>Detection Item</ptxt></entry><entry align="center" valign="middle"><ptxt>DTC Detection Condition</ptxt></entry><entry align="center" valign="middle"><ptxt>Trouble Area</ptxt></entry><entry align="center" valign="middle"><ptxt>Note</ptxt></entry></row></thead><tbody><row><entry align="left" valign="middle"><data-name name="dtc-code"><ptxt>B279C</ptxt></data-name></entry><entry align="left" valign="middle"><data-name name="detect-item"><ptxt>Theft Deterrent System Presence Detection</ptxt></data-name></entry><entry align="left" valign="middle"><data-name name="dtc-detect-cond"><ptxt>An ECM that is incompatible with immobiliser system is installed.</ptxt></data-name></entry><entry align="left" valign="middle"><data-name name="trouble-area"><ptxt>ECM</ptxt></data-name></entry><entry align="left" valign="middle"><data-name name="remark"><list1 type="nonmark"><title>DTC Output Confirmation Operation:</title><item><ptxt>Check for DTCs.</ptxt></item></list1></data-name></entry></row></tbody></tgroup></table><table pgwide="1"><title>Vehicle Condition and Fail-safe Operation when Malfunction Detected</title><tgroup cols="2"><colspec colname="COL1" colwidth="3.54in"/><colspec colname="COL2" colwidth="3.54in"/><thead><row><entry align="center" valign="middle"><ptxt>Vehicle Condition when Malfunction Detected</ptxt></entry><entry align="center" valign="middle"><ptxt>Fail-safe Operation when Malfunction Detected</ptxt></entry></row></thead><tbody><row><entry valign="middle" align="center"><ptxt>Engine cannot be started</ptxt></entry><entry align="center" valign="middle"><ptxt>-</ptxt></entry></row></tbody></tgroup></table><table pgwide="1"><title>Related Data List and Active Test</title><tgroup cols="2"><colspec colname="COL1" colwidth="3.54in"/><colspec colname="COL2" colwidth="3.54in"/><thead><row><entry align="center" valign="middle"><ptxt>DTC No.</ptxt></entry><entry align="center" valign="middle"><ptxt>Data List and Active Test</ptxt></entry></row></thead><tbody><row><entry align="center" valign="middle"><ptxt>B279C</ptxt></entry><entry align="center"><ptxt>-</ptxt></entry></row></tbody></tgroup></table></content5></subpara><subpara id="RM100000000FWAL_04" category="10"><name>CAUTION / NOTICE / HINT</name><content5><atten3><list1 type="unordered"><item><ptxt>If the ECM is replaced, refer to Service Bulletin.</ptxt></item><item><ptxt>After repair, confirm that no DTCs are output by performing &quot;DTC Output Confirmation Operation&quot;.</ptxt></item></list1></atten3></content5></subpara><subpara id="RM100000000FWAL_02" category="01"><name>PROCEDURE</name><testgrp id="RM100000000FWAL_02_0005" cellposition="1-1"><testtitle>CLEAR DTC</testtitle><content6><test1><ptxt>Clear the DTCs.</ptxt><gts-info category="dtc-delete"><title>Powertrain &gt; Engine and ECT &gt; Clear DTCs</title><gts-exec function-id="50002"><gts-ecu ecu-id="61"/></gts-exec><app-communication><app-param name="process-mode">0</app-param><app-param name="edit-mode">1</app-param><app-param name="insert-mode">0</app-param><app-param name="function-tab">0</app-param><app-param name="category-div">1</app-param><app-param name="category-div-name">Powertrain</app-param><app-param name="ecu-id">61</app-param><app-param name="ecu-name">Engine and ECT</app-param><app-param name="gts-order">0</app-param><app-param name="selected-state">1</app-param></app-communication></gts-info></test1><spec type="other"><title>Result</title><table><tgroup cols="1"><colspec colname="col1" colwidth="4.13in"/><thead><row><entry align="center" valign="middle"><ptxt>Proceed to</ptxt></entry></row></thead><tbody><row><entry align="center" valign="middle"><judge-value label="1"><ptxt>NEXT</ptxt></judge-value></entry></row></tbody></tgroup></table></spec></content6><results><result label="1" cellposition="1-1"><action actiontype="next" cellposition="2-1" childid="RM100000000FWAL_02_0006"/></result></results></testgrp><testgrp id="RM100000000FWAL_02_0006" cellposition="2-1"><testtitle>CHECK FOR DTC</testtitle><content6><test1><ptxt>Perform &quot;DTC Output Confirmation Operation&quot; procedure.</ptxt></test1><test1><ptxt>Check for DTCs.</ptxt><gts-info category="dtc-read"><title>Powertrain &gt; Engine and ECT &gt; Trouble Codes</title><gts-exec function-id="50001"><gts-ecu ecu-id="61"/></gts-exec><app-communication><app-param name="process-mode">0</app-param><app-param name="edit-mode">1</app-param><app-param name="insert-mode">0</app-param><app-param name="function-tab">0</app-param><app-param name="category-div">1</app-param><app-param name="category-div-name">Powertrain</app-param><app-param name="ecu-id">61</app-param><app-param name="ecu-name">Engine and ECT</app-param><app-param name="gts-order">0</app-param><app-param name="selected-state">0</app-param></app-communication></gts-info><spec type="other"><title>OK</title><specitem><ptxt>DTC B279C is not output.</ptxt></specitem></spec></test1><spec type="other"><title>Result</title><table><tgroup cols="2"><colspec colname="col1" colwidth="2.89in"/><colspec colname="col2" colwidth="1.24in"/><thead><row><entry align="center" valign="middle"><ptxt>Result</ptxt></entry><entry align="center" valign="middle"><ptxt>Proceed to</ptxt></entry></row></thead><tbody><row><entry align="left" valign="middle"><ptxt>DTC B279C is not output</ptxt></entry><entry align="center" valign="middle"><judge-value label="1"><ptxt>A</ptxt></judge-value></entry></row><row><entry align="left"><ptxt>DTC B279C is output</ptxt></entry><entry align="center"><judge-value label="2"><ptxt>B</ptxt></judge-value></entry></row></tbody></tgroup></table></spec></content6><results><result label="1" cellposition="2-1"><action actiontype="end" cellposition="3-1"><actiontitle>USE SIMULATION METHOD TO CHECK</actiontitle><content6><ptxt>Click here<mlink><xref label="Seep00001" term-id-from="001" term-id-to="002" href="RM100000000G4HR"/><xref term-id-from="002" term-id-to="003" href="RM1000000010V0Q"/><xref term-id-from="003" href="RM10000000136PZ"/></mlink></ptxt></content6></action></result><result label="2" cellposition="2-2"><action actiontype="next" cellposition="3-2" childid="RM100000000FWAL_02_0016"/></result></results></testgrp><testgrp id="RM100000000FWAL_02_0016" cellposition="3-2"><testtitle>REPLACE ECM</testtitle><content6><test1><ptxt>Temporarily replace the ECM with a new one.</ptxt><ptxt>for 1GR-FE: Click here<mlink><xref label="Seep00001" term-id-from="001" href="RM100000000FJEC"/></mlink></ptxt><ptxt>for 1VD-FTV: Click here<mlink><xref label="Seep00002" term-id-from="001" term-id-to="003" href="RM100000000FJHY"/><xref term-id-from="003" href="RM1000000013IGX"/></mlink></ptxt></test1><spec type="other"><title>Result</title><table><tgroup cols="1"><colspec colname="col1" colwidth="4.13in"/><thead><row><entry align="center" valign="middle"><ptxt>Proceed to</ptxt></entry></row></thead><tbody><row><entry align="center" valign="middle"><judge-value label="1"><ptxt>NEXT</ptxt></judge-value></entry></row></tbody></tgroup></table></spec></content6><results><result label="1" cellposition="3-2"><action actiontype="end" cellposition="4-2"><actiontitle>END</actiontitle><content6/></action></result></results></testgrp></subpara></para></ttl></section></servcat></pub></tmc-service-paragraph>
