=== randokuruza70/manual/manual/brm/dtd/paragraph-contents.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- #  DTD VERSION 1.7  UPDATE Dec. 04, 2014    -->
<!ELEMENT tmc-service-paragraph (pub)>
<!ELEMENT pub (servcat)>
<!ATTLIST pub
	id CDATA #REQUIRED
>
<!ELEMENT servcat (name, section)>
<!ATTLIST servcat
	id CDATA #REQUIRED
>
<!ELEMENT section (name, ttl)>
<!ATTLIST section
	id CDATA #REQUIRED
>
<!ELEMENT ttl (name, para)>
<!ATTLIST ttl
	id CDATA #REQUIRED
>
<!ELEMENT para (((name, ncf-para?) | (dtccode, dtcname)*), subpara+)>
<!ATTLIST para
	category CDATA #REQUIRED
	id ID #REQUIRED
>
<!ELEMENT ncf-para (name)>
<!ATTLIST ncf-para
	ncf-para-category CDATA #REQUIRED
>
<!ELEMENT subpara (name?, s-1*, content2*, content3*, content4*, content5*, testgrp*)>
<!ATTLIST subpara
	id ID #REQUIRED
	category CDATA #REQUIRED
>
<!ELEMENT name (#PCDATA)>
<!ELEMENT dtcname (#PCDATA)>
<!ELEMENT dtccode (#PCDATA)>
<!ELEMENT action (actiontitle, content6?)?>
<!ATTLIST action
	actiontype (next | end | jump) #REQUIRED
	cellposition CDATA #IMPLIED
	childid CDATA #IMPLIED
>
<!ELEMENT actiontitle (#PCDATA)>
<!ELEMENT atten2 (title?, (figure | ptxt | list1 | table)+)>
<!ELEMENT atten3 (title?, (figure | ptxt | list1 | table)+)>
<!ELEMENT atten4 (title?, (figure | ptxt | list1 | table)+)>
<!ELEMENT callout (table)>
<!ELEMENT colspec EMPTY>
<!ATTLIST colspec
	align (left | right | center) #IMPLIED
	colname NMTOKEN #IMPLIED
	colnum NMTOKEN #IMPLIED
	colsep NMTOKEN #IMPLIED
	colwidth CDATA #IMPLIED
	rowsep NMTOKEN #IMPLIED
>
<!ELEMENT content1 ((ptxt | list1 | spec | figure | table | atten2 | atten3 | atten4 | torque | sst | gts-info)*, s2*)>
<!ELEMENT content2 (title?, (ptxt | figure | atten2 | atten3 | atten4)*)>
<!ELEMENT content3 (title?, (ptxt | list1 | spec | figure | table | atten2 | atten3 | atten4 | torque | sst | gts-info)*)>
<!ELEMENT content4 (title?, (table | atten2 | atten3 | atten4)*)>
<!ELEMENT content5 (title?, (ptxt | step1 | list1 | spec | figure | table | atten2 | atten3 | atten4 | torque | sst | topic | gts-info)*)>
<!ELEMENT content6 (title?, (spec | sst | torque | atten2 | atten3 | atten4 | figure | list1 | table | test1 | ptxt | gts-info)*)>
<!ELEMENT convertitem (c-value1*, c-value2*, c-value3*)>
<!ATTLIST convertitem
	point1 CDATA #REQUIRED
	point2 CDATA #IMPLIED
	style CDATA #REQUIRED
	unit CDATA #REQUIRED
>
<!ELEMENT c-value1 (#PCDATA)>
<!ATTLIST c-value1
	type CDATA #REQUIRED
	unit CDATA #REQUIRED
>
<!ELEMENT c-value2 (#PCDATA)>
<!ATTLIST c-value2
	type CDATA #REQUIRED
	unit CDATA #REQUIRED
>
<!ELEMENT c-value3 (#PCDATA)>
<!ATTLIST c-value3
	type CDATA #REQUIRED
	unit CDATA #REQUIRED
>
<!ELEMENT data-name (ptxt | list1 | mlink | torque | graphic | atten2 | atten3 | atten4)*>
<!ATTLIST data-name
	args1 CDATA #IMPLIED
	name CDATA #REQUIRED
	parts-id CDATA #IMPLIED
>
<!ELEMENT entry (data-name | (title?, (ptxt | list1 | atten2 | atten3 | atten4 | graphic | judge-value)*))>
<!ATTLIST entry
	align (left | right | center) #IMPLIED
	colname NMTOKEN #IMPLIED
	colsep NMTOKEN #IMPLIED
	morerows NMTOKEN #IMPLIED
	nameend NMTOKEN #IMPLIED
	namest NMTOKEN #IMPLIED
	rowsep NMTOKEN #IMPLIED
	valign (top | middle | bottom) #IMPLIED
>
<!ELEMENT figure (title?, graphic+, callout?, footnote?)>
<!ATTLIST figure
	translate CDATA #IMPLIED
	type CDATA #IMPLIED
>
<!ELEMENT footnote (ptxt)+>
<!ELEMENT graphic EMPTY>
<!ATTLIST graphic
	graphicname CDATA #REQUIRED
	height CDATA #REQUIRED
	width CDATA #REQUIRED
>
<!ELEMENT item (ptxt | figure | table | spec | atten2 | atten3 | atten4)+>
<!ATTLIST item
	label CDATA #IMPLIED
>
<!ELEMENT judge-value (ptxt)>
<!ATTLIST judge-value
	label CDATA #IMPLIED
>
<!ELEMENT list1 (title?, figure*, item, (item | list2)*)>
<!ATTLIST list1
	type (ordered | unordered | nonmark) #IMPLIED
>
<!ELEMENT list2 (title?, figure*, item, (item | list3)*)>
<!ATTLIST list2
	type (ordered | unordered | nonmark) #IMPLIED
>
<!ELEMENT list3 (title?, figure*, item+)>
<!ATTLIST list3
	type (ordered | unordered | nonmark) #IMPLIED
>
<!ELEMENT mlink (xref+)>
<!ELEMENT ptxt (#PCDATA | sub | sup | mlink)*>
<!ELEMENT result (action)>
<!ATTLIST result
	cellposition CDATA #IMPLIED
	label CDATA #IMPLIED
>
<!ELEMENT results (result+)>
<!ELEMENT row (entry+)>
<!ATTLIST row
	rowsep NMTOKEN #IMPLIED
>
<!ELEMENT s-1 (ptxt+, content1*)>
<!ATTLIST s-1
	id ID #REQUIRED
>
<!ELEMENT s2 ((ptxt | list1 | spec | figure | table | atten2 | atten3 | atten4 | torque | sst | gts-info)*, s3*)>
<!ATTLIST s2
	label CDATA #IMPLIED
>
<!ELEMENT s3 ((ptxt | list1 | spec | figure | table | atten2 | atten3 | atten4 | torque | sst | gts-info)*)>
<!ATTLIST s3
	label CDATA #IMPLIED
>
<!ELEMENT s-number (#PCDATA)>
<!ELEMENT spec (title, (table | (subtitle* | specitem)+)+)>
<!ATTLIST spec
	type (current | resistance | voltage | other) #REQUIRED
>
<!ELEMENT specitem (ptxt)+>
<!ELEMENT sst (sstitem+)>
<!ELEMENT sstitem (s-number+, s-subnumber*, ptxt?)+>
<!ELEMENT s-subnumber (#PCDATA)>
<!ELEMENT step1 ((ptxt | list1 | spec | figure | table | atten2 | atten3 | atten4 | torque | sst | gts-info)*, step2*)>
<!ATTLIST step1
	label CDATA #IMPLIED
>
<!ELEMENT step2 ((ptxt | list1 | spec | figure | table | atten2 | atten3 | atten4 | torque | sst | gts-info)*, step3*)>
<!ATTLIST step2
	label CDATA #IMPLIED
>
<!ELEMENT step3 ((ptxt | list1 | spec | figure | table | atten2 | atten3 | atten4 | torque | sst | gts-info)*)>
<!ATTLIST step3
	label CDATA #IMPLIED
>
<!ELEMENT sub (#PCDATA)>
<!ELEMENT subtitle (#PCDATA)>
<!ELEMENT sup (#PCDATA)>
<!ELEMENT table (title?, (ptxt)*, tgroup+, footnote?)>
<!ATTLIST table
	colsep NMTOKEN #IMPLIED
	frame (all | none) #IMPLIED
	pgwide NMTOKEN #IMPLIED
	rowsep NMTOKEN #IMPLIED
	type (dtc-table | dtc-explan-table | tool-table | symptom-table | caption-table | torque-specification-table | freeze-frame | data-list | data-list-table | active-test | active-test-table | utility | utility-table | customize | multi-list) #IMPLIED
>
<!ELEMENT tbody (row+)>
<!ATTLIST tbody
	valign (top | middle | bottom) #IMPLIED
>
<!ELEMENT test1 (ptxt, (ptxt | spec | atten2 | atten3 | atten4 | figure | list1 | table | gts-info)*, test2*)>
<!ATTLIST test1
	id ID #IMPLIED
	label CDATA #IMPLIED
>
<!ELEMENT test2 (ptxt, (ptxt | spec | atten2 | atten3 | atten4 | figure | list1 | table | gts-info)*)>
<!ATTLIST test2
	id ID #IMPLIED
	label CDATA #IMPLIED
>
<!ELEMENT testgrp (testtitle, content6*, results?)>
<!ATTLIST testgrp
	cellposition CDATA #IMPLIED
	id ID #REQUIRED
>
<!ELEMENT testtitle (#PCDATA)*>
<!ELEMENT tgroup (colspec*, thead?, tbody)>
<!ATTLIST tgroup
	align (left | right | center) #IMPLIED
	cols NMTOKEN #REQUIRED
	colsep NMTOKEN #IMPLIED
	rowsep NMTOKEN #IMPLIED
>
<!ELEMENT thead (colspec*, row+)>
<!ATTLIST thead
	valign (top | middle | bottom) #IMPLIED
>
<!ELEMENT title (#PCDATA)>
<!ATTLIST title
	date CDATA #IMPLIED
>
<!ELEMENT topic (title?, (ptxt | list1 | spec | figure | table | atten2 | atten3 | atten4 | torque | sst)*)>
<!ATTLIST topic
	id ID #IMPLIED
>
<!ELEMENT torque (subtitle?, convertitem, ptxt*)+>
<!ELEMENT xref EMPTY>
<!ATTLIST xref
	href CDATA #REQUIRED
	label CDATA #IMPLIED
	refid CDATA #IMPLIED
	term-id-from CDATA #REQUIRED
	term-id-to CDATA #IMPLIED
>
<!ELEMENT gts-info (title, ((table+, title?, table?, gts-exec?, app-communication) | (gts-exec, app-communication)))>
<!ATTLIST gts-info
	category CDATA #IMPLIED
>
<!ELEMENT gts-cust EMPTY>
<!ATTLIST gts-cust
	cust-id CDATA #REQUIRED
>
<!ELEMENT gts-did EMPTY>
<!ATTLIST gts-did
	did-id CDATA #REQUIRED
>
<!ELEMENT gts-ecu (gts-did?, gts-pid*, gts-util?)?>
<!ATTLIST gts-ecu
	ecu-id CDATA #REQUIRED
>
<!ELEMENT gts-exec ((gts-ecu* | gts-cust*), gts-2nd-ecu?)>
<!ATTLIST gts-exec
	function-id CDATA #REQUIRED
>
<!ELEMENT gts-pid EMPTY>
<!ATTLIST gts-pid
	pid-id CDATA #REQUIRED
>
<!ELEMENT gts-util EMPTY>
<!ATTLIST gts-util
	util-id CDATA #REQUIRED
>
<!ELEMENT gts-2nd-ecu (gts-2nd-pid*, gts-multi)?>
<!ATTLIST gts-2nd-ecu
	ecu-id CDATA #REQUIRED
>
<!ELEMENT gts-2nd-pid EMPTY>
<!ATTLIST gts-2nd-pid
	pid-id CDATA #REQUIRED
>
<!ELEMENT gts-multi EMPTY>
<!ATTLIST gts-multi
	multi-mode CDATA #REQUIRED
>
<!ELEMENT app-param (#PCDATA)*>
<!ATTLIST app-param
	name CDATA #REQUIRED
>
<!ELEMENT app-communication (app-param-unit | app-param)*>
<!ELEMENT app-param-unit (app-param+)>

=== randokuruza70/manual/manual/repair/contents/xml/RM100000000FJHA.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tmc-service-paragraph SYSTEM "../dtd/paragraph-contents.dtd">
<tmc-service-paragraph><pub id="RM25T0E"><servcat id="_51"><name>Engine / Hybrid System</name><section id="_029759"><name>1HZ ENGINE CONTROL</name><ttl id="_0135351"><name>ECD SYSTEM</name><para id="RM100000000FJHA" category="J"><dtccode/><dtcname>TC and CG Terminal Circuit</dtcname><subpara id="RM100000000FJHA_01" category="03"><name>DESCRIPTION</name><content5><ptxt>Terminal TC is located in the DLC3.</ptxt><ptxt>The DLC3 is located in the vehicle interior. When terminal TC is connected with terminal CG, DTCs can be read from the glow indicator light in the combination meter assembly.</ptxt></content5></subpara><subpara id="RM100000000FJHA_02" category="03"><name>WIRING DIAGRAM</name><content5><figure type="1" translate="E"><graphic graphicname="A190479E03" width="7.168479331in" height="2.799876969in"/></figure></content5></subpara><subpara id="RM100000000FJHA_03" category="10"><name>CAUTION / NOTICE / HINT</name><content5><atten4><list1 type="unordered"><item><ptxt>Even though terminal TC is not connected with terminal CG, the glow indicator light may blink.</ptxt></item><item><ptxt>For the above phenomenon, the likely cause is an open or short in the wire harness, or malfunction inside the emission control ECU.</ptxt></item></list1></atten4></content5></subpara><subpara id="RM100000000FJHA_06" category="01"><name>PROCEDURE</name><testgrp id="RM100000000FJHA_06_0001" cellposition="1-1"><testtitle>INSPECT DLC3</testtitle><content6><test1><ptxt>Measure the voltage according to the value(s) in the table below.</ptxt><spec type="voltage"><title>Standard Voltage</title><table><tgroup cols="3"><colspec colname="col1" colwidth="1.38in"/><colspec colname="col2" colwidth="1.38in"/><colspec colname="col3" colwidth="1.37in"/><thead><row><entry align="center" valign="middle"><ptxt>Tester Connection</ptxt></entry><entry align="center" valign="middle"><ptxt>Switch Condition</ptxt></entry><entry align="center" valign="middle"><ptxt>Specified Condition</ptxt></entry></row></thead><tbody><row><entry align="center" valign="middle"><ptxt>I17-13 (TC) - I17-4 (CG)</ptxt></entry><entry align="center" valign="middle"><ptxt>Ignition switch ON</ptxt></entry><entry align="center" valign="middle"><ptxt>11 to 14 V</ptxt></entry></row></tbody></tgroup></table></spec><spec type="other"><title>Result</title><table><tgroup cols="1"><colspec colname="col1" colwidth="4.13in"/><tbody><row><entry align="center" valign="middle"><ptxt>Proceed to</ptxt></entry></row><row><entry align="center" valign="middle"><judge-value label="1"><ptxt>OK</ptxt></judge-value></entry></row><row><entry align="center" valign="middle"><judge-value label="2"><ptxt>NG</ptxt></judge-value></entry></row></tbody></tgroup></table></spec><figure type="1" translate="C"><graphic graphicname="A191618C06" width="3.434793307in" height="3.434793307in"/><callout><table pgwide="0" type="caption-table"><tgroup cols="2"><colspec colname="col1" colnum="1" colwidth="0.69in"/><colspec colname="col2" colnum="2" colwidth="2.75in"/><tbody><row><entry align="center" valign="middle"><ptxt>*a</ptxt></entry><entry><ptxt>Front view of wire harness connector</ptxt><ptxt>(DLC3)</ptxt></entry></row></tbody></tgroup></table></callout></figure></test1></content6><results><result label="1" cellposition="1-1"><action actiontype="end" cellposition="2-1"><actiontitle>REPLACE EMISSION CONTROL ECU</actiontitle><content6><ptxt>Click here<mlink><xref label="Seep00001" term-id-from="001" href="RM100000000FJQS"/></mlink></ptxt></content6></action></result><result label="2" cellposition="1-2"><action actiontype="next" cellposition="2-2" childid="RM100000000FJHA_06_0003"/></result></results></testgrp><testgrp id="RM100000000FJHA_06_0003" cellposition="2-2"><testtitle>CHECK HARNESS AND CONNECTOR (DLC3 - BODY GROUND)</testtitle><content6><test1><ptxt>Measure the resistance according to the value(s) in the table below.</ptxt><spec type="resistance"><title>Standard Resistance</title><table><tgroup cols="3"><colspec colname="col1" colwidth="1.38in"/><colspec colname="col2" colwidth="1.38in"/><colspec colname="col3" colwidth="1.37in"/><thead><row><entry align="center" valign="middle"><ptxt>Tester Connection</ptxt></entry><entry align="center" valign="middle"><ptxt>Condition</ptxt></entry><entry align="center" valign="middle"><ptxt>Specified Condition</ptxt></entry></row></thead><tbody><row><entry align="center" valign="middle"><ptxt>I17-4 (CG) - Body ground</ptxt></entry><entry align="center" valign="middle"><ptxt>Always</ptxt></entry><entry align="center" valign="middle"><ptxt>Below 1 Ω</ptxt></entry></row></tbody></tgroup></table></spec><spec type="other"><title>Result</title><table><tgroup cols="1"><colspec colname="col1" colwidth="4.13in"/><tbody><row><entry align="center" valign="middle"><ptxt>Proceed to</ptxt></entry></row><row><entry align="center" valign="middle"><judge-value label="1"><ptxt>OK</ptxt></judge-value></entry></row><row><entry align="center" valign="middle"><judge-value label="2"><ptxt>NG</ptxt></judge-value></entry></row></tbody></tgroup></table></spec><figure type="1" translate="C"><graphic graphicname="A191618C07" width="3.434793307in" height="3.434793307in"/><callout><table pgwide="0" type="caption-table"><tgroup cols="2"><colspec colname="col1" colnum="1" colwidth="0.69in"/><colspec colname="col2" colnum="2" colwidth="2.75in"/><tbody><row><entry align="center" valign="middle"><ptxt>*a</ptxt></entry><entry><ptxt>Front view of wire harness connector</ptxt><ptxt>(DLC3)</ptxt></entry></row></tbody></tgroup></table></callout></figure></test1></content6><results><result label="1" cellposition="2-2"><action actiontype="next" cellposition="4-2" childid="RM100000000FJHA_06_0004"/></result><result label="2" cellposition="2-3"><action actiontype="end" cellposition="3-3"><actiontitle>REPAIR OR REPLACE HARNESS OR CONNECTOR</actiontitle><content6/></action></result></results></testgrp><testgrp id="RM100000000FJHA_06_0004" cellposition="4-2"><testtitle>CHECK HARNESS AND CONNECTOR (DLC3 - EMISSION CONTROL ECU)</testtitle><content6><test1><ptxt>Disconnect the emission control ECU connector.</ptxt></test1><test1><ptxt>Measure the resistance according to the value(s) in the table below.</ptxt><spec type="resistance"><title>Standard Resistance</title><table><tgroup cols="3"><colspec colname="col1" colwidth="1.38in"/><colspec colname="col2" colwidth="1.38in"/><colspec colname="col3" colwidth="1.37in"/><thead><row><entry align="center" valign="middle"><ptxt>Tester Connection</ptxt></entry><entry align="center" valign="middle"><ptxt>Condition</ptxt></entry><entry align="center" valign="middle"><ptxt>Specified Condition</ptxt></entry></row></thead><tbody><row><entry align="center" valign="middle"><ptxt>I17-13 (TC) - A31-14 (TC)</ptxt></entry><entry align="center" valign="middle"><ptxt>Always</ptxt></entry><entry align="center" valign="middle"><ptxt>Below 1 Ω</ptxt></entry></row><row><entry align="center" valign="middle"><ptxt>I17-13 (TC) or A31-14 (TC) - Body ground</ptxt></entry><entry align="center" valign="middle"><ptxt>Always</ptxt></entry><entry align="center" valign="middle"><ptxt>10 kΩ or higher</ptxt></entry></row></tbody></tgroup></table></spec><spec type="other"><title>Result</title><table><tgroup cols="1"><colspec colname="col1" colwidth="4.13in"/><tbody><row><entry align="center" valign="middle"><ptxt>Proceed to</ptxt></entry></row><row><entry align="center" valign="middle"><judge-value label="1"><ptxt>OK</ptxt></judge-value></entry></row><row><entry align="center" valign="middle"><judge-value label="2"><ptxt>NG</ptxt></judge-value></entry></row></tbody></tgroup></table></spec><figure type="1" translate="C"><graphic graphicname="A311450C02" width="3.434793307in" height="4.677165354in"/><callout><table pgwide="0" type="caption-table"><tgroup cols="2"><colspec colname="col1" colnum="1" colwidth="0.69in"/><colspec colname="col2" colnum="2" colwidth="2.75in"/><tbody><row><entry align="center" valign="middle"><ptxt>*a</ptxt></entry><entry><ptxt>Front view of wire harness connector</ptxt><ptxt>(DLC3)</ptxt></entry></row><row><entry align="center" valign="middle"><ptxt>*b</ptxt></entry><entry><ptxt>Rear view of wire harness connector</ptxt><ptxt>(to Emission Control ECU)</ptxt></entry></row></tbody></tgroup></table></callout></figure></test1></content6><results><result label="1" cellposition="4-2"><action actiontype="end" cellposition="5-2"><actiontitle>REPLACE EMISSION CONTROL ECU</actiontitle><content6><ptxt>Click here<mlink><xref label="Seep00001" term-id-from="001" href="RM100000000FJQS"/></mlink></ptxt></content6></action></result><result label="2" cellposition="4-3"><action actiontype="end" cellposition="5-3"><actiontitle>REPAIR OR REPLACE HARNESS OR CONNECTOR</actiontitle><content6/></action></result></results></testgrp></subpara></para></ttl></section></servcat></pub></tmc-service-paragraph>

=== randokuruza70/manual/manual/repair/contents/xml/RM100000000FWMF.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tmc-service-paragraph SYSTEM "../dtd/paragraph-contents.dtd">
<tmc-service-paragraph><pub id="RM25T0E"><servcat id="_58"><name>Vehicle Interior</name><section id="_029924"><name>DOOR LOCK</name><ttl id="_0138408"><name>KEY REMINDER WARNING SYSTEM</name><para id="RM100000000FWMF" category="Y"><dtccode/><dtcname>HOW TO PROCEED WITH TROUBLESHOOTING</dtcname><subpara id="RM100000000FWMF_01" category="10"><name>CAUTION / NOTICE / HINT</name><content5><atten4><ptxt>Use the following procedures to troubleshoot the key reminder warning system.</ptxt></atten4></content5></subpara><subpara id="RM100000000FWMF_02" category="01"><name>PROCEDURE</name><testgrp id="RM100000000FWMF_02_0001" cellposition="1-1"><testtitle>VEHICLE BROUGHT TO WORKSHOP</testtitle><content6><spec type="other"><title>Result</title><table><tgroup cols="1"><colspec colname="col1" colwidth="4.13in"/><thead><row><entry align="center" valign="middle"><ptxt>Proceed to</ptxt></entry></row></thead><tbody><row><entry align="center" valign="middle"><judge-value label="1"><ptxt>NEXT</ptxt></judge-value></entry></row></tbody></tgroup></table></spec></content6><results><result label="1" cellposition="1-1"><action actiontype="next" cellposition="2-1" childid="RM100000000FWMF_02_0009"/></result></results></testgrp><testgrp id="RM100000000FWMF_02_0009" cellposition="2-1"><testtitle>CUSTOMER PROBLEM ANALYSIS</testtitle><content6><atten4><list1 type="unordered"><item><ptxt>In troubleshooting, confirm that the problem symptoms have been accurately identified. Preconceptions should be discarded in order to make an accurate judgment. To clearly understand what the problem symptoms are, it is extremely important to ask the customer about the problem and the conditions at the time the malfunction occurred.</ptxt></item><item><ptxt>Gather as much information as possible for reference. Past problems that seem unrelated may also help in some cases.</ptxt></item><item><ptxt>The following 5 items are important points for problem analysis:</ptxt></item></list1></atten4><table pgwide="1"><tgroup cols="2"><colspec colname="col1" colwidth="2.83in"/><colspec colname="col2" colwidth="4.25in"/><tbody><row><entry valign="middle" align="center"><ptxt>What</ptxt></entry><entry valign="middle"><ptxt>Vehicle model, system name</ptxt></entry></row><row><entry valign="middle" align="center"><ptxt>When</ptxt></entry><entry valign="middle"><ptxt>Date, time, occurrence frequency, whether the problem occurred recently or has been occurring for a long time</ptxt></entry></row><row><entry valign="middle" align="center"><ptxt>Where</ptxt></entry><entry valign="middle"><ptxt>Whether the problem occurs at a specific location</ptxt></entry></row><row><entry valign="middle" align="center"><ptxt>Under what conditions?</ptxt></entry><entry valign="middle"><ptxt>Whether the doors were locked or unlocked, whether the ignition switch was ON, whether the engine has started</ptxt></entry></row><row><entry valign="middle" align="center"><ptxt>How did it happen?</ptxt></entry><entry valign="middle"><ptxt>Problem symptoms</ptxt></entry></row></tbody></tgroup></table><spec type="other"><title>Result</title><table><tgroup cols="1"><colspec colname="col1" colwidth="4.13in"/><thead><row><entry valign="middle" align="center"><ptxt>Proceed to</ptxt></entry></row></thead><tbody><row><entry valign="middle" align="center"><judge-value label="1"><ptxt>NEXT</ptxt></judge-value></entry></row></tbody></tgroup></table></spec></content6><results><result label="1" cellposition="2-1"><action actiontype="next" cellposition="3-1" childid="RM100000000FWMF_02_0002"/></result></results></testgrp><testgrp id="RM100000000FWMF_02_0002" cellposition="3-1"><testtitle>INSPECT BATTERY VOLTAGE</testtitle><content6><spec type="other"><title>Standard voltage</title><specitem><ptxt>11 to 14 V</ptxt></specitem></spec><ptxt>If the voltage is below 11 V, recharge or replace the battery before proceeding to the next step.</ptxt><spec type="other"><title>Result</title><table><tgroup cols="1"><colspec colname="col1" colwidth="4.13in"/><thead><row><entry align="center" valign="middle"><ptxt>Proceed to</ptxt></entry></row></thead><tbody><row><entry align="center" valign="middle"><judge-value label="1"><ptxt>NEXT</ptxt></judge-value></entry></row></tbody></tgroup></table></spec></content6><results><result label="1" cellposition="3-1"><action actiontype="next" cellposition="4-1" childid="RM100000000FWMF_02_0003"/></result></results></testgrp><testgrp id="RM100000000FWMF_02_0003" cellposition="4-1"><testtitle>PROBLEM SYMPTOMS TABLE</testtitle><content6><test1><ptxt>Refer to Problem Symptoms Table.</ptxt><ptxt>Click here<mlink><xref label="Seep00001" term-id-from="001" href="RM100000000FWMH"/></mlink></ptxt></test1><spec type="other"><title>Result</title><table><tgroup cols="2"><colspec colname="col1" colwidth="2.89in"/><colspec colname="col2" colwidth="1.24in"/><thead><row><entry valign="middle" align="center"><ptxt>Result</ptxt></entry><entry valign="middle" align="center"><ptxt>Proceed to</ptxt></entry></row></thead><tbody><row><entry valign="middle"><ptxt>Fault is not listed in problem symptoms table</ptxt></entry><entry valign="middle" align="center"><judge-value label="1"><ptxt>A</ptxt></judge-value></entry></row><row><entry valign="middle"><ptxt>Fault is listed in problem symptoms table</ptxt></entry><entry valign="middle" align="center"><judge-value label="2"><ptxt>B</ptxt></judge-value></entry></row></tbody></tgroup></table></spec></content6><results><result label="1" cellposition="4-1"><action actiontype="next" cellposition="5-1" childid="RM100000000FWMF_02_0004"/></result><result label="2" cellposition="4-3"><action actiontype="end" cellposition="5-3"><actiontitle>ADJUST, REPAIR OR REPLACE IN ACCORDANCE WITH PROBLEM SYMPTOMS TABLE</actiontitle><content6/></action></result></results></testgrp><testgrp id="RM100000000FWMF_02_0004" cellposition="5-1"><testtitle>OVERALL ANALYSIS AND TROUBLESHOOTING</testtitle><content6><test1><ptxt>Operation Check.</ptxt><ptxt>Click here<mlink><xref label="Seep00001" term-id-from="001" href="RM100000000FWMG"/></mlink></ptxt></test1><test1><ptxt>Terminals of ECU.</ptxt><ptxt>Click here<mlink><xref label="Seep00002" term-id-from="001" href="RM100000000FWMI"/></mlink></ptxt></test1><test1><ptxt>Inspection.</ptxt></test1><spec type="other"><title>Result</title><table><tgroup cols="1"><colspec colname="col1" colwidth="4.13in"/><thead><row><entry align="center" valign="middle"><ptxt>Proceed to</ptxt></entry></row></thead><tbody><row><entry align="center" valign="middle"><judge-value label="1"><ptxt>NEXT</ptxt></judge-value></entry></row></tbody></tgroup></table></spec></content6><results><result label="1" cellposition="5-1"><action actiontype="next" cellposition="6-1" childid="RM100000000FWMF_02_0005"/></result></results></testgrp><testgrp id="RM100000000FWMF_02_0005" cellposition="6-1"><testtitle>REPAIR OR REPLACE</testtitle><content6><spec type="other"><title>Result</title><table><tgroup cols="1"><colspec colname="col1" colwidth="4.13in"/><thead><row><entry align="center" valign="middle"><ptxt>Proceed to</ptxt></entry></row></thead><tbody><row><entry align="center" valign="middle"><judge-value label="1"><ptxt>NEXT</ptxt></judge-value></entry></row></tbody></tgroup></table></spec></content6><results><result label="1" cellposition="6-1"><action actiontype="next" cellposition="7-1" childid="RM100000000FWMF_02_0006"/></result></results></testgrp><testgrp id="RM100000000FWMF_02_0006" cellposition="7-1"><testtitle>CONFIRMATION TEST</testtitle><content6><spec type="other"><title>Result</title><table><tgroup cols="1"><colspec colname="col1" colwidth="4.13in"/><thead><row><entry align="center" valign="middle"><ptxt>Proceed to</ptxt></entry></row></thead><tbody><row><entry align="center" valign="middle"><judge-value label="1"><ptxt>NEXT</ptxt></judge-value></entry></row></tbody></tgroup></table></spec></content6><results><result label="1" cellposition="7-1"><action actiontype="end" cellposition="8-1"><actiontitle>END</actiontitle><content6/></action></result></results></testgrp></subpara></para></ttl></section></servcat></pub></tmc-service-paragraph>
