=== randokuruza70/manual/manual/brm/dtd/paragraph-contents.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- #  DTD VERSION 1.7  UPDATE Dec. 04, 2014    -->
<!ELEMENT tmc-service-paragraph (pub)>
<!ELEMENT pub (servcat)>
<!ATTLIST pub
	id CDATA #REQUIRED
>
<!ELEMENT servcat (name, section)>
<!ATTLIST servcat
	id CDATA #REQUIRED
>
<!ELEMENT section (name, ttl)>
<!ATTLIST section
	id CDATA #REQUIRED
>
<!ELEMENT ttl (name, para)>
<!ATTLIST ttl
	id CDATA #REQUIRED
>
<!ELEMENT para (((name, ncf-para?) | (dtccode, dtcname)*), subpara+)>
<!ATTLIST para
	category CDATA #REQUIRED
	id ID #REQUIRED
>
<!ELEMENT ncf-para (name)>
<!ATTLIST ncf-para
	ncf-para-category CDATA #REQUIRED
>
<!ELEMENT subpara (name?, s-1*, content2*, content3*, content4*, content5*, testgrp*)>
<!ATTLIST subpara
	id ID #REQUIRED
	category CDATA #REQUIRED
>
<!ELEMENT name (#PCDATA)>
<!ELEMENT dtcname (#PCDATA)>
<!ELEMENT dtccode (#PCDATA)>
<!ELEMENT action (actiontitle, content6?)?>
<!ATTLIST action
	actiontype (next | end | jump) #REQUIRED
	cellposition CDATA #IMPLIED
	childid CDATA #IMPLIED
>
<!ELEMENT actiontitle (#PCDATA)>
<!ELEMENT atten2 (title?, (figure | ptxt | list1 | table)+)>
<!ELEMENT atten3 (title?, (figure | ptxt | list1 | table)+)>
<!ELEMENT atten4 (title?, (figure | ptxt | list1 | table)+)>
<!ELEMENT callout (table)>
<!ELEMENT colspec EMPTY>
<!ATTLIST colspec
	align (left | right | center) #IMPLIED
	colname NMTOKEN #IMPLIED
	colnum NMTOKEN #IMPLIED
	colsep NMTOKEN #IMPLIED
	colwidth CDATA #IMPLIED
	rowsep NMTOKEN #IMPLIED
>
<!ELEMENT content1 ((ptxt | list1 | spec | figure | table | atten2 | atten3 | atten4 | torque | sst | gts-info)*, s2*)>
<!ELEMENT content2 (title?, (ptxt | figure | atten2 | atten3 | atten4)*)>
<!ELEMENT content3 (title?, (ptxt | list1 | spec | figure | table | atten2 | atten3 | atten4 | torque | sst | gts-info)*)>
<!ELEMENT content4 (title?, (table | atten2 | atten3 | atten4)*)>
<!ELEMENT content5 (title?, (ptxt | step1 | list1 | spec | figure | table | atten2 | atten3 | atten4 | torque | sst | topic | gts-info)*)>
<!ELEMENT content6 (title?, (spec | sst | torque | atten2 | atten3 | atten4 | figure | list1 | table | test1 | ptxt | gts-info)*)>
<!ELEMENT convertitem (c-value1*, c-value2*, c-value3*)>
<!ATTLIST convertitem
	point1 CDATA #REQUIRED
	point2 CDATA #IMPLIED
	style CDATA #REQUIRED
	unit CDATA #REQUIRED
>
<!ELEMENT c-value1 (#PCDATA)>
<!ATTLIST c-value1
	type CDATA #REQUIRED
	unit CDATA #REQUIRED
>
<!ELEMENT c-value2 (#PCDATA)>
<!ATTLIST c-value2
	type CDATA #REQUIRED
	unit CDATA #REQUIRED
>
<!ELEMENT c-value3 (#PCDATA)>
<!ATTLIST c-value3
	type CDATA #REQUIRED
	unit CDATA #REQUIRED
>
<!ELEMENT data-name (ptxt | list1 | mlink | torque | graphic | atten2 | atten3 | atten4)*>
<!ATTLIST data-name
	args1 CDATA #IMPLIED
	name CDATA #REQUIRED
	parts-id CDATA #IMPLIED
>
<!ELEMENT entry (data-name | (title?, (ptxt | list1 | atten2 | atten3 | atten4 | graphic | judge-value)*))>
<!ATTLIST entry
	align (left | right | center) #IMPLIED
	colname NMTOKEN #IMPLIED
	colsep NMTOKEN #IMPLIED
	morerows NMTOKEN #IMPLIED
	nameend NMTOKEN #IMPLIED
	namest NMTOKEN #IMPLIED
	rowsep NMTOKEN #IMPLIED
	valign (top | middle | bottom) #IMPLIED
>
<!ELEMENT figure (title?, graphic+, callout?, footnote?)>
<!ATTLIST figure
	translate CDATA #IMPLIED
	type CDATA #IMPLIED
>
<!ELEMENT footnote (ptxt)+>
<!ELEMENT graphic EMPTY>
<!ATTLIST graphic
	graphicname CDATA #REQUIRED
	height CDATA #REQUIRED
	width CDATA #REQUIRED
>
<!ELEMENT item (ptxt | figure | table | spec | atten2 | atten3 | atten4)+>
<!ATTLIST item
	label CDATA #IMPLIED
>
<!ELEMENT judge-value (ptxt)>
<!ATTLIST judge-value
	label CDATA #IMPLIED
>
<!ELEMENT list1 (title?, figure*, item, (item | list2)*)>
<!ATTLIST list1
	type (ordered | unordered | nonmark) #IMPLIED
>
<!ELEMENT list2 (title?, figure*, item, (item | list3)*)>
<!ATTLIST list2
	type (ordered | unordered | nonmark) #IMPLIED
>
<!ELEMENT list3 (title?, figure*, item+)>
<!ATTLIST list3
	type (ordered | unordered | nonmark) #IMPLIED
>
<!ELEMENT mlink (xref+)>
<!ELEMENT ptxt (#PCDATA | sub | sup | mlink)*>
<!ELEMENT result (action)>
<!ATTLIST result
	cellposition CDATA #IMPLIED
	label CDATA #IMPLIED
>
<!ELEMENT results (result+)>
<!ELEMENT row (entry+)>
<!ATTLIST row
	rowsep NMTOKEN #IMPLIED
>
<!ELEMENT s-1 (ptxt+, content1*)>
<!ATTLIST s-1
	id ID #REQUIRED
>
<!ELEMENT s2 ((ptxt | list1 | spec | figure | table | atten2 | atten3 | atten4 | torque | sst | gts-info)*, s3*)>
<!ATTLIST s2
	label CDATA #IMPLIED
>
<!ELEMENT s3 ((ptxt | list1 | spec | figure | table | atten2 | atten3 | atten4 | torque | sst | gts-info)*)>
<!ATTLIST s3
	label CDATA #IMPLIED
>
<!ELEMENT s-number (#PCDATA)>
<!ELEMENT spec (title, (table | (subtitle* | specitem)+)+)>
<!ATTLIST spec
	type (current | resistance | voltage | other) #REQUIRED
>
<!ELEMENT specitem (ptxt)+>
<!ELEMENT sst (sstitem+)>
<!ELEMENT sstitem (s-number+, s-subnumber*, ptxt?)+>
<!ELEMENT s-subnumber (#PCDATA)>
<!ELEMENT step1 ((ptxt | list1 | spec | figure | table | atten2 | atten3 | atten4 | torque | sst | gts-info)*, step2*)>
<!ATTLIST step1
	label CDATA #IMPLIED
>
<!ELEMENT step2 ((ptxt | list1 | spec | figure | table | atten2 | atten3 | atten4 | torque | sst | gts-info)*, step3*)>
<!ATTLIST step2
	label CDATA #IMPLIED
>
<!ELEMENT step3 ((ptxt | list1 | spec | figure | table | atten2 | atten3 | atten4 | torque | sst | gts-info)*)>
<!ATTLIST step3
	label CDATA #IMPLIED
>
<!ELEMENT sub (#PCDATA)>
<!ELEMENT subtitle (#PCDATA)>
<!ELEMENT sup (#PCDATA)>
<!ELEMENT table (title?, (ptxt)*, tgroup+, footnote?)>
<!ATTLIST table
	colsep NMTOKEN #IMPLIED
	frame (all | none) #IMPLIED
	pgwide NMTOKEN #IMPLIED
	rowsep NMTOKEN #IMPLIED
	type (dtc-table | dtc-explan-table | tool-table | symptom-table | caption-table | torque-specification-table | freeze-frame | data-list | data-list-table | active-test | active-test-table | utility | utility-table | customize | multi-list) #IMPLIED
>
<!ELEMENT tbody (row+)>
<!ATTLIST tbody
	valign (top | middle | bottom) #IMPLIED
>
<!ELEMENT test1 (ptxt, (ptxt | spec | atten2 | atten3 | atten4 | figure | list1 | table | gts-info)*, test2*)>
<!ATTLIST test1
	id ID #IMPLIED
	label CDATA #IMPLIED
>
<!ELEMENT test2 (ptxt, (ptxt | spec | atten2 | atten3 | atten4 | figure | list1 | table | gts-info)*)>
<!ATTLIST test2
	id ID #IMPLIED
	label CDATA #IMPLIED
>
<!ELEMENT testgrp (testtitle, content6*, results?)>
<!ATTLIST testgrp
	cellposition CDATA #IMPLIED
	id ID #REQUIRED
>
<!ELEMENT testtitle (#PCDATA)*>
<!ELEMENT tgroup (colspec*, thead?, tbody)>
<!ATTLIST tgroup
	align (left | right | center) #IMPLIED
	cols NMTOKEN #REQUIRED
	colsep NMTOKEN #IMPLIED
	rowsep NMTOKEN #IMPLIED
>
<!ELEMENT thead (colspec*, row+)>
<!ATTLIST thead
	valign (top | middle | bottom) #IMPLIED
>
<!ELEMENT title (#PCDATA)>
<!ATTLIST title
	date CDATA #IMPLIED
>
<!ELEMENT topic (title?, (ptxt | list1 | spec | figure | table | atten2 | atten3 | atten4 | torque | sst)*)>
<!ATTLIST topic
	id ID #IMPLIED
>
<!ELEMENT torque (subtitle?, convertitem, ptxt*)+>
<!ELEMENT xref EMPTY>
<!ATTLIST xref
	href CDATA #REQUIRED
	label CDATA #IMPLIED
	refid CDATA #IMPLIED
	term-id-from CDATA #REQUIRED
	term-id-to CDATA #IMPLIED
>
<!ELEMENT gts-info (title, ((table+, title?, table?, gts-exec?, app-communication) | (gts-exec, app-communication)))>
<!ATTLIST gts-info
	category CDATA #IMPLIED
>
<!ELEMENT gts-cust EMPTY>
<!ATTLIST gts-cust
	cust-id CDATA #REQUIRED
>
<!ELEMENT gts-did EMPTY>
<!ATTLIST gts-did
	did-id CDATA #REQUIRED
>
<!ELEMENT gts-ecu (gts-did?, gts-pid*, gts-util?)?>
<!ATTLIST gts-ecu
	ecu-id CDATA #REQUIRED
>
<!ELEMENT gts-exec ((gts-ecu* | gts-cust*), gts-2nd-ecu?)>
<!ATTLIST gts-exec
	function-id CDATA #REQUIRED
>
<!ELEMENT gts-pid EMPTY>
<!ATTLIST gts-pid
	pid-id CDATA #REQUIRED
>
<!ELEMENT gts-util EMPTY>
<!ATTLIST gts-util
	util-id CDATA #REQUIRED
>
<!ELEMENT gts-2nd-ecu (gts-2nd-pid*, gts-multi)?>
<!ATTLIST gts-2nd-ecu
	ecu-id CDATA #REQUIRED
>
<!ELEMENT gts-2nd-pid EMPTY>
<!ATTLIST gts-2nd-pid
	pid-id CDATA #REQUIRED
>
<!ELEMENT gts-multi EMPTY>
<!ATTLIST gts-multi
	multi-mode CDATA #REQUIRED
>
<!ELEMENT app-param (#PCDATA)*>
<!ATTLIST app-param
	name CDATA #REQUIRED
>
<!ELEMENT app-communication (app-param-unit | app-param)*>
<!ELEMENT app-param-unit (app-param+)>

=== randokuruza70/manual/manual/repair/contents/xml/RM100000000FKQC.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tmc-service-paragraph SYSTEM "../dtd/paragraph-contents.dtd">
<tmc-service-paragraph><pub id="RM25T0E"><servcat id="_54"><name>Brake</name><section id="_029873"><name>BRAKE CONTROL / DYNAMIC CONTROL SYSTEMS</name><ttl id="_0135612"><name>ANTI-LOCK BRAKE SYSTEM</name><para id="RM100000000FKQC" category="C"><dtccode>C1337</dtccode><dtcname>Diameter of the Tire is not Uniform</dtcname><subpara id="RM100000000FKQC_01" category="03"><name>DESCRIPTION</name><content5><ptxt>The brake actuator assembly (skid control ECU) measures the speed of each wheel by receiving signals from the speed sensors.</ptxt><ptxt>These signals are used for recognizing that all 4 wheels are operating properly.</ptxt><ptxt>Therefore, all wheel signals must indicate the same speed.</ptxt><table type="dtc-explan-table" pgwide="1"><tgroup cols="4"><colspec colname="1" colwidth="1.77in"/><colspec colname="2" colwidth="1.77in"/><colspec colname="3" colwidth="1.77in"/><colspec colname="4" colwidth="1.77in"/><thead><row><entry align="center" valign="middle"><ptxt>DTC No.</ptxt></entry><entry align="center" valign="middle"><ptxt>Detection Item</ptxt></entry><entry align="center" valign="middle"><ptxt>DTC Detection Condition</ptxt></entry><entry align="center" valign="middle"><ptxt>Trouble Area</ptxt></entry></row></thead><tbody><row><entry align="left" valign="middle"><data-name name="dtc-code"><ptxt>C1337</ptxt></data-name></entry><entry align="left" valign="middle"><data-name name="detect-item"><ptxt>Diameter of the Tire is not Uniform</ptxt></data-name></entry><entry align="left" valign="middle"><data-name name="dtc-detect-cond"><ptxt>The following occurs in 3 consecutive trips:</ptxt><ptxt>At a vehicle speed of 20 km/h (12 mph) or more, there is a difference of 20% or more in the average speed between the front wheels and rear wheels for 20 seconds or more.</ptxt></data-name></entry><entry align="left" valign="middle"><data-name name="trouble-area"><list1 type="unordered"><item><ptxt>Tire and wheel size</ptxt></item><item><ptxt>Tire deformation</ptxt></item><item><ptxt>Speed sensor rotor</ptxt></item><item><ptxt>Speed sensor</ptxt></item><item><ptxt>Speed sensor circuit</ptxt></item><item><ptxt>Brake actuator assembly (Skid control ECU)</ptxt></item></list1></data-name></entry></row></tbody></tgroup></table></content5></subpara><subpara id="RM100000000FKQC_03" category="10"><name>CAUTION / NOTICE / HINT</name><content5><atten4><ptxt>When DTCs C1401 to C1416 are output with DTC C1337, inspect and repair the trouble areas indicated by DTCs C1401 to C1416 first.</ptxt><ptxt>Click here<mlink><xref label="Seep00001" term-id-from="001" href="RM100000000FKQ7"/></mlink></ptxt></atten4></content5></subpara><subpara id="RM100000000FKQC_05" category="01"><name>PROCEDURE</name><testgrp id="RM100000000FKQC_05_0001" cellposition="1-1"><testtitle>CHECK TIRES</testtitle><content6><test1><ptxt>Check the size and condition of all 4 wheels.</ptxt><atten4><ptxt>The DTC is output when tire deformation or a difference in tire size is detected.</ptxt></atten4><spec type="other"><title>OK</title><specitem><ptxt>The diameter and air pressure of all 4 tires are the same.</ptxt></specitem></spec></test1><spec type="other"><title>Result</title><table><tgroup cols="1"><colspec colname="col1" colwidth="4.13in"/><thead><row><entry valign="middle" align="center"><ptxt>Proceed to</ptxt></entry></row></thead><tbody><row><entry valign="middle" align="center"><judge-value label="1"><ptxt>OK</ptxt></judge-value></entry></row><row><entry valign="middle" align="center"><judge-value label="2"><ptxt>NG</ptxt></judge-value></entry></row></tbody></tgroup></table></spec></content6><results><result label="1" cellposition="1-1"><action actiontype="next" cellposition="2-1" childid="RM100000000FKQC_05_0002"/></result><result label="2" cellposition="1-3"><action actiontype="end" cellposition="2-3"><actiontitle>REPLACE TIRES SO THAT ALL 4 TIRES ARE SAME SIZE</actiontitle><content6/></action></result></results></testgrp><testgrp id="RM100000000FKQC_05_0002" cellposition="2-1"><testtitle>RECONFIRM DTC</testtitle><content6><test1><ptxt>Clear the DTCs.</ptxt><ptxt>Click here<mlink><xref label="Seep00001" term-id-from="001" href="RM100000000FKQ3"/></mlink></ptxt><gts-info category="dtc-delete"><title>Chassis &gt; ABS/VSC/TRC &gt; Clear DTCs</title><gts-exec function-id="50002"><gts-ecu ecu-id="105"/></gts-exec><app-communication><app-param name="process-mode">0</app-param><app-param name="edit-mode">1</app-param><app-param name="insert-mode">0</app-param><app-param name="function-tab">0</app-param><app-param name="category-div">2</app-param><app-param name="category-div-name">Chassis</app-param><app-param name="ecu-id">105</app-param><app-param name="ecu-name">ABS/VSC/TRC</app-param><app-param name="gts-order">0</app-param><app-param name="selected-state">1</app-param></app-communication></gts-info></test1><test1><ptxt>Turn the ignition switch off.</ptxt></test1><test1><ptxt>Start the engine.</ptxt></test1><test1><ptxt>Drive the vehicle at a speed of 40 km/h (25 mph) or more for at least 60 seconds.</ptxt></test1><test1><ptxt>Check if the same DTC is output.</ptxt><ptxt>Click here<mlink><xref label="Seep00002" term-id-from="001" href="RM100000000FKQ3"/></mlink></ptxt><gts-info category="dtc-read"><title>Chassis &gt; ABS/VSC/TRC &gt; Trouble Codes</title><gts-exec function-id="50001"><gts-ecu ecu-id="105"/></gts-exec><app-communication><app-param name="process-mode">0</app-param><app-param name="edit-mode">1</app-param><app-param name="insert-mode">0</app-param><app-param name="function-tab">0</app-param><app-param name="category-div">2</app-param><app-param name="category-div-name">Chassis</app-param><app-param name="ecu-id">105</app-param><app-param name="ecu-name">ABS/VSC/TRC</app-param><app-param name="gts-order">0</app-param><app-param name="selected-state">0</app-param></app-communication></gts-info><spec type="other"><title>Result</title><table><tgroup cols="1"><colspec colname="col1" colwidth="4.13in"/><thead><row><entry valign="middle" align="center"><ptxt>Proceed to</ptxt></entry></row></thead><tbody><row><entry valign="middle" align="center"><judge-value label="1"><ptxt>DTC is output</ptxt></judge-value></entry></row><row><entry valign="middle" align="center"><judge-value label="2"><ptxt>DTC is not output</ptxt></judge-value></entry></row></tbody></tgroup></table></spec></test1></content6><results><result label="1" cellposition="2-1"><action actiontype="end" cellposition="3-1"><actiontitle>REPLACE BRAKE ACTUATOR ASSEMBLY</actiontitle><content6><ptxt>Click here<mlink><xref label="Seep00001" term-id-from="001" term-id-to="002" href="RM100000000FWYV"/><xref term-id-from="002" href="RM100000000YZ6Q"/></mlink></ptxt></content6></action></result><result label="2" cellposition="2-2"><action actiontype="end" cellposition="3-2"><actiontitle>USE SIMULATION METHOD TO CHECK</actiontitle><content6><ptxt>Click here<mlink><xref label="Seep00001" term-id-from="001" term-id-to="002" href="RM100000000G4HR"/><xref term-id-from="002" term-id-to="003" href="RM1000000010V0Q"/><xref term-id-from="003" href="RM10000000136PZ"/></mlink></ptxt></content6></action></result></results></testgrp></subpara></para></ttl></section></servcat></pub></tmc-service-paragraph>

=== randokuruza70/manual/manual/repair/contents/xml/RM100000000FKQS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tmc-service-paragraph SYSTEM "../dtd/paragraph-contents.dtd">
<tmc-service-paragraph><pub id="RM25T0E"><servcat id="_54"><name>Brake</name><section id="_029873"><name>BRAKE CONTROL / DYNAMIC CONTROL SYSTEMS</name><ttl id="_0135612"><name>ANTI-LOCK BRAKE SYSTEM</name><para id="RM100000000FKQS" category="J"><dtccode/><dtcname>Brake Warning Light Remains ON</dtcname><subpara id="RM100000000FKQS_01" category="03"><name>DESCRIPTION</name><content5><ptxt>When one of the following conditions is met, the brake warning light remains on:</ptxt><list1 type="unordered"><item><ptxt>The brake fluid level is insufficient.</ptxt></item><item><ptxt>The parking brake is applied.</ptxt></item><item><ptxt>The vacuum inside the brake booster decreases (for 1HZ and 1VD-FTV).</ptxt></item><item><ptxt>The brake warning light circuit is shorted.</ptxt></item></list1></content5></subpara><subpara id="RM100000000FKQS_02" category="03"><name>WIRING DIAGRAM</name><content5><figure type="1" translate="E"><graphic graphicname="C311982E01" width="7.168479331in" height="5.838041339in"/></figure></content5></subpara><subpara id="RM100000000FKQS_03" category="10"><name>CAUTION / NOTICE / HINT</name><content5><atten3><list1 type="unordered"><item><ptxt>for 1HZ and 1VD-FTV:</ptxt><ptxt>If there is a brake booster system malfunction, such as a problem with the response of the brake pedal when it is depressed, inspect the brake booster system first.</ptxt><ptxt>Brake booster inspection: Click here<mlink><xref label="Seep00001" term-id-from="001" href="RM100000000FWJX"/></mlink></ptxt><ptxt>Vacuum pump inspection: Click here<mlink><xref label="Seep00003" term-id-from="001" href="RM100000000FWK2"/></mlink> for 1HZ, Click here<mlink><xref label="Seep00002" term-id-from="001" href="RM100000000FWK9"/></mlink> for 1VD-FTV</ptxt></item><item><ptxt>Before disconnecting the connector, make sure that there are no problems with the connection.</ptxt></item><item><ptxt>After disconnecting the connector, make sure that the connector case and terminals are not deformed or corroded.</ptxt></item></list1></atten3></content5></subpara><subpara id="RM100000000FKQS_05" category="01"><name>PROCEDURE</name><testgrp id="RM100000000FKQS_05_0001" cellposition="1-1"><testtitle>INSPECT BRAKE MASTER CYLINDER RESERVOIR SUB-ASSEMBLY</testtitle><content6><test1><ptxt>Turn the ignition switch to ON.</ptxt></test1><test1><ptxt>With the brake fluid at the specified level, disconnect the A15*1 or I85*2 brake master cylinder reservoir sub-assembly (brake fluid level warning switch) connector and check the brake warning light.</ptxt><list1 type="nonmark"><item><ptxt>*1: for LHD</ptxt></item><item><ptxt>*2: for RHD</ptxt></item></list1><spec type="other"><title>Result</title><table><tgroup cols="1"><colspec colname="col1" colwidth="4.13in"/><thead><row><entry valign="middle" align="center"><ptxt>Proceed to</ptxt></entry></row></thead><tbody><row><entry valign="middle" align="center"><judge-value label="1"><ptxt>Brake warning light does not turn off</ptxt></judge-value></entry></row><row><entry valign="middle" align="center"><judge-value label="2"><ptxt>Brake warning light turns off</ptxt></judge-value></entry></row></tbody></tgroup></table></spec><atten4><ptxt>If the brake warning light turns off, the brake master cylinder reservoir sub-assembly (brake fluid level warning switch) has an internal short circuit.</ptxt></atten4></test1></content6><results><result label="1" cellposition="1-1"><action actiontype="next" cellposition="3-1" childid="RM100000000FKQS_05_0002"/></result><result label="2" cellposition="1-2"><action actiontype="end" cellposition="2-2"><actiontitle>REPLACE BRAKE MASTER CYLINDER RESERVOIR SUB-ASSEMBLY</actiontitle><content6><ptxt>Click here<mlink><xref label="Seep00001" term-id-from="001" term-id-to="002" href="RM100000000FWJL"/></mlink></ptxt></content6></action></result></results></testgrp><testgrp id="RM100000000FKQS_05_0002" cellposition="3-1"><testtitle>INSPECT PARKING BRAKE SWITCH ASSEMBLY</testtitle><content6><test1><ptxt>Remove the parking brake switch assembly.</ptxt><ptxt>Click here<mlink><xref label="Seep00001" term-id-from="001" href="RM100000000FV5H"/></mlink></ptxt></test1><test1><ptxt>Inspect the parking brake switch assembly.</ptxt><ptxt>Click here<mlink><xref label="Seep00002" term-id-from="001" href="RM100000000FV5I"/></mlink></ptxt><spec type="other"><title>Result</title><table><tgroup cols="1"><colspec colname="col1" colwidth="4.13in"/><thead><row><entry valign="middle" align="center"><ptxt>Proceed to</ptxt></entry></row></thead><tbody><row><entry valign="middle" align="center"><judge-value label="1"><ptxt>OK (for 1HZ and 1VD-FTV)</ptxt></judge-value></entry></row><row><entry valign="middle" align="center"><judge-value label="2"><ptxt>OK (except 1HZ and 1VD-FTV)</ptxt></judge-value></entry></row><row><entry valign="middle" align="center"><judge-value label="3"><ptxt>NG</ptxt></judge-value></entry></row></tbody></tgroup></table></spec></test1></content6><results><result label="1" cellposition="3-1"><action actiontype="next" cellposition="4-1" childid="RM100000000FKQS_05_0005"/></result><result label="2" cellposition="3-4"><action actiontype="jump" cellposition="4-4" childid="RM100000000FKQS_05_0008"><actiontitle>GO TO STEP 4</actiontitle></action></result><result label="3" cellposition="3-5"><action actiontype="end" cellposition="4-5"><actiontitle>REPLACE PARKING BRAKE SWITCH ASSEMBLY</actiontitle><content6><ptxt>Click here<mlink><xref label="Seep00001" term-id-from="001" href="RM100000000FV5H"/></mlink></ptxt></content6></action></result></results></testgrp><testgrp id="RM100000000FKQS_05_0005" cellposition="4-1"><testtitle>INSPECT VACUUM WARNING SWITCH ASSEMBLY</testtitle><content6><test1><ptxt>Start the engine.</ptxt></test1><test1><ptxt>Idle the engine.</ptxt></test1><test1><ptxt>Disconnect the I32 vacuum warning switch connector and check the brake warning light.</ptxt><spec type="other"><title>Result</title><table><tgroup cols="1"><colspec colname="col1" colwidth="4.13in"/><thead><row><entry valign="middle" align="center"><ptxt>Proceed to</ptxt></entry></row></thead><tbody><row><entry valign="middle" align="center"><judge-value label="1"><ptxt>Brake warning light does not turn off</ptxt></judge-value></entry></row><row><entry valign="middle" align="center"><judge-value label="2"><ptxt>Brake warning light turns off</ptxt></judge-value></entry></row></tbody></tgroup></table></spec><atten4><ptxt>If the brake warning light turns off, the vacuum warning switch has an internal short circuit.</ptxt></atten4></test1></content6><results><result label="1" cellposition="4-1"><action actiontype="next" cellposition="5-1" childid="RM100000000FKQS_05_0008"/></result><result label="2" cellposition="4-3"><action actiontype="end" cellposition="5-3"><actiontitle>REPLACE VACUUM WARNING SWITCH ASSEMBLY</actiontitle><content6><ptxt>Click here<mlink><xref label="Seep00001" term-id-from="001" href="RM100000000G6B2"/></mlink></ptxt></content6></action></result></results></testgrp><testgrp id="RM100000000FKQS_05_0008" cellposition="5-1"><testtitle>CHECK HARNESS AND CONNECTOR (BRAKE WARNING LIGHT CIRCUIT)</testtitle><content6><test1><ptxt>Turn the ignition switch off.</ptxt></test1><test1><ptxt>Disconnect the L25 and L26 combination meter assembly connectors.</ptxt></test1><test1><ptxt>Measure the resistance according to the value(s) in the table below.</ptxt><spec type="resistance"><title>Standard Resistance</title><table pgwide="1"><tgroup cols="3"><colspec colname="col1" colwidth="3.89in"/><colspec colname="col2" colwidth="1.06in"/><colspec colname="col3" colwidth="2.13in"/><thead><row><entry valign="middle" align="center"><ptxt>Tester Connection</ptxt></entry><entry valign="middle" align="center"><ptxt>Condition</ptxt></entry><entry valign="middle" align="center"><ptxt>Specified Condition</ptxt></entry></row></thead><tbody><row><entry valign="middle" align="center"><ptxt>L25-20 (PKBI) or S3-1 - Body ground</ptxt></entry><entry valign="middle" align="center"><ptxt>Always</ptxt></entry><entry valign="middle" align="center"><ptxt>10 kΩ or higher</ptxt></entry></row><row><entry valign="middle" align="center"><ptxt>L26-3 (SW) or A15-1 (+)*1 or I85-1 (+)*2 - Body ground</ptxt></entry><entry valign="middle" align="center"><ptxt>Always</ptxt></entry><entry valign="middle" align="center"><ptxt>10 kΩ or higher</ptxt></entry></row><row><entry valign="middle" align="center"><ptxt>L26-3 (SW) or I32-1*3 - Body ground</ptxt></entry><entry valign="middle" align="center"><ptxt>Always</ptxt></entry><entry valign="middle" align="center"><ptxt>10 kΩ or higher</ptxt></entry></row></tbody></tgroup></table></spec><list1 type="nonmark"><item><ptxt>*1: for LHD</ptxt></item><item><ptxt>*2: for RHD</ptxt></item><item><ptxt>*3: for 1HZ and 1VD-FTV</ptxt></item></list1></test1><spec type="other"><title>Result</title><table><tgroup cols="1"><colspec colname="col1" colwidth="4.13in"/><thead><row><entry valign="middle" align="center"><ptxt>Proceed to</ptxt></entry></row></thead><tbody><row><entry valign="middle" align="center"><judge-value label="1"><ptxt>OK</ptxt></judge-value></entry></row><row><entry valign="middle" align="center"><judge-value label="2"><ptxt>NG</ptxt></judge-value></entry></row></tbody></tgroup></table></spec></content6><results><result label="1" cellposition="5-1"><action actiontype="end" cellposition="6-1"><actiontitle>GO TO METER / GAUGE SYSTEM</actiontitle><content6><ptxt>Click here<mlink><xref label="Seep00001" term-id-from="001" term-id-to="002" href="RM100000000FSUM"/></mlink></ptxt></content6></action></result><result label="2" cellposition="5-2"><action actiontype="end" cellposition="6-2"><actiontitle>REPAIR OR REPLACE HARNESS OR CONNECTOR</actiontitle><content6/></action></result></results></testgrp></subpara></para></ttl></section></servcat></pub></tmc-service-paragraph>
