=== randokuruza70/manual/manual/brm/dtd/pub.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- #  DTD VERSION 1.6  UPDATE Mar. 04, 2014    -->
<!ELEMENT tmc-service-pub (dtd-version, pub)>
<!ELEMENT dtd-version EMPTY>
<!ATTLIST dtd-version
	version CDATA #REQUIRED
>
<!ELEMENT pub (name, models, brand, market-code, model-year-base?, plants, entry-date, publish-date, fin-date, term-base, revision)>
<!ATTLIST pub
	id ID #REQUIRED
	type (RM | NM | EM | BM) #REQUIRED
	xml:lang CDATA #REQUIRED
	format CDATA #IMPLIED
>
<!ELEMENT name (#PCDATA)>
<!ELEMENT models (model+)>
<!ELEMENT model (model-name, model-code+)>
<!ELEMENT model-name (#PCDATA)>
<!ELEMENT model-code (engine-code+)>
<!ATTLIST model-code
	code CDATA #REQUIRED
>
<!ELEMENT engine-code (#PCDATA)>
<!ELEMENT brand (#PCDATA)>
<!ELEMENT market-code (#PCDATA)>
<!ELEMENT model-year-base (year-base+)>
<!ELEMENT year-base EMPTY>
<!ATTLIST year-base
	term-id-from CDATA #REQUIRED
	model-year CDATA #REQUIRED
	term-id-to CDATA #IMPLIED
>
<!ELEMENT plants (plant+)>
<!ELEMENT plant (#PCDATA)>
<!ELEMENT entry-date (#PCDATA)>
<!ELEMENT publish-date (#PCDATA)>
<!ELEMENT fin-date (#PCDATA)>
<!ELEMENT term-base (term+)>
<!ELEMENT term (#PCDATA)>
<!ATTLIST term
	alt-pub-id CDATA #REQUIRED
	date CDATA #REQUIRED
	term-id-from CDATA #REQUIRED
>
<!ELEMENT revision (release+)>
<!ELEMENT release (term | correction+)>
<!ATTLIST release
	send-date CDATA #REQUIRED
>
<!ELEMENT correction (#PCDATA)>
<!ATTLIST correction
	para-id CDATA #REQUIRED
	id ID #REQUIRED
	sicr CDATA #IMPLIED
>

=== randokuruza70/manual/manual/ewd/control/pub.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tmc-service-pub SYSTEM "../dtd/pub.dtd">
<tmc-service-pub><dtd-version version="1.0"/><pub id="EM25T0E" type="EM" xml:lang="en"><name>LAND CRUISER Electrical Wiring Diagram</name><models><model><model-name>LAND CRUISER</model-name><model-code code="GRJ71L"><engine-code>1GR-FE</engine-code></model-code><model-code code="GRJ76L"><engine-code>1GR-FE</engine-code></model-code><model-code code="GRJ78L"><engine-code>1GR-FE</engine-code></model-code><model-code code="GRJ79L"><engine-code>1GR-FE</engine-code></model-code><model-code code="GRJ79R"><engine-code>1GR-FE</engine-code></model-code><model-code code="HZJ71L"><engine-code>1HZ</engine-code></model-code><model-code code="HZJ71R"><engine-code>1HZ</engine-code></model-code><model-code code="HZJ76L"><engine-code>1HZ</engine-code></model-code><model-code code="HZJ76R"><engine-code>1HZ</engine-code></model-code><model-code code="HZJ78L"><engine-code>1HZ</engine-code></model-code><model-code code="HZJ78R"><engine-code>1HZ</engine-code></model-code><model-code code="HZJ79L"><engine-code>1HZ</engine-code></model-code><model-code code="HZJ79R"><engine-code>1HZ</engine-code></model-code><model-code code="VDJ76L"><engine-code>1VD-FTV</engine-code></model-code><model-code code="VDJ76R"><engine-code>1VD-FTV</engine-code></model-code><model-code code="VDJ78L"><engine-code>1VD-FTV</engine-code></model-code><model-code code="VDJ78R"><engine-code>1VD-FTV</engine-code></model-code><model-code code="VDJ79L"><engine-code>1VD-FTV</engine-code></model-code><model-code code="VDJ79R"><engine-code>1VD-FTV</engine-code></model-code></model></models><brand>TOYOTA</brand><market-code>E</market-code><plants><plant>TMC</plant></plants><entry-date>20140612</entry-date><publish-date>20161221</publish-date><fin-date>20161222</fin-date><term-base><term alt-pub-id="EM25T0E" date="201408" term-id-from="001">Improvement</term><term alt-pub-id="EM25T1E" date="201608" term-id-from="002">Improvement</term><term alt-pub-id="EM25T2E" date="201701" term-id-from="003">Improvement</term></term-base><revision><release send-date="20140714"><term alt-pub-id="EM25T0E" date="201408" term-id-from="001">Improvement</term></release><release send-date="20160805"><term alt-pub-id="EM25T1E" date="201608" term-id-from="002">Improvement</term></release><release send-date="20161221"><term alt-pub-id="EM25T2E" date="201701" term-id-from="003">Improvement</term></release></revision></pub></tmc-service-pub>
